### ISSUE TITLE
IIS in-proc changes some responses from content-length to chunked

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#10773]
Converting Content-Length responses to Chunked is problematic as clients may be expecting that content-length value.

Frequently reproduces with:
```
            ctx.Request.Headers.ContentLength = ctx.Request.Path.Value.Length;
            await ctx.Response.WriteAsync(ctx.Request.Path.Value);
```

```
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Server: Microsoft-IIS/10.0
X-Powered-By: ASP.NET
Date: Mon, 03 Jun 2019 16:13:19 GMT

2
/a

```

Reproduces less frequently with:
```
            ctx.Request.Headers.ContentLength = ctx.Request.Path.Value.Length;
            return ctx.Response.WriteAsync(ctx.Request.Path.Value);
```

@jkotalik 

It's also known to change some auto-chunked responses to content-length, but that's less problematic as Content-Length is universally supported.

**Comment by PinpointTownes** [comment]
Could that be related to this old bug? https://github.com/aspnet/AspNetCore/issues/9139

**Comment by Tratcher** [comment]
Perhaps, though I'm not setting a content-type.

**Comment by anurse** [comment]
> Frequently reproduces with: ...
> Reproduces less frequently with: ...

Umm... Am I not seeing how these two are different? They look identical to me.

**Comment by Tratcher** [comment]
The response in this case should not have been compressable. It was also inconsistent and appeared to be timing related. The other issue was consistent and related to compression.

**Comment by Tratcher** [comment]
> > Frequently reproduces with: ...
> > Reproduces less frequently with: ...
> 
> Umm... Am I not seeing how these two are different? They look identical to me.

`await` vs `return`

**Comment by shapeh** [comment]
Hi, I was wondering if there are any news on this one?

**Comment by Tratcher** [comment]
No, is it causing an issue for you?

**Comment by shapeh** [comment]
@Tratcher - it seems to be fixed now. I updated to ASP.NET Core 3.1 and problem went away (previously on 2.2).

**Comment by davidfowl** [comment]
Does this still repro?

**Comment by shapeh** [comment]
I haven't experienced this bug since 3.1. Currently on 5.0. 
I guess it has been fixed.

**Comment by jkotalik** [comment]
Hm, I don't think we actively fixed this in 3.1 or 5.0... may be worth verifying.

**Comment by Tratcher** [comment]
I could still reproduce it last time I tried, but I don't remember how long ago that was.

**Comment by davidfowl** [comment]
Marking as help wanted and good first issue.

**Comment by jkotalik** [comment]
Not sure if this is a `good first issue`, what would the suggested fix be? I believe IIS/HTTP.sys is the one deciding whether it should be chunked or content-length.

**Comment by Tratcher** [comment]
It's something inside IIS, not Http.Sys.

**Comment by dlukyanov** [comment]
Having the following issue:
endpoint returns int 
when the return value between `0` and `9` and `content-type=application/json` 
iis returning this one byte with `content-encoding: chunked` but actually content is not well formatted because the only chunk contains just one byte returned by api when there should be a length+content.

for response `10+` i see the header `content-length: ...` in response.
