### ISSUE TITLE
Investigate why changing _ViewImports.cshtml doesn't automatically refresh impacted files in MacOS/Linux

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#14318]

**Comment by NTaylorMullen** [comment]
This may have been fixed already, still needs to be investigated.

**Comment by ryanbrandenburg** [comment]
If I modify _ViewImports.cshtml to remove 
`@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers` I still receive hover info for taghelpers, but I don't get completions anymore. It's possible that this is a hover-only problem. Investigating.

**Comment by NTaylorMullen** [comment]
> If I modify _ViewImports.cshtml to remove
> `@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers` I still receive hover info for taghelpers, but I don't get completions anymore. It's possible that this is a hover-only problem. Investigating.

Interesting, will be curious to see why completions are unique

**Comment by ryanbrandenburg** [comment]
My guess is that Hover results are cached somewhere, and that the cache is reset when the file is edited (but not when dependent files are edited). I tried to find such a cache but no luck so far.

**Comment by NTaylorMullen** [comment]
> My guess is that Hover results are cached somewhere, and that the cache is reset when the file is edited (but not when dependent files are edited). I tried to find such a cache but no luck so far.

ah, ya that would absolutely make sense. VSCode typically cache's hovers on a per line/token basis to prevent repeatedly querying the language server.

**Comment by ryanbrandenburg** [comment]
I'm spinning up a local VM to test this again. Some strange behavior in other areas is making me wonder if the extremely slow VM I was using for testing was messing with my tests.

**Comment by ryanbrandenburg** [comment]
The answer is... `/` vs `\`! Because we Normalize filepaths for the Import file paths [here](https://github.com/dotnet/aspnetcore-tooling/blame/master/src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectState.cs#L442), but the DocumentShapshotHandle.TargetPath is NOT Normalized the strings don't match when we attempt to do a lookup of the related documents of `Views\_ViewImports.cshtml`. I'm trying to figure out what the best solution to this is, it could potentially be very wide-ranging.

**Comment by NTaylorMullen** [comment]
> DocumentShapshotHandle.TargetPath is NOT Normalized

Super interesting that makes me think Linux MSBuild doesn't use `\`.

**Comment by ryanbrandenburg** [comment]
More specifically the lack of `\` seems to stem from https://github.com/microsoft/msbuild/blob/master/src/Tasks/AssignTargetPath.cs#L99.

**Comment by ryanbrandenburg** [comment]
Possibly this will get resolved by the same thing as https://github.com/dotnet/sdk/issues/10627, but we're going to take the mitigation in dotnet/aspnetcore-tooling#1581 for now.
