### ISSUE TITLE
.NET Core 3.0 + Angular 9 cli application called via the SpaServices extensions hangs in common configuration

### ISSUE THREAD

**Issue by miguellira** [dotnet/aspnetcore#17277]
### Describe the bug
Running a `.NET Core 3.0` + `Angular 9 cli` (version **9.0.0-rc.2** as of this post) with the angular cli build option `progress` set to `false` will hang until the `StartupTimeout` expires (default: 120 seconds)

### To Reproduce
I created a [repo](https://github.com/miguellira/Angular9CliTemplateBug) with a bare bones `.NET Core 3.0` + `Angular 9 cli` application to demo the bug. Simply clone, `npm build` the ClientApp folder, and `dotnet run`. Or you can follow the steps below to do this from scratch:

1. Ensure you have `.NET Core 3.0` installed
2. Create a .NET Core application with the current Angular templates by typing: `dotnet new angular -n HelloWorld`
3. Navigate to the `ClientApp` folder and install the Typescript helper functions required for Angular 9 by typing: `npm install tslib@latest`
4. Update to Angular 9 by typing: `ng update @angular/core @angular/cli --next`
5. Ensure the `progress` build option in the `angular.json` file is set to **false**
6. Run the application by navigating back to the root folder and typing: `dotnet run`
7. Launch a browser and navigate to: `https://localhost:5001`

The application will hang and eventually timeout.

### Further technical details
This appears to be caused by a change in how `ng serve` outputs to the console in the new Angular 9 CLI. The `AngularCliMiddleware` makes a `WaitForMatch()` method call against the standard output to signify when the Angular assets have been generated and the web server is ready to receive requests ([Line 84](https://github.com/aspnet/AspNetCore/blob/242890940e3e881ac605e5fc8b60b3c394e279a3/src/Middleware/SpaServices.Extensions/src/AngularCli/AngularCliMiddleware.cs#L84)). However, unless the `progress` option is set to **true** in the `angular.json` file you never see the expected line.

**UPDATE:** Updated to .NET Core 3.1 and Angular 9.0.0-rc.5. Same issue. New, simpler workaround is to modify your `npm start` script to perform a simple `echo` prior to `ng serve` ([see comment below](https://github.com/aspnet/AspNetCore/issues/17277#issuecomment-562433864))

**UPDATE (6/5/2020):** Lots of recent comments so I figured I'd share **exactly** what has worked for me with every release of `.NET` and `Angular` since my original post. Update your `package.json` like so:
```json
  "scripts": {
    "ng": "ng",
    "start": "echo hello && ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  }
```

**Comment by benelliott** [comment]
I also have this issue, but don't want to have to re-enable `progress` as [webpack's build progress output is routed to stderr](https://github.com/webpack/webpack/issues/3520), and this makes log4net go a bit nuts. If this could be solved in a different way it would be great - especially since listening for the dev server to spit out a specific string always felt a bit fragile.

**Comment by benelliott** [comment]
Actually, I don't think it's quite as simple as that - when I run `ng serve --progress=false` from my `App` directory, I still see the `listening on...` message.

I think the problem is that the message will only show on the first log output from the CLI (https://github.com/angular/angular-cli/blob/2c0efd834b08ac5ea166d88c0ff57cc35df19421/packages/angular_devkit/build_angular/src/dev-server/index.ts#L361) and this often takes longer than the five second default timeout after which .NET assumes that the CLI has died (https://github.com/angular/angular-cli/blob/2c0efd834b08ac5ea166d88c0ff57cc35df19421/packages/angular_devkit/build_angular/src/dev-server/index.ts#L361).

**Comment by elianora** [comment]
I am using .NET Core 3.1 and am encountering the same issue using `@angular/cli@~9.0.0-rc.5`. I never get the line expected by the `AngularCliMiddleware` from the Angular CLI. I have had it work correctly intermittently with both `--progress=true` and `--progress=false`.

I have **zero** clue as to why the following workaround works, but I consistently get the expected behavior if I add any statement that outputs to stdout prior to `ng serve` . My package.json script is `echo hello && npm serve --progress=false`, and I get the following reliably:

![image](https://user-images.githubusercontent.com/49993997/70253883-14af2080-1752-11ea-8935-ffe8ee4796b7.png)

**Comment by benelliott** [comment]
@elianora I spent some time digging around today and found this bug: https://github.com/aspnet/AspNetCore/issues/6146

Basically, the wrapper around `StdOut` might miss the `listening on...` message if it's at the end of a block with lots of newlines. As of Angular 9 this is a problem because the message is more likely to be printed in the same block as the webpack chunk output.

Could you check that you're referencing the latest version of the `SpaServices` packages? I think this fix is only present in 3.0.0 onwards.

**Comment by elianora** [comment]
I am currently referencing `3.1.0` and my `TargetFramework` is set to `netcoreapp3.1`.

**Comment by benelliott** [comment]
I've made a shamelessly hacky workaround which will do for now. Basically, I wrap the call to the Angular CLI in another Node script, and spoof the "open your browser on" message so that dotnet notices it.

You can try the workaround yourself:

1. Edit your `package.json` to rename your `start` script to `start:ng`
2. Add a new `start` script: `"start": "node start-dotnet.js"`. Your `package.json` should look like
```
        "start":  "node start-for-dotnet.js",
        "start:ng": "ng serve [or whatever you had before]",
```
3. Next to your `package.json`, add a file called `start-dotnet.js` with contents

```
// Hack to work around https://github.com/aspnet/AspNetCore/issues/17277

const { spawn } = require('child_process');

const portArgIndex = process.argv.indexOf('--port');

if (portArgIndex === -1) {
    throw new Error('Could not detect port number');
}

const port = process.argv[portArgIndex + 1];

console.log(`open your browser on http://localhost:${port}`);

const child = spawn(`cmd`, ['/c', `npm.cmd run start:ng -- --port ${port}`]);

console.log('Angular CLI started on PID', child.pid);

child.stdout.on('data', x => console.log(x && x.toString()));

child.stderr.on('data', x => console.error(x && x.toString()));

const sleep = () => {
    console.log('[Node.js keepalive]');
    setTimeout(sleep, 10000);
}

sleep();
```

**Comment by benelliott** [comment]
```
const child = spawn(`cmd`, ['/c', `npm.cmd run start:ng -- --port ${port}`]);
```

This line is Windows-specific, the Linux equivalent would be something along the lines of (but possibly not exactly)

```
const child = spawn(`npm`, ['run', `start:ng -- --port ${port}`]);
```

**Comment by elianora** [comment]
I run into no issues just using `echo something && ng serve`, but certainly will keep this in mind if I or anyone else I'm working with run into this issue again; when I get home I will see what the behavior on other operating systems looks like.

**Comment by benelliott** [comment]
Do you still have dotnet randomly choosing a CLI port when you do that?

**Comment by elianora** [comment]
I do, yes.

**Comment by miguellira** [comment]
@elianora suggestion of modifying the `npm start` script in your `package.json` by adding an `echo` statement prior to `ng serve` is enough to notify the AngularCliMiddleware the angular dev server is running. This is a better workaround than setting the `progress` flag to `true`.

BTW, can't see how it would matter but I did notice a subtle difference in how the Angular CLI outputs build info between Angular 8 and 9. Specifically, the Date and Hash information comes **_after_** the chunk information in Angular 9, where as it is the first line in Angular 8.
<code><pre>
info: Microsoft.AspNetCore.SpaServices[0]
      chunk {main} main.js, main.js.map (main) 60.7 kB [initial] [rendered]
      chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 140 kB [initial] [rendered]
      chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
      chunk {styles} styles.js, styles.js.map (styles) 9.94 kB [initial] [rendered]
      chunk {vendor} vendor.js, vendor.js.map (vendor) 2.99 MB [initial] [rendered]
      Date: 2019-12-06T04:20:45.321Z - Hash: 6ee5d8996273b040afe7 - Time: 5917ms **<-- This is now on one line and in a new location in Angular 9**
...
</pre></code>
Of course the actual string the AngularCliMiddleware is searching for: "open your browser on" is still being emitted by the angular_devkit package ([Line 303](https://github.com/angular/angular-cli/blob/b6863b6a306858713460fe2f8c0b9a8dc33b4365/packages/angular_devkit/build_angular/src/dev-server/index.ts#L303)).

**Comment by benelliott** [comment]
The `echo` workaround works for me too... so my workaround might be slight overkill :)

I don't fully get *why* it fixes it though...

**Comment by krisztiankocsis** [comment]
`ng server --verbose` also helps!

**Comment by krisztiankocsis** [comment]
But as verbose mode extremely pollutes the console, it would be better to detect readiness by a background HTTP GET instead of parsing the console output.

**Comment by pbarranis** [comment]
Due to a dependency, I'm unable to upgrade my .NET Core 2.2 app to 3 yet, so when I upgraded to Angular 9 I ran into this issue as well.  The echo solution saved me; thank you @elianora !

**Comment by blogcraft** [comment]
Echo solution works sometimes. Some other times, it just hangs after logging the chunks without printing this message:

`info: Microsoft.AspNetCore.SpaServices[0]
      : Compiled successfully.`

**Comment by JessyParis** [comment]
I encounter the same issue, and the "echo" workaround works for me (even if I don't understand why).
I don't know if it may help but 
with Angular 8 I had this lines
 
```
Microsoft.AspNetCore.SpaServices: Information: i ´¢ówds´¢ú: webpack output is served from /
i ´¢ówds´¢ú: 404s will fallback to //index.html

Microsoft.AspNetCore.SpaServices: Information: chunk {main} main.js, main.js.map (main) 1.29 MB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 284 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.css, styles.css.map (styles) 827 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 10.8 MB [initial] [rendered]
Date: 2020-02-20T14:29:22.992Z - Hash: 6706dd23fbf91f7a606a - Time: 20082ms

Microsoft.AspNetCore.SpaServices: Information: ** Angular Live Development Server is listening on localhost:50733, open your browser on http://localhost:50733/ **
i ´¢ówdm´¢ú: Compiled successfully.

```

With Angular 9: the line **404s will fallback to //index.html** is not there anymore
```
Microsoft.AspNetCore.SpaServices: Information: > evalorplastwebapp@0.0.0 start D:\Sources\Repos\Valorplast\eValorplastWebApp\ClientApp
> ng serve "--port" "51738"

Microsoft.AspNetCore.SpaServices: Information: chunk {main} main.js, main.js.map (main) 2.15 MB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 140 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.css, styles.css.map (styles) 889 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 12.6 MB [initial] [rendered]
Date: 2020-02-20T14:57:58.254Z - Hash: 081b4ea7fae540c9d19b - Time: 25137ms

Microsoft.AspNetCore.SpaServices: Information: ** Angular Live Development Server is listening on localhost:51738, open your browser on http://localhost:51738/ **
: Compiled successfully.
```

**Comment by kurtisauc3** [comment]
Still waiting on a fix for this. The echo solution doesn't work for me, but the node does. It's pretty ugly. Not sure if angular needs to change the way they emit to the console or the spa service extension needs to change the way it listens.

For anyone wanting to use Angular 9 with a netcore3 app, i would recommend going back to angular 8 until this gets resolved. Otherwise the node hack from @benelliott worked for me

**Comment by hordani** [comment]
What worked for me was changing "ng serve" to "ng serve --host 0.0.0.0" in package.json "start"

**Comment by zql9000** [comment]
Hello, I had the same problem and I performed several tests on different projects and simply saving some change in a file inside the ClientApp folder, it makes angular recompile and then VS2019 / VSCode recognizes the node server, without changing any configuration. I comment this in case it helps anyone.

I also tested in the solution of the repo miguellira/Angular9CliTemplateBug with VS 2019 Community and VS Code and works.

**Comment by ravimsnetdev** [comment]
> What worked for me was changing "ng serve" to "ng serve --host 0.0.0.0" in package.json "start"

this worked for me

**Comment by markoj21** [comment]
The above solutions did not work for me but this did

1. In your Startup class, replace the spa.UseAngularCliServer invocation with the following:
   spa.UseProxyToSpaDevelopmentServer("http://localhost:4200");
2. In a command prompt, switch to the ClientApp subdirectory, and launch the Angular CLI development server:
  cd ClientApp
  npm start

**Comment by kemsky** [comment]
`EventedStreamReader` is simply buggy:

```csharp
               //  should use LastIndexOf and process all lines, otherwise loop will stuck on _streamReader.ReadAsync until some file is modified
                var lineBreakPos = Array.IndexOf(buf, '\n', 0, chunkLength); 
                if (lineBreakPos < 0)
                {
                    _linesBuffer.Append(buf, 0, chunkLength);
                }
                else
                {
                    _linesBuffer.Append(buf, 0, lineBreakPos + 1);
                    OnCompleteLine(_linesBuffer.ToString());
                    _linesBuffer.Clear();
                    _linesBuffer.Append(buf, lineBreakPos + 1, chunkLength - (lineBreakPos + 1));
                }
```

**Comment by natenho** [comment]
> I have **zero** clue as to why the following workaround works, but I consistently get the expected behavior if I add any statement that outputs to stdout prior to `ng serve` . My package.json script is `echo hello && npm serve --progress=false`, and I get the following reliably:

@elianora, according to the screenshot, the command is
`echo hello && ng serve --progress=false`
(instead of **npm** serve)

It's fine as a workaround for now, thanks.

**Comment by Cito** [comment]
Four months now and still no proper solution for this?

**Comment by blogcraft** [comment]
I guess no contributor has looked at this yet. Still, that's a bad thing. 😕

**Comment by aprilmaraat** [comment]
Mine works by editing `"start":  "ng serve --port 4200"`

**Comment by nhonlvsoict** [comment]
> What worked for me was changing "ng serve" to "ng serve --host 0.0.0.0" in package.json "start"

this worked for me, thankss

**Comment by kemsky** [comment]
@mkArtakMSFT, `EventedStreamReader` is already fixed in master, related issues #6306, #6146.

**Comment by ice19942335** [comment]
> What worked for me was changing "ng serve" to "ng serve --host 0.0.0.0" in package.json "start"

This helped me!

**Comment by hmheng** [comment]
seems like issue still persists in 3.1.3 spa extension, even with "echo"

**Comment by sismino** [comment]
hi,
waiting for fix, this works under win os;
edit package.json like this:

"start": "@echo open your browser on http://localhost:4200 & ng serve & rem",

**Comment by hmheng** [comment]
it seems like

> hi,
> waiting for fix, this works under win os;
> edit package.json like this:
> 
> "start": "@echo open your browser on http://localhost:4200 & ng serve & rem",

thanks for the help. it works for a while. very soon it will hang again.

**Comment by hmheng** [comment]
> I've made a shamelessly hacky workaround which will do for now. Basically, I wrap the call to the Angular CLI in another Node script, and spoof the "open your browser on" message so that dotnet notices it.
> 
> You can try the workaround yourself:
> 
> 1. Edit your `package.json` to rename your `start` script to `start:ng`
> 2. Add a new `start` script: `"start": "node start-dotnet.js"`. Your `package.json` should look like
> 
> ```
>         "start":  "node start-for-dotnet.js",
>         "start:ng": "ng serve [or whatever you had before]",
> ```
> 
> 1. Next to your `package.json`, add a file called `start-dotnet.js` with contents
> 
> ```
> // Hack to work around https://github.com/aspnet/AspNetCore/issues/17277
> 
> const { spawn } = require('child_process');
> 
> const portArgIndex = process.argv.indexOf('--port');
> 
> if (portArgIndex === -1) {
>     throw new Error('Could not detect port number');
> }
> 
> const port = process.argv[portArgIndex + 1];
> 
> console.log(`open your browser on http://localhost:${port}`);
> 
> const child = spawn(`cmd`, ['/c', `npm.cmd run start:ng -- --port ${port}`]);
> 
> console.log('Angular CLI started on PID', child.pid);
> 
> child.stdout.on('data', x => console.log(x && x.toString()));
> 
> child.stderr.on('data', x => console.error(x && x.toString()));
> 
> const sleep = () => {
>     console.log('[Node.js keepalive]');
>     setTimeout(sleep, 10000);
> }
> 
> sleep();
> ```

While waiting to proper fix, i think this is best hack that seems working fine.
thank you @benelliott

**Comment by mkArtakMSFT** [comment]
Sorry that this is taking this long. We've have been busy with Blazor WebAssembly during last several months. The good news is that we're getting to the end of it and will investigate this in approximately a month.
Just moved this to 5.0-preview5 release to make sure this doesn't get ignored any further, given the amount of feedback this has accumulated.
/cc @danroth27

**Comment by varghesep** [comment]
The angular app created via [Visual Studio 2019 16.6 Preview](https://visualstudio.microsoft.com/vs/preview/) is version 8 not 9. Will it support **Angular 9** in the future?

**Comment by mkArtakMSFT** [comment]
> 
> 
> The angular app created via [Visual Studio 2019 16.6 Preview](https://visualstudio.microsoft.com/vs/preview/) is version 8 not 9. Will it support **Angular 9** in the future?

We haven't added official support for Angular 9 yet. The issue I've referenced above is tracking that work. We'll just make sure this issue is resolved when doing that.

**Comment by hmheng** [comment]
thank you so much @mkArtakMSFT . While it is being brought forward to 5.0-preview, will it be fixed in next patch of .NET Core 3.1 too considering the timeline of 5.0 RTM is still months away from now?

**Comment by hmheng** [comment]
![bde93cce-5137-4e82-844f-bd11993edb83](https://user-images.githubusercontent.com/11830387/79935171-d313dd80-8486-11ea-851d-aea64ce981e6.jpg)

@benelliott 's solution is definitely working, however, I noticed that it will cause memory hogging and not releasing the nodejs process after each debug session. I'm not sure if it is caused by VS2019 for not releasing it while opening new nodejs instance or it is caused by NG9.

**Comment by naveedahmed1** [comment]
I also noticed this, and I believe its the issue with VS2019.

**Comment by dstj** [comment]
> [...] I noticed that it will cause memory hogging and not releasing the nodejs process after each debug session. I'm not sure if it is caused by VS2019 for not releasing it while opening new nodejs instance or it is caused by NG9.

This is definitely not new, I have been having that problem for a long time now, see #5239 and #5204

**Comment by naveedahmed1** [comment]
`taskkill /f /im node.exe` will close all running `node` processes, I was wondering if this could be added to `.csproj` file like  `<Exec Command="taskkill /im node.exe /f"></Exec>` and have it executed after each debug session ends?

**Comment by hmheng** [comment]
> `taskkill /f /im node.exe` will close all running `node` processes, I was wondering if this could be added to `.csproj` file like `<Exec Command="taskkill /im node.exe /f"></Exec>` and have it executed after each debug session ends?

With taskkill like that, it may be killing other nodejs process that are opened in another instance/solution of VS2019.

**Comment by benelliott** [comment]
> With taskkill like that, it may be killing other nodejs process that are opened in another instance/solution of VS2019?

Yes definitely, that would kill every Node process on the box.

**Comment by naveedahmed1** [comment]
Anyway to target only node processes that are launched by Visual Studio?

BTW I dont have anyother node processes running and this seems to work in my case. But the issue is it terminates the processes only when next time I start debug.

**Comment by artar94** [comment]
@mkArtakMSFT Still, this is not fixed in master.
Here is added a line with a large number of trailing zeros, which sometimes leads to a hang of the thread.
https://github.com/dotnet/aspnetcore/blob/1815d37d752ec1066726c1be7c52e808b11145f1/src/Middleware/SpaServices.Extensions/src/Util/EventedStreamReader.cs#L114
Only the significant portion of the buffer needs to be added:
```cs
_linesBuffer.Append(buf, startPos, chunkLength - startPos);
```
Perhaps the problem is deeper and Append should not freeze, but there is definitely an error in this code.

**Comment by viveksinghnegi7** [comment]
Encountered the same issue. Waiting for a permanent solution. 
Sometime it works after re-starting the Visual Studio but after some time the exception occurs.
**An unhandled exception occurred while processing the request.**
**TimeoutException:** _The Angular CLI process did not start listening for requests within the timeout period of 20 seconds. Check the log output for error information._

`System.TimeoutException: The Angular CLI process did not start listening for requests within the timeout period of 20 seconds. Check the log output for error information.
   at Microsoft.AspNetCore.SpaServices.Extensions.Util.TaskTimeoutExtensions.WithTimeout[T](Task`1 task, TimeSpan timeoutDelay, String message)
   at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task`1 baseUriTask, CancellationToken applicationStoppingToken, Boolean proxy404s)
   at Microsoft.AspNetCore.Builder.SpaProxyingExtensions.<>c__DisplayClass2_0.<<UseProxyToSpaDevelopmentServer>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

**Comment by sergioadh** [comment]
> I run into no issues just using `echo something && ng serve`, but certainly will keep this in mind if I or anyone else I'm working with run into this issue again; when I get home I will see what the behavior on other operating systems looks like.

Mine looks like this so I have reference back here:
`"start": "echo \"fix https://github.com/dotnet/aspnetcore/issues/17277\" && ng serve --watch",`

**Comment by Rinsen** [comment]
> Sorry that this is taking this long. We've have been busy with Blazor WebAssembly during last several months. The good news is that we're getting to the end of it and will investigate this in approximately a month.
> Just moved this to 5.0-preview5 release to make sure this doesn't get ignored any further, given the amount of feedback this has accumulated.
> /cc @danroth27

This will not be fixed in 3.x? 
It's a bummer if that's the case since 5.0 is not a LTS version and it will be a great challenge to use in products that customers buy and run because of the "short" support window.

**Comment by smaugcoath** [comment]
Bfff... I've just seen that I'm not alone here... 6 AM and still working.

**Comment by dobrinsky** [comment]
For me, none of the solutions posted here worked, not even changing "ng serve" to "ng serve --host 0.0.0.0" in package.json "start"

But another change in the same place found in:

https://github.com/angular/angular-cli/issues/16961

change "start": "ng serve" to "start": "echo Starting... && ng serve"

worked

**Comment by hembk44** [comment]
> I am using .NET Core 3.1 and am encountering the same issue using `@angular/cli@~9.0.0-rc.5`. I never get the line expected by the `AngularCliMiddleware` from the Angular CLI. I have had it work correctly intermittently with both `--progress=true` and `--progress=false`.
> 
> I have **zero** clue as to why the following workaround works, but I consistently get the expected behavior if I add any statement that outputs to stdout prior to `ng serve` . My package.json script is `echo hello && npm serve --progress=false`, and I get the following reliably:
> 
> ![image](https://user-images.githubusercontent.com/49993997/70254270-d0705000-1752-11ea-9b0b-b570cda6c110.png)
> 
> EDIT: Adding environment info:
> 
> * Windows 10 build 18363
> * Node.js 12.13.0
> * Visual Studio Code 1.40.2
> * dotnet CLI 3.1.100
> * @angular/cli 9.0.0-rc.5

It worked for me.

**Comment by phil123456** [comment]
I tried everything mentioned above and nothing works, after a fresh update and install of vs2019 and .NET core libraries

**Comment by phil123456** [comment]
Just updated visual studio and still the same issue
I tried everything above, nothing works
how could this be released while nobody can't create a default angular app????

**Comment by dev-thinks** [comment]
After tried all workarounds, the below alternate worked for me.

https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-3.1&tabs=visual-studio#run-ng-serve-independently

**Comment by MatGhp** [comment]
angular.json -> architect -> build -> options -> "progress": true

worked for me

**Comment by jayeshinho** [comment]
After trying a lot, what finally worked for me was setting `echo something && ng serve` and then under debug button (by clicking the arrow down button next to project name) in Visual Studio, select project name instead of IIS Express.  I have used this setup on 2 or 3 projects without fail.

**Comment by jrcunningham21** [comment]
I have tried all of the workarounds, but another thing that worked for me was running Visual Studio as an admin which seemed to fix the issue without any code changes. Does this work for anyone else?

The workarounds that have worked for me are:

- echo something && ngserve
- ng serve --verbose
- https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-3.1&tabs=visual-studio#run-ng-serve-independently

**Comment by JessyParis** [comment]
I use VS in admin mode too and I got the issue sometimes.
Echo something workaround works for me

**Comment by deckerbd** [comment]
Is this fix not being back-ported to .NET Core 3.1 LTS? I feel like a large amount of devs may not be able to update to ASP.NET 5 until it's in LTS.

**Comment by miguellira** [comment]
Every few days both new and senior .NET developers stumble upon this bug and post a comment to share their frustration. Although I can sympathize, as the OP it surprises me since I thought I did a decent job describing various workarounds including the simplest one that has worked for me with every release of `.NET` or `Angular` since my original post: 

update the `scripts` section in `package.json` by adding an `echo` statement prior to `ng serve`

Lately, however, some of the posts have expressed concerns of back porting the "fix" to .NET 3.x so I wanted to share my thoughts:

1. It can be argued that updating the dotnet templates to include the `echo` statement by default is harmless enough, however, that would mask the underlying issue which I guess is why that simple change hasn't been done.

2. More importantly, this bug only surfaces during the _**development**_ of a .NET application using the `SpaServices` extensions since that is when you would proxy requests to a local instance of your Angular app served up via `ng serve`. When you actually publish your .NET application, your Angular app gets compiled and those artifacts are published to a `dist` folder which the `SpaServices` extensions will serve as static files. The Angular CLI at this point is no longer in the picture.

Hope that clears up the back porting concern.

I will also update the original post to better describe the simplest workaround.

**Comment by hoksource** [comment]
i am getting this error

https://github.com/angular/angular/issues/34970

is the error related to this issue?
should i just remove below from main.ts? what are the implication if i do this?

`
export { renderModule, renderModuleFactory } from '@angular/platform-server';
`


or should i just keep using angular 8?

**Comment by kemmis** [comment]
@hoksource you can just remove that line. that issue is not related to this one. when the angular cli upgrades your app to v9 it dumps that line into main.ts in a subjectively dumb way. it's helpful to have it there for those using universal (if i remember correctly), but it's problematic for those of us not using universal.

**Comment by kemmis** [comment]
FWIW, I was able to fix this in my project by forking my own copy of the Microsoft.AspNetCore.SpaServices.Extensions project (from the 2.1 release branch), and then dropping in the internal EventedStreamReader class from the .net 5 release branch. This seems to solve the problem where it never sees the line saying "open your browser...".

**Comment by blogcraft** [comment]
Looks that aspnet team no longer cares about the Angular template... net5 still installs angular 8 even tho angular 11 is almost out.

**Comment by paulcsiki** [comment]
This also affected me but the workaround worked with .NET Core 3.1 and Angular 10.1.

**Comment by pbarranis** [comment]
I recently upgraded from Angular 10.1.1 to 10.2.3, and this problem inexplicably got a *lot* more frequent, to the point of being unusable.  This is with the echo and progress solutions in place.  So I tried upgraded my Microsoft.AspNetCore.* NuGet packages to 3.1.10, and I also tried upgrading Angular to 11.0.4.  With those upgrades done, I am unable to get any solution mentioned above to work aside from "Run "ng serve" independently" from the Docs.

That is to say, for me, this problem now has no known solution other than completely abandoning the automatic background Ng CLI process, as it is now non-functional 100% of the time.  I can't explain why or who it suddenly broke except for the upgrade from Angular 10.1.1 to 10.2.3.

**Comment by blogcraft** [comment]
> I recently upgraded from Angular 10.1.1 to 10.2.3, and this problem inexplicably got a *lot* more frequent, to the point of being unusable.  This is with the echo and progress solutions in place.  So I tried upgraded my Microsoft.AspNetCore.* NuGet packages to 3.1.10, and I also tried upgrading Angular to 11.0.4.  With those upgrades done, I am unable to get any solution mentioned above to work aside from "Run "ng serve" independently" from the Docs.
> 
> 
> 
> That is to say, for me, this problem now has no known solution other than completely abandoning the automatic background Ng CLI process, as it is now non-functional 100% of the time.  I can't explain why or who it suddenly broke except for the upgrade from Angular 10.1.1 to 10.2.3.
> 
> 
> 
> It's unthinkable to me that a problem this bad has been ignored by MSFT for over a year now.

I upgraded to .Net 5 and it got way better. With 3.1 it was unusable.

**Comment by mrjohnr** [comment]
I have this bug only on debugging (F5) on .NET 3.1+Angular 11.0.5.only work after I try for 9 or 10 times,too hard to debug...
tried all fixes but none works

**Comment by dmsch** [comment]
The only workaround that worked for us (.NET 3.1.11 + Angular 11.0.5): 
 https://github.com/angular/angular-cli/issues/16961#issuecomment-620022661

**Comment by heart2friend** [comment]
Giving timeout exception for .Net 5.0 and angular 11.0.4

TimeoutException: The Angular CLI process did not start listening for requests within the timeout period of 0 seconds. Check the log output for error information.

Here are the things I tried none of them worked.

1. Increased timeout in Startup.cs
2. Set progress flag to true in agular.json
3. Tried echo in ng serve command
4. Tried --aot and --prod flags in ng build
5. Upgraded global version of Angular to 11.0.4
6. Removed externally installed node.js
7. Setup environment variable to point node.js and ng path from the visual studio environment.

https://developercommunity.visualstudio.com/t/Angular-1104--Net-50-Giving-Timeout/1393855

**Comment by svrooij** [comment]
@heart2friend as a last try you can always start the angular process in a different terminal and switch the spa service to running on developer port.

**Comment by antkers** [comment]
This workaround fixed it in my case:
[https://stackoverflow.com/a/61454189](https://stackoverflow.com/a/61454189)

**Comment by blogcraft** [comment]
@heart2friend updating from .Net Core 3.1 to .Net5 fixed it for me.

**Comment by heart2friend** [comment]
> @heart2friend as a last try you can always start the angular process in a different terminal and switch the spa service to running on the developer port.

Thank you @svrooij it worked. This shouldn't be the ideal solution but it's working is lot more for me.

For those who are struggling with same problem here is the interim solution  

1. Run the angular app using the command prompt (ng serve) from the ClienApp directory.  
2. Replace spa.UseAngularCliServer(npmScript: "start"); with spa.UseProxyToSpaDevelopmentServer("http://localhost:4200"); in Startup.cs file.

app.UseSpa(spa =>
            {
                // To learn more about options for serving an Angular SPA from ASP.NET Core,
                // see https://go.microsoft.com/fwlink/?linkid=864501

                spa.Options.SourcePath = "ClientApp";

                if (env.IsDevelopment())
                {
                    //spa.UseAngularCliServer(npmScript: "start");
                    spa.UseProxyToSpaDevelopmentServer("http://localhost:4200");
                }
            });

This works like a charm!

**Comment by SkrupSulten** [comment]
@benelliott Thanks, your fix is the only solution that works for me. There is one issue though. The Node.js process is kept alive after closing the debug session in VS Code. If I restart a few times I soon run out of memory and the CPU usage skyrockets.

Is there a way to kill the Node.js process?

Right now I'm debating whether to give up and just start the .Net part and frontend parts separately.

**Comment by bthharper** [comment]
Has there been any progress on this?

I have several developers with exactly this problem and all the workarounds are no longer working.   This does seem to have become worse with Angular 12, where the compilation time has increased.

I am now resorting to running the angular client separately before running the hosting application in the IDE.

**Comment by SkrupSulten** [comment]
@bthharper 

Our fix was to have this script in package.json

`"start": "ngserve",`

And then a file ngserve.cmd with the following:

```
@echo ** Angular Live Development Server is listening on localhost:%~2, open your browser on http://localhost:%~2/ **
ng serve %1 %~2
```

We have no issues now, but an actual fix from MS would of course be better.

**Comment by mkArtakMSFT** [comment]
Closing this as we've changed the approach how the SPA project templates work now. You can find more details about this in the issue tracking that work: https://github.com/dotnet/aspnetcore/issues/27887
