### ISSUE TITLE
Visual studio lost intellisense for Blazor Components

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#17660]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/770539/visual-studio-lost-intellisense-for-blazor-compone.html)._

---
[regression] [worked-in:16.3.3]
After updating vs 16.3.3 visual studio gives errors on markup.
Example "Found markup element with unexpected name "EditForm". If this is intended to be a component, add a using directive for its namespace.

---
#### Visual Studio Feedback System on 10/9/2019, 11:31 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 10/23/2019, 07:02 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Georgi Petrov Yaramov on 11/8/2019, 01:58 PM: 

<p>Same happened in VS 16.3.8</p>

#### Melvin C Wiley on 11/23/2019, 02:38 PM: 

<p>Same happened in VS 16.3.10</p>

#### Melvin C Wiley on 11/26/2019, 05:26 AM: 

<p>This also happens in VS2019 16.4 Preview 6. This appears to be a problem with intellisense. Is this being looked into? Is there a patch to fix this?</p>

#### Aaron Mckee on 12/5/2019, 11:37 AM: 

<p>Its like using notepad to develop again... please fix!</p>

---
#### Georgi Petrov Yaramov solved on 11/8/2019, 01:59 PM, 0 votes: 

<p>Same happened on VS 16.3.8</p>

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by mkArtakMSFT** [comment]
It looks like you're using older version of VS. Please upgrade to the latest released version (16.4) and it should be fixed there.

**Comment by roxas0zero** [comment]
this issue happened to me on VS 16.4.2 I fixed it be restarting VS, you may wanna make sure that it's completely fixed...

**Comment by YairHalberstadt** [comment]
I can confirm this occuring on 16.5 preview 1

**Comment by wmgdev** [comment]
Issue on vs 16.4.3
If I add a Component.razor via Add>New Item>Razor Component intellisense seems to be OK
If I copy, paste then rename an existing Component.razor to e.g. ComponentX.razor intellisense does not pick up the file rename and instead picks up <Component__Copy>

**Comment by rogierhofboer** [comment]
Same here with VS 16.5.0 Preview 2.0
After creating the default template project, Intellisense for the components doesn't work.
(SurveyPrompt, NavMenu etc.) 
Restarting VS fixes it. Please re-open this issue.

**Comment by mayur-ekbote** [comment]
The problem still exists. This is how you can reproduce: Create a blazor component. Rename it through rename option in solution explorer. The editor cannot find the class and the build does not go ahead.

**Comment by mkArtakMSFT** [comment]
Reopening as this seems to be impacting many people.
@NTaylorMullen can you please look into this? Thanks!

**Comment by poco1980** [comment]
Also This issue exist in VS code

**Comment by NTaylorMullen** [comment]
> Also This issue exist in VS code

Would you mind doing the "Report a Razor issue"command and pasting the output here (In addition to manually copying the OmniSharp Log's?
![image](https://user-images.githubusercontent.com/1579269/74187998-7bddcb00-4c02-11ea-9a0f-036e64d6a4a2.png)

**Comment by jshovan** [comment]
I had this problem with 16.4.6. Realizing this is in the preview I installed the preview version of VS (16.5.0 Preview 5.0) and at first glance, it seems to be working. I have not done much with it yet but at least I am not getting the red underlines and warning on valid code/markup.

**Comment by talldaniel** [comment]
I have this problem too.  Sometimes only one or two errors, but today there are 117 prompting me to look for a solution.
It still compiles and runs, but when I get a real error, it makes it more difficult to find.

**Comment by NTaylorMullen** [comment]
If anyone is able to provide a repro project that will enable us to investigate further.

**Comment by talldaniel** [comment]
@NTaylorMullen I checked to see if it was something I was doing by downloading an app that I had seen on Pluralsite that is on github called, "BethanysPieshopHRM"  It demonstrates the problem on my machine.
I also dont have a clean install, I have been installing Visual Studio on this computer for about five years and a lot of different versions show up in my programs list.
Also, I had BethanysPieShop open at the same time as my project, but that shouldn't matter.  
The problem seems related to the caching of namespaces, and it doesn't always happen.  If you don't see the error, open a few .razor pages, or drag and drop a file to a different folder.
Also I have noticed that it "may be" true that if I leave a space after a name, it increases the odds of it happening, <MyComponent /> instead of <MyCompontent/>  
And finally it seems to happen to the most recently created components even when it was otherwise okay.
Oh, and copy-pasting a component seems to increase the changes it will cause this.
So, lots of hints as to possible cause, my money is on the caching.

**Comment by talldaniel** [comment]
@NTaylorMullen 
I was able to duplicate this problem by opening BethanysPieShopHRM and then
1.  Copy paste the file "AddEmployeeDialog.razor to the Components folder.  (from pages)
2. Copy the entire EditForm on this page and paste it below.
3.  Attempt to compile and wait for error.
4.  Restore the content of AddEmployeeDialog.razor (but leave it where it was moved to.)
5.  Build and it fails.

![BethaniesPieshop error](https://user-images.githubusercontent.com/5903328/77233055-2df1a680-6b62-11ea-8ce5-1caf0e1aca87.png)

**Comment by talldaniel** [comment]
Also there is another similar problem that i am experiencing today.
I was having the above problem on two folders where there was a file by the same name as the folder in each.  I renamed the folder and restarted.
The Intellisense now shows the old folder name, which it previously said was not there, and was not on intellisense and does not show the new folder name.
If a restart doesn't fix it, then I will edit this message.

**Comment by NTaylorMullen** [comment]
Sadly renaming Blazor files/folders does not always yield a great experience today (requires close/re-open of file) and in some cases the older file name will persist along side the newer one. If you want to work around this bug you can delete your bin/obj directories and re-compile.

**Comment by talldaniel** [comment]
@NTaylorMullen Thanks you!
This fixed the issue.  I had a couple of errors that either were being drowned with noise, or else weren't showing at all. 
For people who have my specific problem, of actual errors being masked, I would call this a fix (so far) as I haven't had this problem again since doing this.
I won't try renaming anything though(smile)

**Comment by NTaylorMullen** [comment]
@talldaniel does this fix all of your issues? As in did deleting bin/obj fix the closed/open issues you were seeing?

**Comment by talldaniel** [comment]
@NTaylorMullen 
The short answer is "Yes".

1. I did a clean and then cleared the obj folder, and then when I started VS again it showed legit errors without listing 50 to 100 other errors that were bogus along with it.
(an empty folder was referenced in _imports and the name of a Templated Component was accidentally used as the name of one of the components to show, inside the Template Component.)
I fixed the two legit errors and this fixed the problem.
I do not know if the legit errors were listed among the usually fifty or so ( 25 to 125) illegitimate errors, but they probably were.

This does not explain why the Pluralsite code also shows the same issue, but perhaps it too has a empty folder or ... 
Thank you for your help, as it is now even easier to develop in Blazor.

**Comment by talldaniel** [comment]
Just had the problem again.
I had a legit error and I fixed it, and then  two false errors were being reported having to do with namespaces.  (Cannot find ...)
I closed all windows, re-opened and that fixed it this time.

**Comment by stevebond007** [comment]
I am also having this issue with all 7 components in my Blazor Server Side project.
I've tried all of the above fixes (clean & delete obj/bin folders). Problem persists.
All dependencies are latest preview versions, as is VS2019.

**Comment by talldaniel** [comment]
@stevebond007 
 Make sure you don't have any empty folders listed in the imports file.
95% of the time there is a actual "error" though I wouldn't think simply having an empty folder referenced should count as an error (for example) but it does.
When it is not an actual error, it should only list a few errors, in my experience.

**Comment by lxman** [comment]
VSCode 1.43.2
dotnet new blazorserver
Open Folder
Found markup element with unexpected name 'NavLink'. If this is intended to be a component, add a @using directive for its namespace.
Builds and runs.
Just a bit annoying.

**Comment by ThatMouse** [comment]
This just happened to me (VS2019 16.5.4). In my case it was all my .razor layout files Header, Nav, Footer, that I had once copy/pasted/renamed, but that was several reboots ago. The errors went away after restarting VS. Not sure how to repeat this, but IntelliSense is always slow to update and with Blazor, it's frequently giving me false errors that build just fine.

**Comment by talldaniel** [comment]
Likely it is easy to repeat, just write a line of code that does not compile correctly and it will all come back, and stay back after you fix he line of code.

**Comment by tripleacoder** [comment]
I have the error in Version 16.5.3.

**Comment by talldaniel** [comment]
Yeah, the problem is back for me too.  
I wish it had started when I was still deciding on the tech to use for my site, as I would have never chosen Blazor, even though I think it is otherwise great, as this is just too big of an issue.
As an example, I typed a few characters in Visual Studio then opened a browser, went to my email, searched for a particular email and then went back to VS and it was still locked up.

**Comment by talldaniel** [comment]
This is actually with no errors

![image](https://user-images.githubusercontent.com/5903328/80897993-2a018a00-8cb3-11ea-94b1-d8fa8af7da11.png)

**Comment by talldaniel** [comment]
@NTaylorMullen This bug seems to have made itself worse.  I had seven errors, none of them the one that was real.  (same old) But the app wouldn't run.
So, I changed to another computer, and still had the error.
I rolled back to a known good build, it ran once, but I made a tiny change and it failed to run after that.
I undid the change, and it still wont run.
So, I have a 30,000 lines project that is dead in the water because it now seems to be treating these fake errors as real errors.
Any suggestions?

**Comment by NTaylorMullen** [comment]
Those errors you linked @talldaniel I believe are fixed in 16.7-preview2 (not yet released)

**Comment by talldaniel** [comment]
Do you suppose the delay will be more than a month?

**Comment by NTaylorMullen** [comment]
It'll be released to a preview channel before a month but it wont be "official" for some tiem

**Comment by talldaniel** [comment]
Thanks, how do I find the preview channel?  I have just been clicking on "check for updates"

**Comment by talldaniel** [comment]
Nevermind, I think I know what you mean. 
Thanks for the help.

**Comment by talldaniel** [comment]
also, probably not related, but it happened after the latest update of windows.

**Comment by talldaniel** [comment]
I was able to confirm that this is what is happening.  I removed the unfound variables error for all seven of them, did a builld and ran, and it 'works" and then I put one of them back, did an F12 and confirmed the variable was good and then tried to run it and it failed for not found for the variable I had just F12ed.
So, apparently someone "fixed' that it would still run when it reported an error.

**Comment by talldaniel** [comment]
Thanks Taylor,
Blazor is the best development environment **ever** and I look forward to when it is stable.

**Comment by talldaniel** [comment]
Also, I noticed in the Blazor faq that this is the most common error people are having, and it claims that the problem comes from using the wrong version of Visual studio.
I just installed Windows 10 pro and then VS 2019 on a new computer yesterday, and have this problem, so I don't think that is right, unless there is something else I am supposed to do to get the "right" version.
I don't think it is caused from using the wrong version of VS, unless there is something I am missing.

**Comment by saddlebear** [comment]
![2020-05-20_15-28-43](https://user-images.githubusercontent.com/9727091/82499414-dcf12680-9aae-11ea-936f-4ec978108665.jpg)

Still happening in VS 16.6.0.   Generated new project+solution.  Seems to error out on components and or templates.   Dead in the water here.

**Comment by talldaniel** [comment]
I suggest you copy the code in the file that is failing and paste it into notepad and save.
Delete the Razor page
Do a clean, restart VS and do another clean
(You can also delete the obj folder, but it it seems to be a small risk causing other problems with TFS/GIT (not sure))
Create a new Razor file with the same name, but located in the Pages folder.
Copy the notepad text and paste that into this file.

**Comment by JoeMooreBrk** [comment]
I am not a razor expert and I'm simply trying to publish code written by someone else.  This code happens to be core.  In my case, it runs fine in debug without showing any errors, but publish shows the errors and won't publish.  A quick scan of this topic did not show any particular relationship to publishing vs debugging--forgive me if it's there.  Is there someplace to vote the severity up or a way to make it publish regardless of the error?

**Comment by talldaniel** [comment]
Microsoft no longer fixes bugs for those things for which there is a work around, which results in one having to know their way around a software package in order to know the work around's.  (one of the downsides of the Agile Methodology is that bugs "don't count")
For the error you are talking about, I believe the solution is to go to Build/Publish and then select "manage Azure App Service Settings and then delete a setting. (I dont' remember which setting)
Make sure you are updated to 16.7.2 and if you are, then google to find the setting to delete.  One of the things I remember about this bug is that it has been around since 2017. (But since it has a work around they will probably never fix it.)

**Comment by mayur-ekbote** [comment]
I wouldn't use such a strong language but I absolutely agree with the sentiment: random crashes, lack of *any* kind of refactoring support, and general unpredictability. There are so many different crashes that I have stopped reporting. VS is probably the best IDE in the market. However, for blazor, is only slightly better than VIM.

**Comment by ataraxia89** [comment]
Maybe that was a little strong, I've removed the language but it is very irritating. Just a note, the component that I was having a problem referencing I've now moved to a new components project and it is now working. So it was:

The project [MyApplication].Web.App contained a Components folder and all components within that folder were in the namespace [MyApplication].Web.App.Components. These components were referenced by pages within [MyApplication].Web.App.Pages (folder and namespace) and the references were broken.

I created a new project within the solution called [MyApplication].Web.App.Components and moved everything from the Components folder in the Web.App project into the new project, then set the Web.App project to reference the Web.App.Components project, so the components project is forced to build first. The references are now working with no issues.

I still get a load of intellisense errors, mainly in the .razor files, but the solution does actually build and run properly.

**Comment by NTaylorMullen** [comment]
Hey folks, just chiming in to say we hear your pain and are working hard to make Blazor's tooling experience excellent. So some high level information on where we're going here: The existing Razor editor, the one that's been there from the beginning and the one that you've all been using, has a lot of power but of course also has a LOT of quirks and inadequacies that hinder our ability to innovate & address issues for all of you folks in a timely manner. So in the background we've been re-thinking how our Blazor editor works from the ground up and actually in 16.7 we exposed a preview feature flag to enable a [new experimental Razor editor](https://devblogs.microsoft.com/aspnet/new-experimental-razor-editor-for-visual-studio/):
![image](https://user-images.githubusercontent.com/2008729/91070328-7454a100-e5eb-11ea-8b06-da441e471019.png)

Now hold your breath. It currently has some significant known issues. Issues like incoherent coloring, misaligned errors, crashing when you close a solution or inability to reopen documents without losing C#/HTML IntelliSense BUT it's design is significantly simpler then anything we've had previously and will serve as the foundation for us to innovate and deliver you all a better overarching experience faster!

So all of that said, please hang in there! We're hard at work to make everything better. If you're feeling adventurous try out the new editor and send us feedback. Totally can understand the pain of working in an environment where the editing experience hinders your ability to deliver.

If you're extra curious, tomorrow (8/25/2020), we (the Razor/Blazor tooling team) have a .NET community standup where we'll be sharing a general update on what's been going on and what's planned to happen and when.

**Comment by ataraxia89** [comment]
I have been using the experimental editor and constantly keeping my version of VS 2019 up-to-date, but now I not only get spurious errors from Intellisense but also from the experimental editor (with purple lines, oddly, though it doesn't bother me) telling me there are markup issues, but not specifying what they are.

I did have a sweet sweet moment this afternoon where all errors disappeared. I don't think I had done anything, but when it happened I have to admit I just sat and looked at it, remembering what error-free code looks like...

The project still builds, runs and works (it's partly running in live production) as mentioned before, but Intellisense and the new editor are having a complete hissy fit.

**Comment by ThatMouse** [comment]
Thanks for sharing some good news @NTaylorMullen !!

**Comment by NTaylorMullen** [comment]
> Is this standup something that's public or is this just for our information to show it's being actively discussed?

Public for all! https://www.youtube.com/watch?v=nci0ZMoGcLM

**Comment by NTaylorMullen** [comment]
> but Intellisense and the new editor are having a complete hissy fit.

If you're willing to spend some time helping us capture enough logs / investigate we'd love to dive into what's happening on your end. If that's something you're interested in please file a new issue with some of the specific issues you're seeing (can mention me) and we can see what's going on.

**Comment by ataraxia89** [comment]
> If you're willing to spend some time helping us capture enough logs / investigate we'd love to dive into what's happening on your end. If that's something you're interested in please file a new issue with some of the specific issues you're seeing (can mention me) and we can see what's going on.

I'll file a new issue but would prefer not to share too much source code of this project in a public domain, unless I can reproduce this in a test project. The absolute number one problem for me is the number of false negatives. I have a genuine issue somewhere in my code but it's completely swamped by 100+ other "errors" that aren't actually errors.

**Comment by mayur-ekbote** [comment]
> I did have a sweet sweet moment this afternoon where all errors disappeared. I don't think I had done anything, but when it happened I have to admit I just sat and looked at it, remembering what error-free code looks like...
> 
> The project still builds, runs and works (it's partly running in live production) as mentioned before, but Intellisense and the new editor are having a complete hissy fit.

Keep an eye on the lower left corner. Even when it shows it's "ready" don't believe it. Wait till the animation stops and some more. False errors would disappear. Works for me about 90% of time.

**Comment by ataraxia89** [comment]
I dearly wish it was that simple, but I still get errors even after I've run the program then stopped it again. Errors also linger, I've removed files completely and the errors are still there. I am constantly closing VS, clearing bin and obj, reopening then rebuilding and it is sooooooooo time consuming it's unbearable.

**Comment by mayur-ekbote** [comment]
> I dearly wish it was that simple, but I still get errors even after I've run the program then stopped it again. Errors also linger, I've removed files completely and the errors are still there. I am constantly closing VS, clearing bin and obj, reopening then rebuilding and it is sooooooooo time consuming it's unbearable.

You might have already tried, but just in case: instead of deleting bin and obj, have you tried deleting .vs folder?

**Comment by ataraxia89** [comment]
Just tried that, no difference, here's just a snapshot of what I'm dealing with atm:

![image](https://user-images.githubusercontent.com/48794242/91191089-3d19e900-e6ec-11ea-9182-98122cfdeb50.png)

Also, all errors are doubled up if you look at the line numbers.

**Comment by ataraxia89** [comment]
Here's another, the RegisterNewUser and ResetPassword components are currently running, fully functional, in a live environment in exactly the same state as they are at the moment:

![image](https://user-images.githubusercontent.com/48794242/91191680-faa4dc00-e6ec-11ea-8ad9-2b880256bcf3.png)

**Comment by talldaniel** [comment]
Sometimes if you look in the output window, the very first error thrown is "the one".
There does seem to be some new bugs in the latest code, as I just ran into a situation where it would not build due to an error, but then the error would go away a few seconds after the build fails. Luckily I had only copy/pasted some code, so I undid it and restarted the computer, and then it worked.

I would suggest, that if all your components are not already in the directory "Page" that you move them there.

**Comment by NTaylorMullen** [comment]
> Just tried that, no difference, here's just a snapshot of what I'm dealing with atm:

Would you be willing to provide a simple repro app for us to look into it further?

**Comment by talldaniel** [comment]
I think Blazor is getting a bit of an unfair rep for bugs.  I have had bugs very similar to both of the bugs listed above since they were posted.
In one case it was because there is a bug in deployment where it defaults to "Package = 1" and you have to change it.  If you don't then you get an error that is pretty vague.  I don't remember what it was exactly, but it is something like "there was an error"  Not a bug that the Blazor team can fix, or is responsible for.

I don't know if I got the same bug as the other one above, but I got one that was very similar.  I had used the "rename" functionality of VS and it did not rename everything, but there was no error generated for the incorrectly named word left behind, but there was like a hundred errors displayed that were all obviously incorrect.  VS has done that for years, where if you have one error it will show 100.

**Comment by darrylluther** [comment]
I see this was closed almost a month ago, but this still happens on a nearly daily basis using VS 2019 16.7.3. When I get this error I open the component it is complaining about and then go back and the error is no longer present. Still annoying to have to do that when the compile breaks.
![image](https://user-images.githubusercontent.com/4376954/95485987-4c28c380-0947-11eb-9739-912d027fbc4e.png)

**Comment by andrewaggb** [comment]
> Just tried that, no difference, here's just a snapshot of what I'm dealing with atm:
> 
> ![image](https://user-images.githubusercontent.com/48794242/91191089-3d19e900-e6ec-11ea-9182-98122cfdeb50.png)
> 
> Also, all errors are doubled up if you look at the line numbers.

I'm in the exact same situation.  Over 220 errors reported, but it compiles fine, runs fine.  Generally when I quit visual studio and start it again my custom components show up properly for a while but they typically break eventually.  It's pretty annoying but the output window always shows the actual issues when I build and similarly dotnet watch run only shows real errors so it's not a complete deal breaker.  I'm not going to have the time to make a repro right now but I thought I'd just add that I'm experiencing this as well.

Current using:
Microsoft Visual Studio Community 2019
Version 16.8.1

I was using the previews with .net 5 rc support before that and had the same issues.

![image](https://user-images.githubusercontent.com/1630971/99201093-66379c00-2766-11eb-8018-2a238d3ffb1a.png)

**Comment by andrewaggb** [comment]
![image](https://user-images.githubusercontent.com/1630971/99201123-b44c9f80-2766-11eb-8891-73b1c768ebe5.png)

This is what it looks like after restarting VS. (All the errors are gone, components show up fine).  But it'll break within the first 30 minutes or so.  I touch and sometimes modify a fair number of files as I have some code generation, so it could be something like that.

**Comment by andrewaggb** [comment]
If there are logs I could send them, but I'm not sure if it creates logs somewhere?  I could also send my project privately if it's necessary.  I just don't have a lot of time to debug it right now and it's definitely in the inconvenient category and not a complete show stopper (for me at least).

**Comment by NTaylorMullen** [comment]
> If there are logs I could send them, but I'm not sure if it creates logs somewhere? I could also send my project privately if it's necessary. I just don't have a lot of time to debug it right now and it's definitely in the inconvenient category and not a complete show stopper (for me at least).

When you're in the "broken" state if you could take a full heap dump of VS that'd be a good place for us to start.

**Comment by andrewaggb** [comment]
I've never taken a heap dump of a process before.  I created a dump from task manager by selecting the copy of vs and choosing to create a dump file.  If that's what you're asking for, the file is ~2gb.  
I'm not sure how to provide a private link/message on github... So I've created a one-drive link that expires Nov 30th.
https://1drv.ms/u/s!AvJ3E6KtF9fujtBa2lYgKkfrRTtNuQ?e=6S0DhR
pwd is blazordump

**Comment by NTaylorMullen** [comment]
@andrewaggb thank you for the dump! I took a look and it's definitely interesting. I can see that your project indeed doesn't currently understand the "PropertyEdit" type which has pushed me in another direction. While your project is broken could you take a dump of `ServiceHub.RoslynCodeAnalysisService32.exe`? This is the process that analyzes C#'s understanding of your projects and returns all of the potential Blazor components. 

I believe I've narrowed down the issue to two things:
1. We're failing to properly serialize/deserialize the result from the ServiceHub.RoslynCodeAnalysisService32.exe
2. The ServiceHub.RoslynCodeAnalysisService32.exe doesn't have a proper representation of the in-proc server

**Comment by andrewaggb** [comment]
@NTaylorMullen just wanted to say I didn't work on this project much today and it didn't enter a crashed state.  I hope to work on it more this week and I'll update the thread when it happens again.  It was happening very regularly so I'll probably trigger it again soon.

**Comment by andrewaggb** [comment]
@NTaylorMullen This is a dump of the ServiceHub.RoslynCodeAnalysisService.  The filename doesn't say 32 and windows doesn't indicate it's 32 bit but I think it's the one you're after.

https://1drv.ms/u/s!AvJ3E6KtF9fujtBhOAox5Ks-lP9-Ag?e=tjJMp1
pwd blazordump

**Comment by NTaylorMullen** [comment]
@andrewaggb Thank you for the log! So I'm almost positive I know what's breaking but not why. To be extra certain could you do the following the next time it errors for you:

1. Pause what you're doing until both dumps have been captured
1. Build the project.
1. Get another dump of devenv.exe
1. Get another dump of ServiceHub.RoslynCodeAnalysis.exe
1. Provide which Blazor element is incorrectly unrecognized/erroring, I've been looking for PropertyEdit as indicated in your screenshots but want to make sure.

With all this info we'll be able to see if there's a synchronization issue between VS/OOP host (since you'll be taking the dumps back to back). Thank you again for all the legwork here, we're gonna figure this one out!

**Comment by andrewaggb** [comment]
@NTaylorMullen 

https://1drv.ms/u/s!AvJ3E6KtF9fujtBtoR5YWEAacozy1w?e=X7BY41
pwd blazordump

Captures of both visual studio and the roslyn service.
Some of my custom components are recognized (eg the EditButtons component), but others such as PropertyEdit, ColumnCard, ColumnEdit are not.

I have several dotnet watch runs on different powershell terminals for 2 api projects and the blazor project.  I normally let dotnet watch run do the builds but I do periodically build in visual studio as well.  For the most part I just edit/write code and save periodically.  dotnet watch pick up the changes.  I sometimes run a custom tool that will update some of the code files to do things like adding missing resx entries, update api client methods and dto's to match entities, create/update fluent validation models and whatnot.  This doesn't change files unless there are changes but could modify 20-60 files in short order (probably similar to the visual studio search/replace with the open files option).  I've occasionally had dotnet watch runs conflict with doing a visual studio build saying a file is in use and I have to stop the watch run to get visual studio to build.  I'm not sure if file locking/in-use could affect VS and Roslyn but I thought I'd mention it in case it's relevant.

**Comment by tanvrkhan** [comment]
Would love to see a solution for this also. I have been living with this every day for so long now.

**Comment by talldaniel** [comment]
tanvrkham,
I accidentally created a similar problem in VS 2015 in a large solution with 120 projects.  I replaced a dll with a test dll (same one, except the new one was a later version.) in several of the projects.

What happened next wasn't the same problem you and many others are having, but it was pretty similar.  

When I did something to create one error, there were hundreds of errors and everything on the screen was red, even though it shouldn't have been as the Intellisense had broken. 

Anyway, I suspect it has something to do with a dll, if it isn't what Taylor (above) thinks it is since I saw such a similar issue in VS 2015 with a dll.

**Comment by talldaniel** [comment]
I would like to point out that this is a critical bug and if it is not fixed, then long term a Blazor app would be **unmaintainable**.
I am using a third party vendor set of Blazor controls and they (unfortunately) included a breaking change in almost every control to update for an otherwise minor update.
There are hundreds of fake errors generated so I had no idea how to fix the actual problem. After struggling with it for hours, giving up and then coming back to it again I was unable to even begin to fix it.
I created a ticket with their support and the support got escalated to the point that they were digging in my code to try to help me, but even their top level support was unable to fix it.
So now, they are bringing in the developers for each component and we will possibly be able to fix it at that point, though I seriously doubt the developers will be able to fix it.
So you can see, that if Blazor reaches more popularity it would not be practical for third party control developers to bring in their developers to help fix a compile error due to the fact that the IDE reports hundreds of errors that are not really true.  
And for that reason this bug is a critical show stopping bug that must be fixed because otherwise applications that use third party controls are unmaintainable.

**Comment by thepigeonfighter** [comment]
Can confirm I run into this problem on the daily. Blazor is such an amazing framework that I work through the pain, but I'd like to be part of the solution. I just had to restart visual studio 3 times to get the fake errors to disappear. While like everyone has been saying on this thread renaming components usually causes things to break, things also break at unpredictable intervals at other points. At this point I would be unsure of how to reproduce the scenarios that causes the break.

**Comment by NTaylorMullen** [comment]
We've made a LOT of changes in this area and have resolved a lot of the underlying concerns that contribute to this in the 16.9-Preview3 release. Would it be possible for folks to give that build a shot and let us know if you see the buggy behavior reproduce?

[Install VS Preview](https://visualstudio.microsoft.com/vs/preview/)

**Comment by talldaniel** [comment]
@NTaylorMullen 
I had two computers arrive in the mail today so I installed the preview version on one of them and pulled my code from the repository.   There were a few minor issues with that, but probably nothing related to Blazor.
After I got the solution to build I saw that it no longer marks Components as "not existing" when they do in fact exist.  So that is a  good improvement.

I did a test with some nuget package updates where i know there is breaking changes, and it performed well. I was previously unable to update these controls  because of this bug ,and now it appears I may be able to.  It used to list hundreds of errors and now it lists 14 errors, which are probably correct. 

But when I rolled back the nuget updates by reverting the project file, the compile errors I had previously seen when I had updated the package continued to show as build errors and two using statements were also red and showing as errors in the code.   

I  restarted Visual Studio and it built and these errors went away.
So I would say it seems a lot  better after a quick look, but there is still a problem.  When I reverted the file in Team Explorer, the cached results were not updated is my guess.   
 
I will be using it a bit over the weekend, if I see anything else I will update this message .

**Comment by Thaina** [comment]
Using vscode with dotnet 5 blazorwasm template also face this

> Found markup element with unexpected name 'SurveyPrompt'. If this is intended to be a component, add a @using directive for its namespace.

**Comment by BenjaminCharlton** [comment]
I have this issue too on the latest Microsoft Visual Studio Community 2019 Version 16.8.5

**Comment by Arthuraafn** [comment]
> I have this issue too on the latest Microsoft Visual Studio Community 2019 Version 16.8.5

+1

**Comment by boukenka** [comment]
+1 with Visual Studio Version 16.9.0 Preview 4.0

**Comment by NTaylorMullen** [comment]
> +1 with Visual Studio Version 16.9.0 Preview 4.0

Ah interesting, would not have expected this in 16.9 preview builds. @boukenka would you mind providing the following when you see a Blazor component not get recognized:
- Taking a dump of devenv.exe
- Taking a dump of ServiceHub.RoslynCodeAnalysisService.exe
- Providing the file name & project name for where you're seeing the unrecognized component
- The unrecognized component name

**Comment by boukenka** [comment]
Unfortunately, I cannot answer your request to help you.
I have already implemented a workaround. The name of my component was "_PageTitle_". 
After I renamed it to "_WebPageTitle_", the problem disappeared.

**Comment by talldaniel** [comment]
if there is already an error then it is common for Visual Studio itself to display a few hundred extra errors.  I can remember this behavior as far back as VS 2015 and it probably goes back further.  The most recent example is when I did something wrong linking to a DLL and got around 900 errors.

Is anyone still seeing this error when there are no legitimate errors?

I hope it is not a VS error as if it is, it will probably never be fixed, but I think it probably is.  (And is not a Blazor error anymore)

**Comment by andrewaggb** [comment]
My experience so far with the 16.9.0 Preview 4.0 is that intellisense doesn't work at all in razor pages.  I think it recognizes my blazor components better (my error list isn't full and there is color highlighting) but I get no code autocompletions in the code blocks so I've gone back to the non-preview VS which is working much better for me.  I'm way less productive without variable and function autocompletes/suggestions.

**Comment by NTaylorMullen** [comment]
> My experience so far with the 16.9.0 Preview 4.0 is that intellisense doesn't work at all in razor pages. I think it recognizes my blazor components better (my error list isn't full and there is color highlighting) but I get no code autocompletions in the code blocks so I've gone back to the non-preview VS which is working much better for me. I'm way less productive without variable and function autocompletes/suggestions.

Would you mind doing the "Report a Problem" option in VS and possibly provide additional information like the project and/or repro steps? We'd love to investigate further, that definitely sounds broken 😄

**Comment by lucent-sea** [comment]
This issue comes and goes for me all the time.  In the below screenshot, those two components are in the same namespace.  

![image](https://user-images.githubusercontent.com/20995508/109402436-af24f200-790a-11eb-844b-557a0bc31296.png)

**Comment by mjhillman** [comment]
Likewise...
![image](https://user-images.githubusercontent.com/50423474/110243554-e60d9000-7f28-11eb-8164-1408aaa7728a.png)

The references are in the imports file.  All works properly despite the red squiggles.

See the project at https://github.com/mjhillman/HITS.Blazor.GridDemo

**Comment by jlsandin** [comment]
Visual Studio 16.9.1 and this issue is still open... I have lost hours trying to work out many "errors" cause intellisense cannot detect you change a component name or a variable name in a component and nobody notices this change.
Real issue is with intellisense but you cannot compile your solution cause changes are not noticed!!!!

Yes, closing and reopening helps... but you cannot be doing this if you need to make several "small" changes... Surprised cause this issue is from December 2019...

**Comment by talldaniel** [comment]
@jlsandin 

i saw a clue on this issue that is probably wrong, but just in case, are you using TFS for your repository?

Anyway, 
 here are the 'rules' for using Blazor for now (and probably forever)

Never copy/paste anything
Never rename a file
Never put a .razor file anywhere except in the Pages folder, or in a folder inside the Pages folder.
Check in very often so if there is a weird issue it can easily be reverted.
Use the codebehind/base files whenever there is a significant amount of C# code for a .razor file.
Avoid putting logic in the display sections, better to use a Template Selector. (I never have problems related to Templates.)

**Comment by jlsandin** [comment]
> @jlsandin
> 
> i saw a clue on this issue that is probably wrong, but just in case, are you using TFS for your repository?
> 
> Anyway,
> here are the 'rules' for using Blazor for now:
> 
> Never copy/paste anything (If you really need to, then first paste it to notepad and then save notepad, and then copy it from notepad, and then paste it.)
> Never rename a file

Thank you @talldaniel .
No TFS. My components as such are under a Components folder not under Page folder. Under Page folder I just have razor files with a Page directive.
And yes, I'm using a third party toolset. This is where I get more problems when making any renaming.

I will follow these 'rules' from you. Sound quite 'logical' after the mess I've been into :-D Thanks again!!

**Comment by talldaniel** [comment]
@jlsandin 
Thanks,
Blazor is the best development environment ever, IMO, and it is worth learning to work around these things, though there is no working around the third party tools problem.  

I don't have a lot of confidence they will ever fix these bugs because Microsoft uses Agile and Agile gives zero points for fixing bugs.

**Comment by NTaylorMullen** [comment]
Ok so we've been plugging away at what could be happening here (there's a lot!!) and we believe this issue will be fixed by our investments into the new experimental Razor editor. If you'd like to try this tooling out you can [download the latest VS preview release](https://visualstudio.microsoft.com/vs/preview/) and check the following preview feature checkbox (Tools -> Options -> Environment -> Preview Features):

![image](https://user-images.githubusercontent.com/2008729/87990285-8b5a1d80-ca98-11ea-914f-949fa326d9e3.png)

Would folks mind trying out the new editor to see if it resolves these issues for you and report back?

**Comment by sgwin** [comment]
@NTaylorMullen - enabling that feature fixed the issue with me! Visual Studio Pro 2019 - 16.9.1
Thank you!

**Comment by talldaniel** [comment]
@NTaylorMullen 
Updated to 16.10.0 preview 1 and enabled the experimental editor.

It does get rid of a lot of the incorrect squigglies, but it had problems with css code, especially the use of @@Media 
Other css has identical lines of code and it did not have a problem with it.

After I commented out the offending css code, it now has these two errors both on the same component.  

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0104	'ValidationSummary' is an ambiguous reference between 'Microsoft.AspNetCore.Components.Forms.ValidationSummary' and 'Microsoft.AspNetCore.Mvc.Rendering.ValidationSummary'		C:address.razor		

and 

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1662	Cannot convert lambda expression to intended delegate type because some of the return types in the block are not implicitly convertible to the delegate return type		C:address.razor

**Comment by NTaylorMullen** [comment]
> Severity Code Description Project File Line Suppression State
> Error CS0104 'ValidationSummary' is an ambiguous reference between 'Microsoft.AspNetCore.Components.Forms.ValidationSummary' and 'Microsoft.AspNetCore.Mvc.Rendering.ValidationSummary' C:address.razor

Ahhh this one we've fixed in 16.10-Preview2 in the new experimental Razor editor!

> Error CS1662 Cannot convert lambda expression to intended delegate type because some of the return types in the block are not implicitly convertible to the delegate return type C:address.razor

If you can provide a repro for this we'd love to dig in more!

> It does get rid of a lot of the incorrect squigglies, but it had problems with css code, especially the use of @@media
> Other css has identical lines of code and it did not have a problem with it.

Would you mind filing a separate issue for this? We'd love to ensure this works in the new experimental editor!

**Comment by talldaniel** [comment]
Hi,
When I switched back to the regular non-experimental Razor editor it gave me the line number of the errors and I was able to fix the second one.  (I commented out the validation one)
I had understood the @ inside of quotes to be optional when specifying a method to call for a click, but removing the @ symbol for the click= "@method" fixed that one.
I can fill out an issue on the css tonight, thanks for fixing these problems

**Comment by lucent-sea** [comment]
I'm trying the experimental editor.  So far, so good.  I'll report back if I encounter any issues.  Thanks!

**Comment by djscott00** [comment]
I was having this issue today whenever I published and then tried to follow up with a build. I switched to the experimental editor as suggested and that seems to have resolved the issue for me.

**Comment by lucent-sea** [comment]
I ended up having too many issues with the experimental Razor editor.  Auto-completions often didn't work correctly (e.g. tab completing on `override OnInitializedAsync`  doesn't add the protected keyword, Task return type, or call to base method).  And the intellisense would freeze occasionally, like below:

![image](https://user-images.githubusercontent.com/20995508/112002066-c2c41280-8adc-11eb-97eb-c4f1791272c9.png)

**Comment by NTaylorMullen** [comment]
> Auto-completions often didn't work correctly (e.g. tab completing on `override OnInitializedAsync` doesn't add the protected keyword, Task return type, or call to base method).

This is coming in 16.10-Preview2 but I can totally understand how this could be a blocker for many! Thank you again for giving it a shot!

> And the intellisense would freeze occasionally, like below:

Ooooo those freezes are worrisome! When you encounter that freeze would you mind doing the [Report a Problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) flow in Visual Studio? It should give us all the information we need to act on it.

**Comment by jlsandin** [comment]
Many issues here with experimental Razor editor. Sometimes when overriding, on tab for completing,  the editor deletes all my code. Fortunately, undoing works fine 😉

**Comment by mayur-ekbote** [comment]
> I ended up having too many issues with the experimental Razor editor. Auto-completions often didn't work correctly (e.g. tab completing on `override OnInitializedAsync` doesn't add the protected keyword, Task return type, or call to base method). And the intellisense would freeze occasionally, like below:
> 
> ![image](https://user-images.githubusercontent.com/20995508/112002066-c2c41280-8adc-11eb-97eb-c4f1791272c9.png)

I faced the same problem. Most of the time this new editor just hangs showing only the progress bar.
Another problem is that the new editor doesn't seem to show css classes.

**Comment by lucent-sea** [comment]
@NTaylorMullen   Thanks for the response!  I'll try enabling it again soon and see if I can repro.  Lacking time at the moment, though.

For what it's worth, I'm overall enjoying the heck of Blazor.  I'm still amazed at how much more productive it enables me to be.  Since I've started using it in my side projects, it's like I've doubled the amount of free time I have to work on them.

**Comment by NTaylorMullen** [comment]
> I faced the same problem. Most of the time this new editor just hangs showing only the progress bar.

If you could do the Report a Problem flow in Visual Studio I'd love to dig in more!

> Another problem is that the new editor doesn't seem to show css classes.

Coming in 16.10 😉

**Comment by mayur-ekbote** [comment]
> If you could do the Report a Problem flow in Visual Studio I'd love to dig in more!
 How to do this? Because the only way to close the modal is to kill the VS process. Is there any way to report the problem after restarting?

**Comment by NTaylorMullen** [comment]
> How to do this? Because the only way to close the modal is to kill the VS process. Is there any way to report the problem after restarting?

Ah, so if you start the "Report a problem" dialog prior to the hang there's a "Record steps" piece, that you can run prior so that al necessary information is captured

**Comment by markarlsson365** [comment]
Have had problem with intellisense not working in razor components (without code behind). No problem with intellisense in components with code behind. Did not know I had the experimental Razor editor activated. Deactivated it and intellisense is back in the non code behind components. Got curious and activated it again (restarted VS) aand intellisense is gone. Did this 3 times with the same result. I'm just so glad right now... Thank you @NTaylorMullen for recommending looking in to the exp. Razor editor. I know your advice was the opposite but it helped me so thank you!

**Comment by NTaylorMullen** [comment]
> Have had problem with intellisense not working in razor components (without code behind). No problem with intellisense in components with code behind. Did not know I had the experimental Razor editor activated. Deactivated it and intellisense is back in the non code behind components. Got curious and activated it again (restarted VS) aand intellisense is gone. Did this 3 times with the same result. I'm just so glad right now... Thank you @NTaylorMullen for recommending looking in to the exp. Razor editor. I know your advice was the opposite but it helped me so thank you!

@markarlsson365 given that's the case, we'd love to dig into more as to why your IntelliSense was not working! Would you mind using VS' "Report a problem" button in the top right to allow us to investigate further?

**Comment by talldaniel** [comment]
@NTaylorMullen 
using version 16.10.0 preview 1.0  There appears to be a timeout after a person types an "at" character (shift 2) where if you wait long enough it will turn into a reported bug, that is related to the bug where lots of fake bugs and squiggles are reported.
I would try to repeat it, but I would have to first go to a good state again.

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen
> using version 16.10.0 preview 1.0 There appears to be a timeout after a person types an "at" character (shift 2) where if you wait long enough it will turn into a reported bug, that is related to the bug where lots of fake bugs and squiggles are reported.
> I would try to repeat it, but I would have to first go to a good state again.

I'd be super curious as to the type of project, also, in 16.10-Preview2 the experimental editor got masssssive perf gains. Now that being said, it came with some hiccups (closing and reopening a sln will result in no IntelliSense) that will be fixed in 16.10-P3.

**Comment by ChrisASearles** [comment]
I can confirm that Intellisense in Blazor is brutal and causes more problems than it solves at the moment. I tried enabling the experimental editor and it broke my build reporting phantom errors and simply didn't work at all. Switching back and restarting multiple times got me back to where I was but the smallest syntax error in HTML markup causes so many issues it becomes hard to work and makes it extremely difficult to track down where the extra set of quotes are (that were added automatically by Intellisense). Local variables often don't show up and with a small error somewhere else on the page are continuously overwritten with class names. I really like the architecture but the dev experience is leaving a bad taste and makes it feel like the production release was hugely rushed. The issues are so prevalent I can't believe they weren't known beforehand.

**Comment by maxgsamson** [comment]
> I can confirm that Intellisense in Blazor is brutal and causes more problems than it solves at the moment. I tried enabling the experimental editor and it broke my build reporting phantom errors and simply didn't work at all. Switching back and restarting multiple times got me back to where I was but the smallest syntax error in HTML markup causes so many issues it becomes hard to work and makes it extremely difficult to track down where the extra set of quotes are (that were added automatically by Intellisense). Local variables often don't show up and with a small error somewhere else on the page are continuously overwritten with class names. I really like the architecture but the dev experience is leaving a bad taste and makes it feel like the production release was hugely rushed. The issues are so prevalent I can't believe they weren't known beforehand.

separating razor and cs partial class helps a bit but to say production was rush not sure... its just editor side when you know the issues you can easily work with it its just annoying.

**Comment by talldaniel** [comment]
@NTaylorMullen 
"I'd be super curious as to the type of project, also, in 16.10-Preview2 the experimental editor got masssssive perf gains. Now"

It is a Blazor project.  Since noticing this bug I noticed a couple of others that are similar.  Did someone home roll the thread manager for this project?

**Comment by mayur-ekbote** [comment]
> I can confirm that Intellisense in Blazor is brutal and causes more problems than it solves at the moment. I tried enabling the experimental editor and it broke my build reporting phantom errors and simply didn't work at all. Switching back and restarting multiple times got me back to where I was but the smallest syntax error in HTML markup causes so many issues it becomes hard to work and makes it extremely difficult to track down where the extra set of quotes are (that were added automatically by Intellisense). Local variables often don't show up and with a small error somewhere else on the page are continuously overwritten with class names. I really like the architecture but the dev experience is leaving a bad taste and makes it feel like the production release was hugely rushed. The issues are so prevalent I can't believe they weren't known beforehand.

Switch to VS 2022. While it has its share of problems, it is much more stable than the VS 2019 version.

**Comment by ramious76** [comment]
Is there a way we can still have it debug with the errors?  I have false positives on intellisense but its blocking builds for the reasons of the false positives and that's the most frustrating part of it.

**Comment by ramious76** [comment]
It would be nice if the build would still work if intellisense was giving a false positive.  I have an async Task function with an await navigation inside and I am stuck with an error of I can't await a void with it pointed at this function.  I can't even build or debug because of this exact false positive.

**Comment by ldsenow** [comment]
I am using VS 2022 preview 17. The intellisense issue really causes more problems than it solves. Previously, I can clear the errors by remving .vs folder, now I cant see this folder anymore but the errors stay. Simply i change the property type, the errors occur. 
Not sure how to fix this, seeing red underline all the time. I rather turn it off completely. Hope this issue can be fixed asap.
