### ISSUE TITLE
.Net 5 Blazor Wasm not available

### ISSUE THREAD

**Issue by JulienM28** [dotnet/aspnetcore#20007]
I took a look to .Net 5 today and Blazor WASM project is not available, only server is.

Is it normal or is the some stuff to make it working ?

Thanks.

**Comment by danroth27** [comment]
Hi @JulienM28. We haven't included Blazor WebAssembly in .NET 5 just yet because we're focused on Blazor WebAssembly 3.2 release which is scheduled for May of this year. Blazor WebAssembly 3.2 is based on .NET Core 3.1 and will soon be included in the .NET Core 3.1 SDK. After the May release we'll integrate Blazor WebAssembly with .NET 5.

You can still install the Blazor WebAssembly template and use it with the .NET 5 SDK, but the project template will still only show up as a .NET Core 3.1 base project.

![image](https://user-images.githubusercontent.com/1874516/77103869-55b50300-69d8-11ea-9c7e-e0746ce8114b.png)

I hope this helps!

**Comment by uzabumuhire** [comment]
Hello,

I am using Visual Studio 2019  16.6.0 Preview 1 on Windows 10 and I have installed .NET 5.0 preview 1 and then ran dotnet new -i Microsoft.AspNetCore.Components.WebAssembly.Templates::3.2.0-preview2.20160.5, and restarted VS, but still don’t have the WebAssembly template.

Here are the print screens  

![creating-new-blazor-app-project-net-core-3-1-2020-03-24-045253](https://user-images.githubusercontent.com/3822499/77387123-ce2b1380-6d8c-11ea-9ad0-59cb10983906.png)

![creating-new-blazor-app-project-net-core-5-0-2020-03-24-045253](https://user-images.githubusercontent.com/3822499/77387158-e7cc5b00-6d8c-11ea-8fb6-15f9426560d0.png)

**Comment by danroth27** [comment]
@uzabumuhire To check that everything is correctly installed, could you please provide the output of the following two commands?:

- `dotnet --info`
- `dotnet new -u`

**Comment by uzabumuhire** [comment]
@danroth27 thanks for your quick reply here are the content of dotnet --info
 
PS C:\Program Files\PowerShell\7> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   5.0.100-preview.1.20155.7
 Commit:    1c44853056

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.1.20155.7\

Host (useful for support):
  Version: 5.0.0-preview.1.20120.5
  Commit:  3c523a6a7a

.NET Core SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.200 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.1.20155.7 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.1.20124.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.1.20120.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.1.20127.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
PS C:\Program Files\PowerShell\7>

**Comment by uzabumuhire** [comment]
Here is the content of dotnet new -u

PS C:\Program Files\PowerShell\7> dotnet new -u
Template Instantiation Commands for .NET Core CLI

Currently installed items:
  Microsoft.DotNet.Common.ProjectTemplates.3.1
    Details:
      NuGetPackageId: Microsoft.DotNet.Common.ProjectTemplates.3.1
      Version: 3.1.2
      Author: Microsoft
    Templates:
      Class library (classlib) C#
      Class library (classlib) F#
      Class library (classlib) VB
      Console Application (console) C#
      Console Application (console) F#
      Console Application (console) VB
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Common.ProjectTemplates.3.1

  Microsoft.DotNet.Common.ProjectTemplates.2.1
    Details:
      NuGetPackageId: Microsoft.DotNet.Common.ProjectTemplates.2.1
      Version: 1.0.2-beta3
      Author: Microsoft
    Templates:
      Class library (classlib) C#
      Class library (classlib) F#
      Class library (classlib) VB
      Console Application (console) C#
      Console Application (console) F#
      Console Application (console) VB
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Common.ProjectTemplates.2.1

  Microsoft.DotNet.Test.ProjectTemplates.2.1
    Details:
      NuGetPackageId: Microsoft.DotNet.Test.ProjectTemplates.2.1
      Version: 1.0.2-beta4.20105.2
      Author: Microsoft
    Templates:
      Unit Test Project (mstest) C#
      Unit Test Project (mstest) F#
      Unit Test Project (mstest) VB
      xUnit Test Project (xunit) C#
      xUnit Test Project (xunit) F#
      xUnit Test Project (xunit) VB
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Test.ProjectTemplates.2.1

  Microsoft.DotNet.Web.ProjectTemplates.3.1
    Details:
      NuGetPackageId: Microsoft.DotNet.Web.ProjectTemplates.3.1
      Version: 3.1.2
      Author: Microsoft
    Templates:
      Blazor Server App (blazorserver) C#
      ASP.NET Core Empty (web) C#
      ASP.NET Core Empty (web) F#
      ASP.NET Core gRPC Service (grpc) C#
      Razor Class Library (razorclasslib) C#
      ASP.NET Core Web App (webapp) C#
      ASP.NET Core Web App (Model-View-Controller) (mvc) C#
      ASP.NET Core Web App (Model-View-Controller) (mvc) F#
      ASP.NET Core Web API (webapi) C#
      ASP.NET Core Web API (webapi) F#
      Worker Service (worker) C#
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Web.ProjectTemplates.3.1

  Microsoft.DotNet.Web.ProjectTemplates.2.1
    Details:
      NuGetPackageId: Microsoft.DotNet.Web.ProjectTemplates.2.1
      Version: 2.1.14
      Author: Microsoft
    Templates:
      ASP.NET Core Empty (web) C#
      ASP.NET Core Empty (web) F#
      Razor Class Library (razorclasslib) C#
      ASP.NET Core Web App (razor) C#
      ASP.NET Core Web App (Model-View-Controller) (mvc) C#
      ASP.NET Core Web App (Model-View-Controller) (mvc) F#
      ASP.NET Core Web API (webapi) C#
      ASP.NET Core Web API (webapi) F#
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Web.ProjectTemplates.2.1

  Microsoft.DotNet.Web.Spa.ProjectTemplates.2.1
    Details:
      NuGetPackageId: Microsoft.DotNet.Web.Spa.ProjectTemplates.2.1
      Version: 2.1.14
      Author: Microsoft
    Templates:
      ASP.NET Core with Angular (angular) C#
      ASP.NET Core with React.js (react) C#
      ASP.NET Core with React.js and Redux (reactredux) C#
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Web.Spa.ProjectTemplates.2.1

  Microsoft.DotNet.Common.ItemTemplates
    Details:
      NuGetPackageId: Microsoft.DotNet.Common.ItemTemplates
      Version: 5.0.0-preview.1.20124.3
      Author: Microsoft
    Templates:
      dotnet gitignore file (gitignore)
      global.json file (globaljson)
      NuGet Config (nugetconfig)
      Solution File (sln)
      Dotnet local tool manifest file (tool-manifest)
      Web Config (webconfig)
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Common.ItemTemplates

  Microsoft.DotNet.Common.ProjectTemplates.5.0
    Details:
      NuGetPackageId: Microsoft.DotNet.Common.ProjectTemplates.5.0
      Version: 5.0.0-preview.1.20124.3
      Author: Microsoft
    Templates:
      Class library (classlib) C#
      Class library (classlib) F#
      Class library (classlib) VB
      Console Application (console) C#
      Console Application (console) F#
      Console Application (console) VB
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Common.ProjectTemplates.5.0

  Microsoft.DotNet.Test.ProjectTemplates.3.1
    Details:
      NuGetPackageId: Microsoft.DotNet.Test.ProjectTemplates.3.1
      Version: 1.0.2-beta4.20079.1
      Author: Microsoft
    Templates:
      Unit Test Project (mstest) C#
      Unit Test Project (mstest) F#
      Unit Test Project (mstest) VB
      xUnit Test Project (xunit) C#
      xUnit Test Project (xunit) F#
      xUnit Test Project (xunit) VB
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Test.ProjectTemplates.3.1

  Microsoft.DotNet.Web.ProjectTemplates.5.0
    Details:
      NuGetPackageId: Microsoft.DotNet.Web.ProjectTemplates.5.0
      Version: 5.0.0-preview.1.20124.5
      Author: Microsoft
    Templates:
      Blazor Server App (blazorserver) C#
      ASP.NET Core Empty (web) C#
      ASP.NET Core Empty (web) F#
      ASP.NET Core gRPC Service (grpc) C#
      Razor Class Library (razorclasslib) C#
      ASP.NET Core Web App (webapp) C#
      ASP.NET Core Web App (Model-View-Controller) (mvc) C#
      ASP.NET Core Web App (Model-View-Controller) (mvc) F#
      ASP.NET Core Web API (webapi) C#
      ASP.NET Core Web API (webapi) F#
      Worker Service (worker) C#
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Web.ProjectTemplates.5.0

  Microsoft.DotNet.Web.Spa.ProjectTemplates.3.1
    Details:
      NuGetPackageId: Microsoft.DotNet.Web.Spa.ProjectTemplates.3.1
      Version: 3.1.2
      Author: Microsoft
    Templates:
      ASP.NET Core with Angular (angular) C#
      ASP.NET Core with React.js (react) C#
      ASP.NET Core with React.js and Redux (reactredux) C#
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Web.Spa.ProjectTemplates.3.1

  Microsoft.DotNet.Wpf.ProjectTemplates
    Details:
      NuGetPackageId: Microsoft.DotNet.Wpf.ProjectTemplates
      Version: 5.0.0-preview.1.20127.4
      Author: Microsoft
    Templates:
      WPF Application (wpf) C#
      WPF Application (wpf) VB
      WPF Class library (wpflib) C#
      WPF Class library (wpflib) VB
      WPF Custom Control Library (wpfcustomcontrollib) C#
      WPF Custom Control Library (wpfcustomcontrollib) VB
      WPF User Control Library (wpfusercontrollib) C#
      WPF User Control Library (wpfusercontrollib) VB
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Wpf.ProjectTemplates

  NUnit3.DotNetNew.Template
    Details:
      NuGetPackageId: NUnit3.DotNetNew.Template
      Version: 1.7.1
      Author: akharlov
    Templates:
      NUnit 3 Test Project (nunit) C#
      NUnit 3 Test Item (nunit-test) C#
      NUnit 3 Test Project (nunit) F#
      NUnit 3 Test Item (nunit-test) F#
      NUnit 3 Test Project (nunit) VB
      NUnit 3 Test Item (nunit-test) VB
    Uninstall Command:
      dotnet new -u NUnit3.DotNetNew.Template

  Microsoft.DotNet.Test.ProjectTemplates.5.0
    Details:
      NuGetPackageId: Microsoft.DotNet.Test.ProjectTemplates.5.0
      Version: 1.0.2-beta4.20126.1
      Author: Microsoft
    Templates:
      Unit Test Project (mstest) C#
      Unit Test Project (mstest) F#
      Unit Test Project (mstest) VB
      xUnit Test Project (xunit) C#
      xUnit Test Project (xunit) F#
      xUnit Test Project (xunit) VB
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Test.ProjectTemplates.5.0

  Microsoft.DotNet.Web.ItemTemplates
    Details:
      NuGetPackageId: Microsoft.DotNet.Web.ItemTemplates
      Version: 5.0.0-preview.1.20124.5
      Author: Microsoft
    Templates:
      Protocol Buffer File (proto)
      Razor Component (razorcomponent) C#
      Razor Page (page) C#
      MVC ViewImports (viewimports) C#
      MVC ViewStart (viewstart) C#
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Web.ItemTemplates

  Microsoft.DotNet.Web.Spa.ProjectTemplates.5.0
    Details:
      NuGetPackageId: Microsoft.DotNet.Web.Spa.ProjectTemplates.5.0
      Version: 5.0.0-preview.1.20124.5
      Author: Microsoft
    Templates:
      ASP.NET Core with Angular (angular) C#
      ASP.NET Core with React.js (react) C#
      ASP.NET Core with React.js and Redux (reactredux) C#
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Web.Spa.ProjectTemplates.5.0

  Microsoft.Dotnet.WinForms.ProjectTemplates
    Details:
      NuGetPackageId: Microsoft.Dotnet.WinForms.ProjectTemplates
      Version: 5.0.0-preview.1.20120.6
      Author: Microsoft
    Templates:
      Windows Forms (WinForms) Application (winforms) C#
      Windows Forms (WinForms) Application (winforms) VB
      Windows Forms (WinForms) Class library (winformslib) C#
      Windows Forms (WinForms) Class library (winformslib) VB
    Uninstall Command:
      dotnet new -u Microsoft.Dotnet.WinForms.ProjectTemplates

  Microsoft.AspNetCore.Components.WebAssembly.Templates
    Details:
      NuGetPackageId: Microsoft.AspNetCore.Components.WebAssembly.Templates
      Version: 3.2.0-preview2.20160.5
      Author: Microsoft
    Templates:
      Blazor WebAssembly App (blazorwasm) C#
    Uninstall Command:
      dotnet new -u Microsoft.AspNetCore.Components.WebAssembly.Templates

PS C:\Program Files\PowerShell\7>

**Comment by danroth27** [comment]
Thanks @uzabumuhire! It looks like everything is installed correctly, so there must be some other issue here that is preventing the Blazor WebAssembly template from showing up. @phenning Any ideas?

To try to workaround this issue, could you please try clearing out the VS template hive and then restarting VS? VS will then recreate the hive. To clear out the hive, delete the contents of the *C:\Users\[user]\.templateengine\vs* folder.

**Comment by uzabumuhire** [comment]
I have just cleared out the VS template hive and restarted VS but I still don't have the Blazor WebAssembly template.

**Comment by phenning** [comment]
We had a bug in Visual Studio 2019 Preview 1 where the Visual Studio hive would not sync up with the 5.0 CLI Hive. This has been fixed in Preview 2

In preview 1, you can work around the bug by forcing the template to be installed to highest non 5.0 CLI installed.

From a command prompt, create a temporary folder, then run:
`dotnet new globaljson`
Then
`'dotnet --list-sdks`

Take the highest non 5.0 version listed there and substitute it for the value in the created global.json.

Now rerun the dotnet new -i command to install the template package and restart Visual Studio.

**Comment by danroth27** [comment]
Thanks @phenning! Since this has been addressed for the upcoming 16.6 Preview 2 release, I'm going to go ahead and close this issue.

**Comment by uzabumuhire** [comment]
Thanks @phenning. I have followed the procedure but I still don't have WebAssembly template.

**Comment by uzabumuhire** [comment]
I will wait  for the  16.6 Preview 2 to try to migrate my WebAssembly projects to .NET  5.0
