### ISSUE TITLE
Http.DefaultHttpClientFactory could not be located: Blazor WebAssembly 3.2.0 Preview 5 

### ISSUE THREAD

**Issue by Discovery-support** [dotnet/aspnetcore#21356]
Blazor WebAssembly: Client

As per Preview 5 Asp.Net blog I changed the file: **Program.cs**
    from:
`    builder.Services.AddSingleton(new HttpClient { BaseAddress = new Uri(baseAddress) });`

to the new code:
 `
builder.Services.AddHttpClient("TaskTrackIT.ServerAPI",
    client => client.BaseAddress = new Uri(baseAddress))
    .AddHttpMessageHandler<BaseAddressAuthorizationMessageHandler>();`
`    builder.Services.AddTransient(
    sp => sp.GetRequiredService<IHttpClientFactory>().CreateClient("TaskTrackIT.ServerAPI"));`

If I run this in `debug` or `release`
[BlazorError.txt](https://github.com/dotnet/aspnetcore/files/4557775/BlazorError.txt)
 mode on my local machine then **all works fine**.  Publishing to a **WinHost server** results in the following **client side error**.  

`Unhandled exception rendering component: A suitable constructor for type 'Microsoft.Extensions.Http.DefaultHttpClientFactory' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.`

All worked fine on the WInHost server before I made the above change, any ideas? Full exception Stack Trace attached.  The WinHost site has a valid SSL Certificate.

Thank you.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by Discovery-support** [comment]
@mkArtakMSFT  Issue solved by upgrading from `3.2.0 Preview 5` to  `3.2.0 RC`

**Comment by MichaOnGit** [comment]
I have exactly the same problem, but I have already updated my project to 3.2.0 rc1 and I still get the error described above.
Also with me it runs without problems on the local machine, only the hosting causes the error
