### ISSUE TITLE
Visual Studio 2019 attach to Blazor WebAssembly App browser - A debugger operation is taking a long time

### ISSUE THREAD

**Issue by AlexeyBoiko** [dotnet/aspnetcore#21790]
### Problem
Attach to Chrome/MS Edge (Chromium) from Visual Studio 2019 Preview prompt a popup with message:
"A debugger operation is taking a long time to complete. Click "Cancel" to stop waiting and terminate the process."

### To Reproduce
0. Create Blazor WebAssembly App project with "ASP.Net core hosted" option from template.
1. In launchSettings.json of server project set "launchBrowser": false
```
{
    "iisSettings": {
      "windowsAuthentication": false,
      "anonymousAuthentication": true,
      "iisExpress": {
        "applicationUrl": "http://localhost:55119",
        "sslPort": 44321
      }
    },
    "profiles": {
      "IIS Express": {
        "commandName": "IISExpress",
===>        "launchBrowser": false,
        "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",
        "environmentVariables": {
          "ASPNETCORE_ENVIRONMENT": "Development"
        }
      },
      "Reservation365AdminWeb.Server": {
        "commandName": "Project",
===>        "launchBrowser": false,
        "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",
        "applicationUrl": "https://localhost:5001;http://localhost:5000",
        "environmentVariables": {
          "ASPNETCORE_ENVIRONMENT": "Development"
        }
      }
    }
  }
```
2.  Set break point in Counter.razor in IncrementCount()
```
@code {
    private int currentCount = 6;

    private void IncrementCount()
    {
===>        currentCount++;
    }
}
```
Launch project
3. Launch msedge with debugging settings
`msedge --remote-debugging-port=9222 --user-data-dir="C:\Users\A1\AppData\Local\Temp\blazor-edge-debug" --no-first-run https://localhost:44321/`
3. In VS attach to msedge process
4. In browser press Ctrl+Alt+D
5. In browser click on "Click me button" on "Counter" page
6. VS window will get focus and error popup appear.

### Further technical details
- Visual Studio 2019 Preview Version 16.6.0 Preview 6.0

**Comment by Sm1le291** [comment]
Hi! Just install the last VS Preview which allows you to debug your app without typing any commands

**Comment by AlexeyBoiko** [comment]
> Hi! Just install the last VS Preview which allows you to debug your app without typing any commands.
> Oh, you already on the last preview. Why are you using it? It must just works
> I think problem with you PC, WebBlazor develop needs fast PC. Sometimes I can't enter into breakpoints after few hours of developing, restart pc helps me

Debug work without
`"launchBrowser": false`
Every time when you press F5 new browser window will be open. In my case I can't use this behavior.

**Comment by mkArtakMSFT** [comment]
@digeff I know you've been looking into this. Any updates?

**Comment by mkArtakMSFT** [comment]
This is being tracked at: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1125902

**Comment by AlexeyBoiko** [comment]
@mkArtakMSFT link did not work. You close ticket - please let me know what does it mean? Where I can track status or what I have to do to fix problem?

**Comment by mkArtakMSFT** [comment]
Thanks for bringing this up, @AlexeyBoiko.
The issue is internal and is not owned by our team. The plan is to get this resolved by VS 16.7 release.

**Comment by AlexeyBoiko** [comment]
@mkArtakMSFT , just update Visual Studio to Version 16.7.0 Preview 1.0.
Debugger still don't work.

Exact behavior:
1. Launch Blazor project
2. Launch msedge with debugging settings
msedge --remote-debugging-port=9222 --user-data-dir="C:\Users\A1\AppData\Local\Temp\blazor-edge-debug" --no-first-run https://localhost:44321/
3. In VS attach to msedge process
4. In browser click on "Click me" button on "Counter" page
-> nothing happens
5. In browser press F12
-> VS window get focus. There are error message "Source Not Available"

![image](https://user-images.githubusercontent.com/29090032/82525322-bf1cd380-9b39-11ea-846d-78d8d797d721.png)

**Comment by digeff** [comment]
@AlexeyBoiko We haven't had a chance to fix the issue yet. We are planning on doing it during version 16.7. I'll let you know when the fix is available for you to test.
