### ISSUE TITLE
Quarantined test ThrowingSynchronousConnectionMiddlewareDoesNotCrashServer 

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#24758]
```C#
Assert.Throws() Failure
Expected: typeof(System.IO.IOException)
Actual:   typeof(System.Net.NetworkException): The connection was aborted by the local host.
---- System.Net.NetworkException : The connection was aborted by the local host.
-------- System.Net.Sockets.SocketException : An established connection was aborted by the software in your host machine.
```

```
at System.IO.StreamWriter.FlushAsyncInternal(StreamWriter _this, Boolean flushStream, Boolean flushEncoder, Char[] charBuffer, Int32 charPos, Boolean haveWrittenPreamble, Encoding encoding, Encoder encoder, Byte[] byteBuffer, Stream stream, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Testing.StreamBackedTestConnection.Send(String[] lines) in /_/src/Servers/Kestrel/shared/test/StreamBackedTestConnection.cs:line 85
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ConnectionMiddlewareTests.<>c__DisplayClass0_0.<<ThrowingSynchronousConnectionMiddlewareDoesNotCrashServer>b__2>d.MoveNext() in /_/src/Servers/Kestrel/test/FunctionalTests/ConnectionMiddlewareTests.cs:line 39
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.IO.StreamWriter.FlushAsyncInternal(StreamWriter _this, Boolean flushStream, Boolean flushEncoder, Char[] charBuffer, Int32 charPos, Boolean haveWrittenPreamble, Encoding encoding, Encoder encoder, Byte[] byteBuffer, Stream stream, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Testing.StreamBackedTestConnection.Send(String[] lines) in /_/src/Servers/Kestrel/shared/test/StreamBackedTestConnection.cs:line 85
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ConnectionMiddlewareTests.<>c__DisplayClass0_0.<<ThrowingSynchronousConnectionMiddlewareDoesNotCrashServer>b__2>d.MoveNext() in /_/src/Servers/Kestrel/test/FunctionalTests/ConnectionMiddlewareTests.cs:line 39
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendAsyncForNetworkStream(Socket socket, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.SendAsyncForNetworkStream(ReadOnlyMemory`1 buffer, SocketFlags socketFlags, CancellationToken cancellationToken)
   at System.Net.Sockets.NetworkStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.IO.StreamWriter.FlushAsyncInternal(StreamWriter _this, Boolean flushStream, Boolean flushEncoder, Char[] charBuffer, Int32 charPos, Boolean haveWrittenPreamble, Encoding encoding, Encoder encoder, Byte[] byteBuffer, Stream stream, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.IO.StreamWriter.FlushAsyncInternal(StreamWriter _this, Boolean flushStream, Boolean flushEncoder, Char[] charBuffer, Int32 charPos, Boolean haveWrittenPreamble, Encoding encoding, Encoder encoder, Byte[] byteBuffer, Stream stream, CancellationToken cancellationToken)
   at System.IO.StreamWriter.FlushAsyncInternal(Boolean flushStream, Boolean flushEncoder, Char[] sCharBuffer, Int32 sCharPos, CancellationToken cancellationToken)
   at System.IO.StreamWriter.FlushAsync()
   at Microsoft.AspNetCore.Testing.StreamBackedTestConnection.Send(String[] lines) in /_/src/Servers/Kestrel/shared/test/StreamBackedTestConnection.cs:line 85
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Testing.StreamBackedTestConnection.Send(String[] lines)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ConnectionMiddlewareTests.<>c__DisplayClass0_0.<<ThrowingSynchronousConnectionMiddlewareDoesNotCrashServer>b__2>d.MoveNext() in /_/src/Servers/Kestrel/test/FunctionalTests/ConnectionMiddlewareTests.cs:line 39
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.Asyn
```

**Comment by pranavkm** [comment]
FYI @halter73. This one looks a a straight up failure given that it failed on all 3 platforms

**Comment by pranavkm** [comment]
This was a runtime change that was resolved as part of #24757

**Comment by ryanbrandenburg** [comment]
@pranavkm it looks like this is still happening, what specifically about the PR you link was supposed to have fixed it?

**Comment by pranavkm** [comment]
@ryanbrandenburg these changes: https://github.com/dotnet/aspnetcore/pull/24757/files#diff-2524881202d6d65eedbddb9171f29556R323, https://github.com/dotnet/aspnetcore/pull/24757/files#diff-70660aa1127d7163dfa8a77c8ab7fcbeR30

**Comment by BrennanConroy** [comment]
This doesn't seem to be an issue anymore.
