### ISSUE TITLE
Blazor WASM .NET 5 RC1 and Azure Cosmos DB - System.PlatformNotSupportedException: Operation is not supported on this platform.

### ISSUE THREAD

**Issue by ylr-research** [dotnet/aspnetcore#26043]
**Summary**
I have a bare bones Blazor WASM (standalone) application reading a container from Azure Cosmos DB. Before upgrading to .NET 5 RC1 it was working fine. Now I'm seeing the following output in the Developer Console.

![image](https://user-images.githubusercontent.com/63487874/93546233-69fa9e00-f930-11ea-8a3e-93639b6a8fd9.png)

**Line failing**
``` C#
using (var cosmosClient = new CosmosClient(endpoint, authKey, cosmosClientOptions))
{
}
```
**CosmosClientOptions**
```C#
var cosmosClientOptions = new CosmosClientOptions
{
     ConnectionMode = ConnectionMode.Gateway
};
```
**Cosmos Package Reference**
`<PackageReference Include="Microsoft.Azure.Cosmos" Version="3.13.0-preview" />`

**Comment by campersau** [comment]
Similar to https://github.com/dotnet/runtime/issues/42405 the `Microsoft.Azure.Cosmos` library would need to be updated to account for these `PlatformNotSupportedExcention`s.

**Comment by campersau** [comment]
In your case it might work if you provide your own `HttpClientHandler` via 
```c#
var cosmosClientOptions = new CosmosClientOptions
{
    ConnectionMode = ConnectionMode.Gateway,
    HttpClientFactory = () => new HttpClientHandler()
};
```
Because the default one sets the proxy property:
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/8c31ca03d52d8550a103155a6ed4966a9eb51980/Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs#L99-L107

**Comment by lewing** [comment]
fixed by https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1863

**Comment by ylr-research** [comment]
this is still a problem [Azure/azure-cosmos-dotnet-v3#1865](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1865)

**Comment by ealsur** [comment]
@ylr-research That is not the same issue, the new issue you are facing is .NET 5 not supporting SHA functions currently in RC1.
