### ISSUE TITLE
Blazor RC1 Virtualize Component paging issue

### ISSUE THREAD

**Issue by Jarek300** [dotnet/aspnetcore#26353]
Virtualize component seems not to support clicking in “page down” area of the scroll bar. 

If you drag a handle, component correctly loads items. 

If you click in the scrollbar below the handle, component automatically scrolls the list from the current position till the end. Sometimes it’s enough to click once, sometimes you have to click ‘page down’ a few times.

I’ve attached a simple test project based on blazor project template:

[WebApplication1.zip](https://github.com/dotnet/aspnetcore/files/5287079/WebApplication1.zip)

**Comment by captainsafia** [comment]
> If you click in the scrollbar below the handle, component automatically scrolls the list from the current position till the end.

This is an issue in RC1 that was resolved in RC2. Can you try RC2 and verify if the same behavior persists? You can check out the nightly builds of RC2 at https://github.com/dotnet/installer#installers-and-binaries.

**Comment by Jarek300** [comment]
Paging still does not work in RC2. See the attached recording. Use the test project above to reproduce the problem.

[WebApplication1.zip](https://github.com/dotnet/aspnetcore/files/5379162/WebApplication1.zip)
