### ISSUE TITLE
Blazor WASM: StaticWebAssetBasePath breaks published app

### ISSUE THREAD

**Issue by ejhg** [dotnet/aspnetcore#29185]
### Describe the bug
When StaticWebAssetBasePath is specified in the project file, the published Blazor WASM app does not work.  At least one reason for this is that the `blazor.boot.json` file that is produced is uninitialized.  In other words, StaticWebAssetBasePath breaks blazor.boot.json and consequently the rest of the static Blazor app.

### To Reproduce

Create a new WASM sample project (This bug affects any WASM project)
```
dotnet new blazorwasm -o blazor-web
```

Manually edit the csproj file and add the following in the first <PropertyGroup/>
```
<StaticWebAssetBasePath>app1</StaticWebAssetBasePath>
```

Run a publish release build
```
dotnet publish -c Release
```

Observe that the `blazor.boot.json` file contains uninitialize properties.  (eg, the list of assemblies is missing). This would not have happened if the <StaticWebAssetBasePath/> property had not been added to the csproj file.
```
# bin/Release/net5.0/publish/wwwroot/app1_framework/blazor.boot.json
{
  "cacheBootResources": true,
  "config": [ ],
  "debugBuild": false,
  "entryAssembly": "blazor-web",
  "icuDataMode": 0,
  "linkerEnabled": true,
  "resources": {
    "assembly": { },
    "lazyAssembly": null,
    "pdb": null,
    "runtime": { },
    "satelliteResources": null
  }
}
```

### Further technical details
- ASP.NET Core version: 5.01
- Include the output of `dotnet --info`

```
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.101/

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  3.1.101 [/usr/local/share/dotnet/sdk]
  3.1.102 [/usr/local/share/dotnet/sdk]
  3.1.200 [/usr/local/share/dotnet/sdk]
  3.1.300 [/usr/local/share/dotnet/sdk]
  3.1.301 [/usr/local/share/dotnet/sdk]
  3.1.402 [/usr/local/share/dotnet/sdk]
  3.1.403 [/usr/local/share/dotnet/sdk]
  3.1.404 [/usr/local/share/dotnet/sdk]
  5.0.100 [/usr/local/share/dotnet/sdk]
  5.0.101 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.18 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.22 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version:  macOS 10.15.6 on command line zsh

**Comment by pranavkm** [comment]
Likely a dupe of https://github.com/dotnet/aspnetcore/issues/27776 that should be resolved in the upcoming 5.0.2 release. The issue has some possible workarounds listed

**Comment by BrentCarter** [comment]
Is it possible you have an ETA on that 5.0.2 release?  It looks like the last couple releases were on Nov 10 and Dec 8...  any chance that "second Tuesday of the month" trend continues and we see it on the 12th or thereabouts?

**Comment by fuzl-llc** [comment]
I've updated to the new 5.0.2 release and still see this issue. Publishing with a default Blazor WASM app results in a blazor.boot.json file with 34 items in the assembly list and 7 items in the runtime list. After adding the StaticWebAssetBasePath element, both assembly and runtime lists are empty. In addition to #27776, I suspect this is related to #29179 where there are additional details specific to that issue but I'm guessing these are all due to the same underlying issue.

**Comment by javiercn** [comment]
We believe that this has been fixed in the latest version of the SDK. Let us know if you still have issues after upgrading to 5.0.103
