### ISSUE TITLE
MatBlazor Button breaks Hot reload in Dotnet 6 preview 3.

### ISSUE THREAD

**Issue by vallgrenerik** [dotnet/aspnetcore#31668]
### Describe the bug
Hello! 
First: Thanks for fantastic work with Hot reload. It looks promising! 
But unfortunately a MatBlazor (https://www.matblazor.com/) button "MatButton" makes the hot reload crash.

### To Reproduce
I've created a repo https://github.com/vallgrenerik/HotReloadTest 
(A simple Blazor WASM ASP.Core Hosted)
Look inside the Index.razor in the .Client project. 

Uncomment the button to make it crash.
Comment out the MatButton, press CTRL + R in terminal to force reload and the Hot reload works again.

### Exceptions (if any)
The crash appears in the browser console like this: 
```
* Assertion at /__w/1/s/src/mono/mono/metadata/metadata-update.c:809, 
condition `<disabled>' not met
```
Full crash: 
```
dotnet.6.0.0-preview.3.21201.4.js:1 * Assertion at /__w/1/s/src/mono/mono/metadata/metadata-update.c:809, condition `<disabled>' not met

542288 @ dotnet.6.0.0-preview.3.21201.4.js:1
_emscripten_asm_const_int @ dotnet.6.0.0-preview.3.21201.4.js:1
(anonymous) @ 008ace4e:0xdec8e
(anonymous) @ 008ace4e:0x19281b
(anonymous) @ 008ace4e:0x107942
(anonymous) @ 008ace4e:0x8b218
(anonymous) @ 008ace4e:0xf002
(anonymous) @ 008ace4e:0x7c6f
(anonymous) @ 008ace4e:0x56f3
(anonymous) @ 008ace4e:0x1a180a
(anonymous) @ 008ace4e:0x11988d
(anonymous) @ 008ace4e:0xee6f7
(anonymous) @ 008ace4e:0xdf021
(anonymous) @ 008ace4e:0xe1e41
(anonymous) @ 008ace4e:0x46356
(anonymous) @ 008ace4e:0x12dfac
(anonymous) @ 008ace4e:0x117c6e
(anonymous) @ 008ace4e:0x7a160
(anonymous) @ 008ace4e:0xfcc5
(anonymous) @ 008ace4e:0x10dc13
(anonymous) @ 008ace4e:0xee3e6
(anonymous) @ 008ace4e:0xedf47
(anonymous) @ 008ace4e:0x194d3b
(anonymous) @ 008ace4e:0x59c7c
(anonymous) @ 008ace4e:0x46258
(anonymous) @ 008ace4e:0x12dfac
(anonymous) @ 008ace4e:0x117c6e
(anonymous) @ 008ace4e:0x7a160
(anonymous) @ 008ace4e:0x152f4
(anonymous) @ 008ace4e:0x10e00d
fb @ 008ace4e:0x108652
Module._mono_wasm_invoke_method @ dotnet.6.0.0-preview.3.21201.4.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_InvokeDotNet @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_InvokeDotNet:19
invokeDotNetFromJS @ blazor.webassembly.js:1
m @ blazor.webassembly.js:1
e.invokeMethod @ blazor.webassembly.js:1
he._internal.applyHotReload @ blazor.webassembly.js:1
(anonymous) @ aspnetcore-browser-refresh.js:101
applyBlazorDeltas @ aspnetcore-browser-refresh.js:101
BlazorHotReloadDeltav1 @ aspnetcore-browser-refresh.js:31
connection.onmessage @ aspnetcore-browser-refresh.js:37
Show 11 more frames
```

### Further technical details
- ASP.NET Core version 6.0.0-preview.3.21201.13
- Include the output of dotnet --info
```
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.3.21202.5
 Commit:    aee38a6dd4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.3.21202.5\

Host (useful for support):
  Version: 6.0.0-preview.3.21201.4
  Commit:  236cb21e3c

.NET SDKs installed:
  3.1.407 [C:\Program Files\dotnet\sdk]
  5.0.200-preview.20614.14 [C:\Program Files\dotnet\sdk]
  5.0.200-preview.21077.7 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.3.21202.5 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.3.21201.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.3.21201.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.3.21201.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- Microsoft Visual Studio Professional 2019 Preview
Version 16.10.0 Preview 1.0

**Comment by MRakesh** [comment]
It is not worked for me also and  checked my network it is missing downloading of 127.0.0.1 websocket, connection.
Fixed after adding <script src="/_framework/aspnetcore-browser-refresh.js"></script>
below <script src="_framework/blazor.webassembly.js"></script> and hot reload is working with any libraries like ( matblazor and others). 
Hot Reload is not working with Lazy Loaded Razor Class Library Pages (In my case).

**Comment by vallgrenerik** [comment]
@MRakesh Okey, are you sure it works? Have you tried restarting the dotnet watch?
Even if I add `<script src="/_framework/aspnetcore-browser-refresh.js"></script>` it's still crashing.
With the browser-refresh.js the error now looks like this:
```
dotnet.6.0.0-preview.3.21201.4.js:1 Uncaught Error: System.TypeLoadException: EnC: cannot add new method with token 0x06000033
   at System.Reflection.Metadata.AssemblyExtensions.ApplyUpdate(Assembly assembly, ReadOnlySpan`1 metadataDelta, ReadOnlySpan`1 ilDelta, ReadOnlySpan`1 pdbDelta)
   at Microsoft.AspNetCore.Components.WebAssembly.Infrastructure.JSInteropMethods.ApplyHotReloadDelta(String moduleId, Byte[] metadataDelta, Byte[] ilDeta)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
--- End of stack trace from previous location ---
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(JSRuntime jsRuntime, DotNetInvocationInfo& callInfo, IDotNetObjectReference objectReference, String argsJson)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.Invoke(JSRuntime jsRuntime, DotNetInvocationInfo& invocationInfo, String argsJson)
   at Microsoft.AspNetCore.Components.WebAssembly.Services.DefaultWebAssemblyJSRuntime.InvokeDotNet(String assemblyName, String methodIdentifier, String dotNetObjectId, String argsJson)
    at Object._convert_exception_for_method_call (https://localhost:5011/_framework/dotnet.6.0.0-preview.3.21201.4.js:1:194923)
    at Object._handle_exception_for_call (https://localhost:5011/_framework/dotnet.6.0.0-preview.3.21201.4.js:1:196892)
    at managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_InvokeDotNet (https://mono-wasm.invalid/managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_InvokeDotNet:20:21)
    at Object.invokeDotNetFromJS (https://localhost:5011/_framework/blazor.webassembly.js:1:33466)
    at m (https://localhost:5011/_framework/blazor.webassembly.js:1:1068)
    at Object.e.invokeMethod (https://localhost:5011/_framework/blazor.webassembly.js:1:2130)
    at Object.he._internal.applyHotReload (https://localhost:5011/_framework/blazor.webassembly.js:1:49030)
    at https://localhost:5011/_framework/aspnetcore-browser-refresh.js:101:49
    at Array.forEach (<anonymous>)
    at applyBlazorDeltas (https://localhost:5011/_framework/aspnetcore-browser-refresh.js:101:12)
```

**Comment by pranavkm** [comment]
FYI @lambdageek

**Comment by lambdageek** [comment]
Haven't tried running the repro yet, but looking at the source for MatButton, I see it has a `RenderFragment ChildContent` parameter.
`RenderFragment`s compile down to C# lambdas, which are not supported yet in WebAssembly hot reload.  It's something I'm looking into, but it's not in this  preview yet.

**Comment by Xuntar** [comment]
Love the hot reload functionality, but the fact that RenderFragment parameters are not working yet is a huge bummer (I understand it's in preview though, of course).
As far as I could read on [Preview 3 blog post](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-3/), it should automatically rebuild and restart the app if it detects a change it can't apply. Is there a way to make it do that instead of crashing by any chance?

**Comment by lambdageek** [comment]
> As far as I could read on [Preview 3 blog post](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-3/), it should automatically rebuild and restart the app if it detects a change it can't apply. Is there a way to make it do that instead of crashing (ideally without having to wait for preview 4)?

Yes, the goal overall is to get to a point where:
1. edits that are supported by MonoVM hot reload will apply without crashing
2. edits that aren't supported are detected by `dotnet watch`/Roslyn and the app is restarted.

At the moment MonoVM and Roslyn aren't yet on the same page about what's supported.  (Partly because we are working on expanding what Mono can do. The Roslyn team would have to do some work to reliably detect and report rude edits, only to undo that work in the next release.)

I realize that leave folks trying it out now in a quite painful situation in the meantime, please bear with us.
