### ISSUE TITLE
Configuring Blazor Server to only use WebSockets

### ISSUE THREAD

**Issue by ryanbuening** [dotnet/aspnetcore#31976]
I'm trying to configure my Blazor Server app to only use WebSockets as the transport so as to not need to enable sticky sessions on our load balancer. I have tried the following:

`_Host.cshtml`
```
	<script src="_framework/blazor.server.js" autostart="false"></script>
	<script>
		Blazor.start({
			configureSignalR: function (builder) {
				builder.withUrl("/_blazor", {
					skipNegotiation: true,
					transport: 1
				});
			}
		});
	</script>
```

`Startup.cs`
```
app.UseEndpoints(endpoints =>
{
	endpoints.MapBlazorHub(options => options.Transports = HttpTransportType.WebSockets);
	endpoints.MapFallbackToPage("/_Host");
});
```

That configuration results in errors:

```
blazor.server.js:1 WebSocket connection to 'wss://domain.com/_blazor' failed: 
blazor.server.js:1 [2021-04-19T20:04:18.010Z] Error: Failed to start the connection: Error: There was an error with the transport.
blazor.server.js:21 [2021-04-19T20:04:18.011Z] Error: Error: There was an error with the transport.
blazor.server.js:1 Uncaught (in promise) Error: Cannot send data if the connection is not in the 'Connected' State.
```

Is there a different configuration I need to be doing for Blazor Server to only use WebSockets?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ryanbuening.
@BrennanConroy can you assign someone to help here? Thanks!

**Comment by BrennanConroy** [comment]
> Is there a different configuration I need to be doing for Blazor Server to only use WebSockets?

Nope, that's correct.

How are you hosting your app? Does the proxy/load balancer support websockets?

If you're using Azure App Service or IIS, you need to enable websockets manually.

**Comment by ryanbuening** [comment]
@BrennanConroy we are using IIS and we have WebSockets enabled. The load balancer (Fortinet ADC) supports WebSockets. We are doing something similar with an Angular/ASP.NET Core Chat app we have on our server that uses only WebSockets on SignalR.

**Comment by ryanbuening** [comment]
🤦‍♂️ I'm thinking I might need to configure `withUrl`. The app is hosted at https://subdomain.domain.com/appname

**Comment by BrennanConroy** [comment]
Glad the connection issue was resolved, sending to blazor folks to take a look at the "list of component records is not valid." error.

**Comment by javiercn** [comment]
@ryanbuening thanks for contacting us.

I suggest you try adding the following to the response emitted by your `.cshtml` page.

```
if (!context.Response.HasStarted)
{
    context.Response.Headers[HeaderNames.CacheControl] = "no-cache, no-store, no-transform, max-age=0";
}
```

before the component tag helper is invoked.

**Comment by ryanbuening** [comment]
@javiercn I added the following to the `_Host.cshtml` page:

```
@using Microsoft.Net.Http.Headers
@inject IHttpContextAccessor httpContextAccessor

@if (!httpContextAccessor.HttpContext.Response.HasStarted)
{
	httpContextAccessor.HttpContext.Response.Headers[HeaderNames.CacheControl] = "no-cache, no-store, no-transform, max-age=0";
}
```

but I still receive the `The list of component records is not valid.` error approximately 50% of the time when loading the app.

Is there a different way I need to be adding this? Thanks.

**Comment by javiercn** [comment]
@ryanbuening You don't need to use the HttpContext accessor. 

The HttpContext instance is available within _Host.cshtml already.

Can you provide a bit more context on the page within _Host.cshtml so that we can see the full picture?

Also, is the code hosted in more than one server instance?

Finally, try removing `@if (!httpContextAccessor.HttpContext.Response.HasStarted)` in case you started to flush the response earlier (you'll get an exception if that's the case) and we'll know if it wasn't taking effect

**Comment by ryanbuening** [comment]
@javiercn the full `_Host.cshtml` is below. I removed the `@if` check and I'm still getting the same error occasionally.

The code **is** hosted on more than one server instance which was the original question on this issue. I was trying to configure Blazor Server in a way where we don't need to use sticky sessions on our load balancer which is in front of our (two) IIS servers. I was under the impression that only using WebSockets as the transport would allow us to do that. When we **do** have sticky sessions enabled, the app loads successfully every time and I do **not** receive the `The list of component records is not valid` error.

However, the goal was to see if we were able to run Blazor Server behind our load balancer without needing to enable sticky sessions. Some of that challenge was solved by using only WebSockets as the transport, but it seems like there might be more to it as this `list of component records is not valid` error indicates.

```
@page  "/{handler?}"
@model HostAuthModel
@namespace BlazorRaterServer.UI.Pages
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using Microsoft.AspNetCore.Authorization
@using Microsoft.AspNetCore.Components.Authorization
@using System.Security.Claims
@using Microsoft.AspNetCore.Http
@using Microsoft.Net.Http.Headers

@attribute [AllowAnonymous]

@{
	Layout = null;
	HttpContext.Response.Headers[HeaderNames.CacheControl] = "no-cache, no-store, no-transform, max-age=0";
}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>BlazorRaterServer.UI</title>
	<base href="~/" />
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
	@*<link rel="stylesheet" href="css/bootstrap/bootstrap.min.css" />*@
	<link href="css/site.css" rel="stylesheet" />
	<link href="BlazorRaterServer.UI.styles.css" rel="stylesheet" />
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
	<link href="_content/Blazored.Modal/blazored-modal.css" rel="stylesheet" />
</head>

<body>
	@*@if (User.Identity is not null && User.Identity.IsAuthenticated)
		{*@
	<app>
		<component type="typeof(App)" render-mode="Server" />
	</app>
	@*}*@
	@*else
		{
			<p>
				<a href="/Login">Login</a>
			</p>
		}*@

	<div id="blazor-error-ui">
		<environment include="Staging,Production">
			An error has occurred. This application may no longer respond until reloaded.
		</environment>
		<environment include="Development">
			An unhandled exception has occurred. See browser dev tools for details.
		</environment>
		<a href="" class="reload">Reload</a>
		<a class="dismiss">🗙</a>
	</div>

	@*<script src="_framework/blazor.server.js"></script>*@

	<script src="_framework/blazor.server.js" autostart="false"></script>
	<script>
		Blazor.start({
			configureSignalR: function (builder) {
				@*builder.withUrl("/_blazor", {*@
					builder.withUrl("/blazorrater/_blazor", {
						skipNegotiation: true,
						transport: 1
					});
				}
		});

	</script>

	<script src="_content/CurrieTechnologies.Razor.SweetAlert2/sweetAlert2.min.js"></script>
	<script src="_content/BlazorInputMask/Main.js"></script>
	<script src="_content/BlazorInputMask/IMask.js"></script>
	<script src="_content/Blazored.Modal/blazored.modal.js"></script>

	<!-- Auto reconnect -->
	<script>
		Blazor.defaultReconnectionHandler._reconnectCallback = function (d) {
			document.location.reload();
		}
	</script>
</body>
</html>
```

**Comment by javiercn** [comment]
@ryanbuening the issue is likely then with sticky sessions.

Blazor requires sticky sessions to work, we don't guarantee anything works if you don't enable them. There are a couple of things that might be going wrong in your case, one is that data protection is not correctly configured to share keys across al your servers or that the clock in your servers is not in sync and preventing the Blazor descriptor from being decrypted.

**Comment by ryanbuening** [comment]
> Blazor requires sticky sessions to work, we don't guarantee anything works if you don't enable them. There are a couple of things that might be going wrong in your case, one is that data protection is not correctly configured to share keys across al your servers or that the clock in your servers is not in sync and preventing the Blazor descriptor from being decrypted.

Ok. We'll take a look at those things and keep in mind that we may just need to enable sticky sessions. Thanks.

**Comment by ryanbuening** [comment]
It looks like not having data protection setup was the issue here. Just wanted to follow up for anyone that finds this.
