### ISSUE TITLE
[Blazor] [.NET 6 preview 5] New server project null reference exception

### ISSUE THREAD

**Issue by paprzytula** [dotnet/aspnetcore#33868]
### Describe the bug
<component type="typeof(App)" render-mode="ServerPrerendered" /> - error reported here in _Host.cshtml
On .NET 6.0.0.preview.5 in VS19 16.11.0 preview 2 after creating new Blazor server project and try to run:
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=System.Private.CoreLib
  Ślad stosu:
   w System.Runtime.CompilerServices.CastHelpers.IsInstanceOfClass(Void* toTypeHnd, Object obj)
   w Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewAttributeFrame(DiffContext& diffContext, RenderTreeFrame& newFrame)
   w Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   w Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   w Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   w Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   w Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   w Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   w Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
--- Koniec śladu stosu z poprzedniej lokalizacji ---
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception)
   w Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
   w Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessPendingRender()
   w Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   w Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
   w Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   w Microsoft.AspNetCore.Components.ComponentBase.<RunInitAndSetParametersAsync>d__20.MoveNext()
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception)
   w Microsoft.AspNetCore.Components.RenderTree.Renderer.HandleExceptionViaErrorBoundary(Exception error, ComponentState errorSourceOrNull)
   w Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToPendingTasks(Task task, ComponentState owningComponentState)
   w Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)
   w Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
   w Microsoft.AspNetCore.Components.RenderTree.Renderer.<RenderRootComponentAsync>d__36.MoveNext()
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   w Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.<CreateInitialRenderAsync>d__17.MoveNext()
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   w Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.<RenderComponentAsync>d__8.MoveNext()
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   w Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c__11`1.<<InvokeAsync>b__11_0>d.MoveNext()
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   w Microsoft.AspNetCore.Mvc.ViewFeatures.StaticComponentRenderer.<PrerenderComponentAsync>d__4.MoveNext()
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   w Microsoft.AspNetCore.Mvc.ViewFeatures.ComponentRenderer.<PrerenderedServerComponentAsync>d__11.MoveNext()
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   w Microsoft.AspNetCore.Mvc.ViewFeatures.ComponentRenderer.<RenderComponentAsync>d__6.MoveNext()
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   w Microsoft.AspNetCore.Mvc.TagHelpers.ComponentTagHelper.<ProcessAsync>d__21.MoveNext()
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   w Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<<RunAsync>g__Awaited|0_0>d.MoveNext()
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   w HotReloadBlazor.Pages.Pages__Host.<<ExecuteAsync>b__14_1>d.MoveNext() w c:\Users\username\source\repos\HotReloadBlazor\HotReloadBlazor\Pages\_Host.cshtml:wiersz 20

  Ten wyjątek został pierwotnie zgłoszony w tym stosie wywołań:
    [Kod zewnętrzny]
    HotReloadBlazor.Pages.Pages__Host.ExecuteAsync.AnonymousMethod__14_1() w _Host.cshtml```


### Further technical details
Microsoft Windows [Version 10.0.19043.1052]
(c) Microsoft Corporation. Wszelkie prawa zastrzeżone.

C:\Users\username>dotnet --info
Zestaw .NET SDK (odzwierciedlenie dowolnego pliku global.json):
 Version:   6.0.100-preview.5.21302.13
 Commit:    d6380bcae7

Środowisko uruchomieniowe:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\Program Files (x86)\dotnet\sdk\6.0.100-preview.5.21302.13\

Host (useful for support):
  Version: 6.0.0-preview.5.21301.5
  Commit:  ec3e0b276b

.NET SDKs installed:
  6.0.100-preview.5.21302.13 [C:\Program Files (x86)\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-preview.5.21301.17 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-preview.5.21301.5 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.5.21301.4 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
How are you publishing / running the app?

**Comment by paprzytula** [comment]
I tried F5, dotnet watch and ISS Express.

**Comment by pranavkm** [comment]
Are you able to share a minimal app that reproduces the problem? We tried a project created from the template using the SDK that you listed but are unable to see this issue. Thanks!

**Comment by paprzytula** [comment]
OK, I'll install again the preview 5 and try to recreate issue

**Comment by paprzytula** [comment]
![image](https://user-images.githubusercontent.com/14290787/123845477-86425700-d914-11eb-956d-c35e025ef81e.png)
The code is available here:
[BlazorIssued](https://github.com/paprzytula/BlazorIssued)

**Comment by paprzytula** [comment]
I've installed Microsoft Visual Studio Enterprise 2019 Preview
Version 16.11.0 Preview 2.0 and dotnet --version 6.0.100-preview.5.21302.13 on another PC. Newly created project works fine. The issue can be related to many preview versions and need of switching environment variables (Path - VS19 solution explorer didn't show files under dotnet x64).

**Comment by paprzytula** [comment]
After format and clean Windows 10 install i can open sql designer under VS19 - success. I've installed dotnet x64 and x86.
![image](https://user-images.githubusercontent.com/14290787/124629932-3585ad80-de82-11eb-8c74-694b4f4dc255.png)
![image](https://user-images.githubusercontent.com/14290787/124630237-84cbde00-de82-11eb-882c-fa5602d125c9.png)
Tried on x64. The main issue is related to Path: 
![image](https://user-images.githubusercontent.com/14290787/124630864-1a676d80-de83-11eb-9f12-c6985c4629b5.png)
Different order makes it working. I'd suggest to change naming of the versions to allow usage of specific .NET versions.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe this is now fixed in the latest 6.0-preview6 release. Can you please try that out and see whether you are still facing it or not.

**Comment by pawelel** [comment]
I can't reproduce the issue because didn't backup old system. Just hope, that the issue is solved for others.

**Comment by ashishsinha24** [comment]
I am still facing this issue. 
I am developing on Visual Studio 2022 Preview 3.1 with .Net 6.0.100-rc.2.21428.11 9 & Windows 11

Earlier, Whenever I restarted my computer, the error vanished, but today, even after several restarts the error still persists

**Comment by rsudbdg** [comment]
> I am still facing this issue.
> I am developing on Visual Studio 2022 Preview 3.1 with .Net 6.0.100-rc.2.21428.11 9 & Windows 11
> 
> Earlier, Whenever I restarted my computer, the error vanished, but today, even after several restarts the error still persists
> 
> Got It working. Two pages had the same routes.
> 
> Was able to debug it by adding an to my App.razor file. and then a human readable messages showed up in the console.


:)
I had the same issue until I found a component which has 2 routes, 1 route pointed to root "/";

Profile.razor
@page "/"
@page "/account/profile"

... fixed
@page "/account"
@page "/account/profile"
