### ISSUE TITLE
Pack of .NET 5 RazorClassLibrary is broken when .NET 6 Preview 7 is installed 

### ISSUE THREAD

**Issue by TFTomSun** [dotnet/aspnetcore#35568]
### Describe the bug
I have a side by side installation of Visual Studio 2022 and Visual Studio 2019. But I think that bug appears whenever you try to pack a Razor Class Library with TargetFramework net5.0 using the .NET 6 Preview 7 build toolchain.

### To Reproduce
* Install Visual Studio 2019 and / or 2022
* Make sure that the latest .NET 5 SDK is installed
* Install .NET 6 Preview 7 SDK 
* Open Visual Studio and create a RazorClassLibrary with target framework net5.0
* Right-Click the Project and select Pack
* Ensure that the .NET 6 Preview tool chain is used for build by checking the output

### Exceptions (if any)
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Static web asset 'Severity	Code	Description	Project	File	Line	Suppression State
Error		Static web asset 'D:\Git\siemens_testing\TestApp\ConsoleApp1\RazorClassLibrary1\wwwroot\exampleJsInterop.js' has invalid source type ''.	RazorClassLibrary1	C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.StaticWebAssets.5_0.targets	436	

```

**Comment by javiercn** [comment]
@TFTomSun thanks for contacting us.

We've done extensive work on razor class libraries on preview 7 and this is a know limitation that we've fixed on RC1. If you try an RC1 nightly build from dotnet/installers you shouldn't have any issues. Let's us know if that's not the case.

**Comment by jsakamoto** [comment]
Hi @javiercn, could you reopen this issue?

> Let's us know if that's not the case.

On my PC, I could still reproduce this problem even though on .NET 6 RC1.

I attached the sample project to this post as below.

[📂 RzcLibNet5.zip](https://github.com/dotnet/aspnetcore/files/7177603/RzcLibNet5.zip)

The project above was created by the `dotnet new razorclasslib -n RzcLibNet5` command with .NET 5 SDK.

With .NET SDK 6 RC1, when I executed `dotnet pack -c:Release` command against that project, it was failed with the following error message.

```
C:\Program Files\dotnet\sdk\6.0.100-rc.1.21458.32\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.5_0.targets(500,5): 
error : Static web asset 'C:\Project\...\RzcLibNet5\wwwroot\exampleJsInterop.js' has invalid source type ''. 
```
![image](https://user-images.githubusercontent.com/95908/133611458-e3f18b32-8a19-41b4-8a2b-b03e86e90c8b.png)

I appreciate it if you investigate my case.

<details>
<summary>- Include the output of `dotnet --info`</summary>

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21458.32
 Commit:    d7c22323c4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.1.21458.32\

Host (useful for support):
  Version: 6.0.0-rc.1.21451.13
  Commit:  d7619cd4b1

.NET SDKs installed:
  2.1.818 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.413 [C:\Program Files\dotnet\sdk]
  5.0.401 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.1.21458.32 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.1.21451.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
</details>

**Comment by javiercn** [comment]
@jsakamoto thanks for letting us know.

Unfortunately seems like a separate change we did regressed this scenario in RC1. We have fixed it in RC2, if you want to make sure that's the case, you can grab the latest nightly build of the sdk at dotnet/installer and check it out.

**Comment by javiercn** [comment]
Just confirmed it works with the latest RC2 nightly 
![image](https://user-images.githubusercontent.com/6995051/133624126-141c008d-7773-4581-a99a-482d741262bf.png)
