### ISSUE TITLE
Error using a generated razor class in any other class

### ISSUE THREAD

**Issue by CrahunGit** [dotnet/aspnetcore#36265]
### Describe the bug
There is a bug that caused VS 2022 Versión 17.0.0 Preview 3.1 not compiling blazor 6 app when there is a reference to a generated class. Let me explain. I'm using 

```csharp
IStringLocalizer<AddressEditor> localizer
```

Where AddressEditor is a razor component and the compiler says "Type or namespace not found". This works fine with the cli.

Worked fine on preview 7 but not rc1

### To Reproduce
Create a razor component and reference the generated class from any other c# class. It works fine on components from VS 2022.

For example, if you use the current blazor template
```csharp
    public class Learner
    {
        public Learner()
        {
            var f = new FetchData();
        }
    }
```

This will fail compiling.

I've got a repo showing the bug [https://github.com/CrahunGit/BlazorBug](https://github.com/CrahunGit/BlazorBug)

### Exceptions (if any)
Type or namespace name 'AddressEditor' not found (using directive or assembly reference missing?)

### Further technical details
- ASP.NET Core version 6.0.100-rc.1.21457.47
- Include the output of `dotnet --info`
SDK de .NET (que refleje cualquier global.json):
 Version:   6.0.100-rc.1.21457.47
 Commit:    86222977d2

Entorno de tiempo de ejecución:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.1.21457.47\

Host (useful for support):
  Version: 6.0.0-rc.1.21451.13
  Commit:  d7619cd4b1

.NET SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.0.103 [C:\Program Files\dotnet\sdk]
  3.1.405 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]
  5.0.400 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.1.21457.47 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.5.21301.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.5.21301.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.7.21378.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.1.21451.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
- The IDE (VS / VS Code/ VS4Mac) is VS 2022 Versión 17.0.0 Preview 3.1

**Comment by CrahunGit** [comment]
I've use it to get translation on fluent validator class. I need to inject 
```csharp
IStringLocalizer<AddressEditor> localizer
```

**Comment by pranavkm** [comment]
Could you try updating to a newer build of the SDK? We had a compiler bug that resulted in strange behavior such as the one you're observing, which should be addressed in a newer RC1 build of the SDK.

**Comment by CrahunGit** [comment]
Ok, i’ve tried this morning with rc1 and rc2 and it’s still failing. Anyway i will try again. Now I’m compiling with the cli and works fine

**Comment by CrahunGit** [comment]
Tested against 6.0.100-rc.1.21458.46 and 6.0.100-rc.2.21458.9. It's still failing for both of them.

**Comment by CrahunGit** [comment]
Ok, the error is gone with the official rc1 and vs studio 2022 preview 4.
