### ISSUE TITLE
Locating an owner in a Razor syntax tree can fail

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#36689]
With this document and cursor / location requested denoted by `|`:

```Razor
@page "/"

<h1>Hello, world!</h1>

Welcome to your new app.
<SurveyPrompt Title="How is Blazor working for you?" />
<Input>
    <input />
</Input>|

```

Calling syntaxTree.Root.GetOwner(...) returns null. It should at the very least be returning the base document body.

This results in an unexpected flow at tooling time:
![image](https://user-images.githubusercontent.com/2008729/133864148-b21df1bd-6ddd-4e12-93f7-7f7697b41514.png)

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen can you share info about what is the impact and severity of this?
Moving this to .NET 7 planning milestone for future consideration. In the meantime, if you believe there is a critical factor here that I'm missing, please clear the milestone so that we can see this again.

**Comment by NTaylorMullen** [comment]
> can you share info about what is the impact and severity of this?
> Moving this to .NET 7 planning milestone for future consideration. In the meantime, if you believe there is a critical factor here that I'm missing, please clear the milestone so that we can see this again.

Ya this is pretty critical it means that there are "holes" in the SyntaxTree that can't be reasoned about. The end-user impact is either some Razor features entirely breaking down in those areas (could result in documents getting trashed) or simply features not lighting up when expected.

**Comment by ryanbrandenburg** [comment]
Here's another way this expresses itself: https://github.com/dotnet/aspnetcore/issues/39764.

As noted in that issue I suspect that this is a problem somewhere in `DefaultRazorTagHelperBinderPhase`. Probably the logic that matches StartTag to EndTag is being confused by the self-closing `<input />` before the `</Input>`. I attempted to investigate further but struggled enough that I thought I'd leave it to the experts.

This seems super similar to what I fixed in https://github.com/dotnet/razor-compiler/pull/13.

**Comment by javiercn** [comment]
Looked into this issue and was already fixed. From what @NTaylorMullen points out, @ryanbrandenburg did some work at some point to fix this case. That said, I'm not able to find the commit, but in this case the API seems to be working as expected in the current version.

**Comment by ryanbrandenburg** [comment]
@javiercn I have not fixed this scenario, it's the same thing as https://github.com/dotnet/razor-tooling/issues/4533 and still happening as of 17.2.0 Preview1.0 32201.39.main.

**Comment by javiercn** [comment]
@ryanbrandenburg I'm a bit confused, I literally wrote a unit test on the compiler right now, and it was returning the document root.

One thing that I discussed with @NTaylorMullen is that for these repros to be

**Comment by ryanbrandenburg** [comment]
Though I can reproduce the scenario above 100% in real use-cases I also found that razor-compiler unit tests I tried to write for this scenario passed. My best-guess is that it's some combination of behaviors across the initial parse and subsequent passes.

I'm not sure what you mean about a source change. Taylors repro above works even if you launch VS when the project is already in the given state if that has any bearing on what you're thinking. If it's helpful, the [LOC shown in his screenshot is here](https://github.com/dotnet/razor-tooling/blob/adcccb2a563ecc250d65081cab04d2bbb55a1ea2/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/ExtractToCodeBehindCodeActionProvider.cs#L54).

**Comment by javiercn** [comment]
Got the tree for the sample above

```
RazorDocument - [0..44) - FullWidth: 44 - [@page "/"LF<Input>LF    <input />LFLF<p></p>]
    MarkupBlock - [0..44) - FullWidth: 44
        MarkupTextLiteral - [0..0) - FullWidth: 0 - [] - Gen<Markup> - SpanEditHandler;Accepts:Any
            Marker;[];
        CSharpCodeBlock - [0..11) - FullWidth: 11
            RazorDirective - [0..11) - FullWidth: 11 - Directive:{page;SingleLine;FileScopedMultipleOccurring}
                CSharpTransition - [0..1) - FullWidth: 1 - Gen<None> - SpanEditHandler;Accepts:None
                    Transition;[@];
                RazorDirectiveBody - [1..11) - FullWidth: 10
                    RazorMetaCode - [1..5) - FullWidth: 4 - Gen<None> - SpanEditHandler;Accepts:None
                        Identifier;[page];
                    CSharpCodeBlock - [5..11) - FullWidth: 6
                        MarkupEphemeralTextLiteral - [5..6) - FullWidth: 1 - [ ] - Gen<None> - SpanEditHandler;Accepts:Whitespace
                            Whitespace;[ ];
                        CSharpStatementLiteral - [6..9) - FullWidth: 3 - ["/"] - Gen<DirectiveToken {route template;String;Opt:False}> - DirectiveTokenEditHandler;Accepts:NonWhitespace
                            StringLiteral;["/"];
                        MarkupEphemeralTextLiteral - [9..11) - FullWidth: 2 - [LF] - Gen<None> - SpanEditHandler;Accepts:Whitespace
                            NewLine;[LF];
        MarkupTagHelperElement - [11..35) - FullWidth: 24 - Input[StartTagAndEndTag] - Input
            MarkupTagHelperStartTag - [11..18) - FullWidth: 7 - [<Input>] - Gen<Markup> - SpanEditHandler;Accepts:Any
                OpenAngle;[<];
                Text;[Input];
                CloseAngle;[>];
            MarkupTextLiteral - [18..24) - FullWidth: 6 - [LF    ] - Gen<Markup> - SpanEditHandler;Accepts:Any
                NewLine;[LF];
                Whitespace;[    ];
            MarkupElement - [24..33) - FullWidth: 9
                MarkupStartTag - [24..33) - FullWidth: 9 - [<input />] - Gen<Markup> - SpanEditHandler;Accepts:Any
                    OpenAngle;[<];
                    Text;[input];
                    MarkupMiscAttributeContent - [30..31) - FullWidth: 1
                        MarkupTextLiteral - [30..31) - FullWidth: 1 - [ ] - Gen<Markup> - SpanEditHandler;Accepts:Any
                            Whitespace;[ ];
                    ForwardSlash;[/];
                    CloseAngle;[>];
            MarkupTextLiteral - [33..35) - FullWidth: 2 - [LF] - Gen<Markup> - SpanEditHandler;Accepts:Any
                NewLine;[LF];
        MarkupTextLiteral - [35..37) - FullWidth: 2 - [LF] - Gen<Markup> - SpanEditHandler;Accepts:Any
            NewLine;[LF];
        MarkupElement - [37..44) - FullWidth: 7
            MarkupStartTag - [37..40) - FullWidth: 3 - [<p>] - Gen<Markup> - SpanEditHandler;Accepts:Any
                OpenAngle;[<];
                Text;[p];
                CloseAngle;[>];
            MarkupEndTag - [40..44) - FullWidth: 4 - [</p>] - Gen<Markup> - SpanEditHandler;Accepts:Any
                OpenAngle;[<];
                ForwardSlash;[/];
                Text;[p];
                CloseAngle;[>];
```

It's missing the trailing `</Input>`

**Comment by davidwengier** [comment]
Another example. Given:

```
@foreach (var num in Enumerable.Range(1, 10))
{
    <span class="skill_result btn">
        <!--asdfasd-->
        <span style="margin-left:0px">
            <svg>
                <rect width="1" height="1" />
            </svg>
        </span>
    </span>
}
```

`LocateOwner` on the `<span` after the comment will return the `<span`. If you remove the comment, `LocateOwner` will return the whitespace in front of the `<span`.

The tree diff between with and without comment can be see [here](https://wengier.com/LinkableDiff/#7R1rbxM50N9O4lcEPoEEtJvHJkuhusKV43TA3QE6PiB0gjZ9iDbtNS2PQ_z3G9vrxzq7sb1rZ72pNWpYkrU9L4_Hr5lX6AP6D52hC_QLfO6hK3SKpmiGLlEP3YO_d2gT3QfoowGaoDv5t0_hvROAt-gY7cO7R-gBfEvfYeV-Rgek3im0sAdv9NBt9BmeL-BpRtrpQekZfO7m_5_Cbx_QR6h3Ci2-gucZOoTn2yhBd-G9BHC5A_Ac2v9OPh-iOTon7_WgjRN4mgM8Qrfg8xPUjnH8h-AwJxhjqj7C5wze2CY19HKQa5rDG98IFrimU4LzIcH1Hvn2AH5_ALico68L9cj1fYZS5b-KtzBuewSvL5yXuNUE_nrwPIVvD-HfS-nbjco2N0pbpd9T6tRfbgJN9-CXfaAKc-8AnvA32zl_1ZI_yOd7dIPX8YLw5xPw9xw9Bv5gLfpUW3tuLFAl1_8G-PEVSjyHkpe5vpwobW1q2tnk77_Pn34lGv-w0NJ2_tvrnPpdqAG3-Yz8b5_owQXaQjtA7R48n8Nvc6h_B379VkKFSg0tjXHYKnn7CbR7RN48h-czaG-6lLepAW_TJVjJ7b0hXJ0BNZjeY2hzprSYaFpLFL6-JHVMa_OUla_Gn0EZ7lvEFpXzuYz-11DyA9EuZgnLtS0hvBhp9W2IMl7Gv0VUdRpTcwp_vvSZwe9Q5hvYMEzfPuF5kdbl_GfwFt6kvKZWB2OC6-oZln-eW-c_CVep9I5Ibcfwh2u6bVjTb6TPzYgWHcAf669UXquhpgoHqhurwWFRrlhD26W_rHeY1Yh9nEtSx_2GOIi-uHrNnBGeHhJcirZpi9gls3rwuHJKvBtc6u7KZKrDftOwplfcM6rm6Z0W6noJpb4QymY5b6hdttGSx4QjjLffPba83HsbST7GQDvqT-AdPZZyi7uk76ozDh-tlrVOR_oL-HwD_x4utD_RejoD7uu8azgX8eGLmvtNKvwBdWA8doiNO8m16aGhHqrAvHZcB-NRvZpkruxAjZfwv2Pg4hWxImX6O8olqfPS-vAmK2Uvv_c1aCmjafn8hlEz0vr7Qit7rcxyTKHpaOKCpynhaart60I_hHaEzFu518kYN-HrLvoXaMP8o2Pio5XJKYUeSuWkHxFYmVtBywf7ole59_oXPJ0RqrdyvJtwlVI7JbZxr8QqYh5iXo5hZqrj5bJVgzpSLkp30Yb_Tb6_gqdFbEdabPu8VJXNbmKpm2ivWxrC1WoVimN_FT1NtN2Nlo3zsVXfJ4ZIjK10_G9HpwTG6-INqODLO2jC89RQSwa8DNOR7vBd7rMM-9WM8pivZv769R3ln5DxfA61FGdn25b1mUtlkq91T0A-y6WS8jLyLlNI8mmyOqNCtX1idNeVR_m6COY_XRfZhFFI1z8SeLvZDLtqfYThQdvQ2UGx39ZkjzWs9REGbtdJGLhbLymTqsm6SZbPthIyA9CtnMgekZ1cXXhO5naMUZVZzCHDsl5V4NtTsuHxIOexbr9frKcInekCr4u9U2Dugs-u11fqyC_Le_7m2vhgDPytuDDQrbxQrjLLql8LGHma5djPj-0xZyWXjwEu585llC7Xdn9Uhd8bVJDtmo661dokKhtTfyRaJQauZor1JMbmCH3tHCGR5ghl5xpDlKLLeSQD3XxS8KOp9Mrnl1RWVGqZdj8sBb_fzYykap4p4zOAZ1N_Upy9DXPWyMDP7JFB0U_F_HBTr2urUqYROusy4PPTocF4IOany85ih2hlGPiwNgxMrY7gkyspV1mhYb7Knhjsl_XBUrn1RaqtkS1ewh7VPeUftv1i4NeOMZDtGeOnv30gk1Uy7JUmuUboz4_IXk6ZHrQ9ExK0jLRjbdfWx1RY1c5iPTn0uRx0nrPweYQ-dVEect-WKfEhC19rbM1kPuEy15_J6db8VgX_q3Aq6FflRnzVMzVY9fTHm6ZrdHZ0iHI-xp5ltOn7Q106utcfVJBtoeldDp-ySPkKqYmPE22TvQTMfM2U-2djA_9M9tDK5hdte5uCmjR6m63Koc_loNuxFad7ZI3qokRkG1uk5bp4nCkfYcdrt8-rQoge55iPqmODUTVcj9OOjnA9zvp0dK8_qBCaxzm28nSibbKXwAuEbzXvlfTxJ2R1-HJhTX7M_YSxwem5tvXHBtfoW5rAUxIB4gvhyD5wgd4nPCJtbThuK4QdxjE_cTIxOBfUvfMLDELYWXS5o4h5pu7bTbgsTU41iF27jXiOAK2m53flrIKNBcm4F5Otwb0ZBm2ce3Jx3qnMLmQW92nGqGgXWEy8MC2DH4vg0xK4v_Oy-ntyVI-oRiXaVZXw-3w37sqxOFZ0xrK41kJlQaXSN7g3V-dUo42OCGwSLTbi5BqL1Hmd7M1jRGOs4bpuNqxLnmc_g95wTtZ9aXRIyle__gCVNtNCnRcqRptiZFYf0i_rmW7suIq7bw73c4_LpJ-L-_k02m2Y_cqP1jJoY4TsS71Af7NUHiHDkpCLsVHnoVIemUbC64aH6nak8OGRuvNE6_avOtGIqYaYxoMW1o_G9HYdNdhcP5r0IxG1sxgv80dFeRs7NZB6nj5yuW87pfPgl3HxJxKr1izG_8iA1lGHY_yzaPdz7pnI0e7FezEXgM9cAKZa1qQHX9dcAPrYoPQds9En5gKIuQBiLoCYC6BKrjEXQMwF0ESmMReAXkvCywUw0q5F4J0Q17kA3LVa1nrMBVAFMRdAzAUQcwHEXAAqxFwAIUcJZhBzAcRcAKGcWS6O_TEXgDudirkA2uB5zAXgl78xF4AOYi6AeL5RROPfNNiN8Xu6keGiv2cRTzauy8lGds9BH_FdPtUo78B37VRjEXff3J0Y9-54prGNEZFKhskonFGx3bONDFadI4fKwPy0v78sOQITHK825slZxzw5CVmjYTJen0w5Ml3J2t2hDydbDuUu43PMmGMP7WfMSchNUpbrYF3WKhiEkDOnz88aDjqWM8cWc1Yy7Jw5vqgKvzeoIFu20HLmDHjUC71nEq0SgzYjRgz4fGEYc-YYQvs5c4Z8vpkYRJfxnzNnyLVIH8c_5swpQlfi0JRphM66iLwCacyZ0xDCy5mT8tw0WVA5c2zxEvYo5sxpDrI9CyVnjojuqT9THXrOnHqRSsO2m1UQchRzOeJnzJnjvs0QI5iP-c6oydnVbs1vVQgzgnnG7XiXc-bY0SHKhRfBvC4d3esPKsi2MIQI5hO-Qmri40TbZC8BM19zgkQM1u7nzBHUTKK32aoc-lwOMWfO9fE4J3yEzdZun1eFED3OjI-q-vPFIXucdnSE63HWp6N7_UGF0DzOzMrTibbJXgL2OXMy7idkwefMscM1-pYmcN1y5mT5iRN8PijmzKkHYeTMoRI0P9Ugdu1izpweijlzZLCLkZ9wrQvnJk0Xzz35yZlD5WJ6u6YbEckZxJw5bWcEGMScOQVoM2fOgMfdGwaQM0dgM4g5c5bCOt0sp9JmWhhz5vjg8JB7XPp-Hu-XtzNCDqVeEHPm6DzUIc_coY8Y2w0PNebM8ZUzZ8Rz5ujjqMacOTo7NZJ6Xrdz5vwP), and I've highlighted the whitespace-before-span-element below to show the differences:
<img width="1498" alt="image" src="https://user-images.githubusercontent.com/754264/154214212-c9cab72d-5f58-43c3-9747-0e43d91a9e65.png">
