### ISSUE TITLE
Use given model nullability in razor pages

### ISSUE THREAD

**Issue by Jupakabra** [dotnet/aspnetcore#37510]
We are migrating our 5.0 project to 6.0-rc2 and noticed that [RazorPage.Model](https://github.com/dotnet/aspnetcore/blob/v6.0.0-rc.2.21480.10/src/Mvc/Mvc.Razor/src/RazorPageOfT.cs#L18) was changed to always be nullable, even though model type in razor file is specified as not null. Because of this, we are getting thousands of compile time errors on any model access outside of `asp-for` expressions like `asp-route-id="@Model.Id"`.

### Describe the solution you'd like
Would it be possible to change it to `TModel` from `TModel?`?
So we can tell the razor page if model is possibly null or not in the view?
```
@model MyModel?
```

### Additional context
My guess is that razor doesn't parse nullable models in views, so it wasn't made that way because of that?

**Comment by Jupakabra** [comment]
Tried using custom razor page model, but as expected razor doesn't handle it well today. For example using
```
@model TestModel?
```
Doesn't compile at all, because nullability context is disabled? Even though the project has it enabled.
```
cshtml.g.cs(10,5,10,6): error CS8669: The annotation for nullable reference types should only be used in code
within a '#nullable' annotations context. Auto-generated code requires an explicit '#nullable' directive in source.
```

**Comment by Bartmax** [comment]
I'm having this issue too. I believe it was wrong to annotate `TModel` as ?. A real blocker to upgrade to net6.
For me it's impossible to upgrade to NET6. I have 1983 views in one project only.

We need a way to fix (opt out of nullable razor models) with one liner at startup.

**Comment by seangwright** [comment]
This is a show-stopping breaking change if an app has <WarningsAsErrors>nullable</WarningsAsErrors>.

If an application has hundreds (or thousands) of Views, it's going to take awhile adding this 'unofficial' solution to get the app to compile again.

> A possible workaround might be to introduce a base type for your view

Where was the planning for this feature? What was the official planned recommendation to resolve this issue for the many apps built before .NET 6.0?

Hundreds or thousands of errors after upgrading to .NET 6.0 and the best we have at the moment is "a possible workaround"?

🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️

**Comment by pranavkm** [comment]
Thanks for the feedback. Addressing this is two parts - 

* a change in the to make [this non-nullable](https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Razor/src/RazorPageOfT.cs#L18. It's fibbing a bit because the runtime doesn't enforce nullability for the model value, but it's definitely a lot less ergonomic this way. 
* update the Razor compiler to allow non-nullable models to be declared

My hope is to try and get these tackled as part of an upcoming VS release / .NET servicing release.

**Comment by pranavkm** [comment]
This is fixed for the 6.0.2 release of the runtime and a compiler change that allows models to be declared as nullable would be available in 17.1 / 6.0.200 version of the .NET SDK. Thanks for all of your feedback!

**Comment by kingmotley** [comment]
@pranavkm Since runtime 6.0.2 seems to be included in the 17.0.6/6.0.102 SDK would those be appropriate, or is there additional work coming in 17.1.x/6.0.2xx?

**Comment by dotnetshadow** [comment]
I just updated my app to 6.0.2 but I'm still getting the analyser message:
Severity	Code	Description	Project	File	Line	Suppression State
Warning (active)	**CS8602	Dereference of a possibly null reference.**	StockWatch.Web	d:\Programming\Code\.....\Dashboard\Index.cshtml	70	

This is how I'm using it
```
@model Foo.Dashboard.DashboardViewModel

<span class="counter-number-related text-capitalize">@("people".ToQuantity(Model.UserOnlineCount, ShowQuantityAs.None))</span>
```

**Comment by pranavkm** [comment]
So I just tried this with the 6.0.102 SDK installed and the runtime changes work - doing `@Model.UserOnlineCount` does not produce a nullable warning. I'm still unable to do `@model TestModel?` since that relies on a change in the 6.0.200 SDK which hasn't shipped.

Could you confirm that's the SDK your app is using to build? SDKs typically roll forward, so if you happen to have a 6.0.200 preview SDK installed side-by-side, it'll end up using that instead and not use these changes. You can confirm the SDK that is being used by running `dotnet --info`. You can also use a `global.json` to specify an exact SDK to use to build your project. You could consider using that until a RTM 6.0.200 rolls out:

Global.json contents:

```json
{
  "sdk": {
    "version": "6.0.102"
  }
}
```

**Comment by dotnetshadow** [comment]
> 
This is my runtime info
![image](https://user-images.githubusercontent.com/296247/153092682-4541d633-78d1-47d6-952d-52b7dc4a6659.png)

**Comment by pranavkm** [comment]
@dotnetshadow  setting the AnalysisMode does not change the result for me. Do you see the same error if you build the app from the CLI? If you do, could I bother you to share msbuild binary logs by running `dotnet msbuild /bl` and including the MSBuild.binlog file. It might provide some hints about what's happening here. 

Note that binlogs will capture ambient environment variables.

**Comment by dotnetshadow** [comment]
> Do you see the same error if you build the app from the CLI?

Funny you should ask, I just tried that and not getting any warnings when using the cli

**Comment by pranavkm** [comment]
@dotnetshadow looks like the file was removed.

**Comment by dotnetshadow** [comment]
> @dotnetshadow looks like the file was removed.

Sorry about that I uploaded to a new host
https://www.sendspace.com/file/r2y1cu

**Comment by Diego-T** [comment]
I was getting the same warning for razor files in Visual Studio and CLI build.  `dotnet --info` also showed version 6.0.102 SDK.  
Initially I installed it from Windows Update but after downloading and installing the SDK manually, the warning was gone.

Before reinstalling, when I used the "Go to definition" command over `Model`, I saw it still had the nullable annotation,  `public TModel? Model { get; }`, but not after.  I'm hoping that helps with the diagnostic.

**Comment by pranavkm** [comment]
Thanks @Diego-T. Looking at the build logs, it looks like it's compiling against the right assembly. Could you try installing the SDK from https://dotnet.microsoft.com/en-us/download/dotnet/6.0? It would help narrow down if this is a setup / installer issue.

**Comment by Diego-T** [comment]
@pranavkm That's what I did, I installed the SDK from that link and the warning was cleared.
That compilation log is not mine though.

**Comment by dotnetshadow** [comment]
> Thanks @Diego-T. Looking at the build logs, it looks like it's compiling against the right assembly. Could you try installing the SDK from https://dotnet.microsoft.com/en-us/download/dotnet/6.0? It would help narrow down if this is a setup / installer issue.

I did install from dot.net
![image](https://user-images.githubusercontent.com/296247/153121972-fadfbd65-9e2c-4a52-a92d-9ac19de4a1fb.png)

I will try to reinstall again

**Comment by dotnetshadow** [comment]
> I was getting the same warning for razor files in Visual Studio and CLI build. `dotnet --info` also showed version 6.0.102 SDK. Initially I installed it from Windows Update but after downloading and installing the SDK manually, the warning was gone.
> 
> Before reinstalling, when I used the "Go to definition" command over `Model`, I saw it still had the nullable annotation:
> 
> ```cs
> public TModel? Model { get; }
> ```
> 
> , but not after. I'm hoping that helps with the diagnostic.

Hi @Diego-T Did you try compiling with the following? I initially didn't have the error but that's because `dotnet build` didn't try to rebuild properly
```dotnet build --no-incremental``

**Comment by Diego-T** [comment]
@dotnetshadow I just tried with that flag `--no-incremental` and I don't get the warning.  I can no longer reproduce the issue.

**Comment by dotnetshadow** [comment]
> @dotnetshadow I just tried with that flag `--no-incremental` and I don't get the warning. I can no longer reproduce the issue.

Thanks @Diego-T. I just reinstalled **dotnet-sdk-6.0.102-win-x64.exe** seems to work now. Could of been a point in time thing. I rebooted and looks to be working now thanks for all your help guys

**Comment by dotnetshadow** [comment]
Just a note, I did notice the following peculiar issue.

Say you have as your model
```cshtml
// Index.cshtml
@model Person
 ```

Then later in the page you might have the following
````.cshtml
// Index.cshtml
<p>@Model?.Age</p><-- notice the ? here (even if it's by accident)
<p>@Model.Age</p> <--- causes  Warning (active)	CS8602	Dereference of a possibly null reference.	
````

**Comment by pranavkm** [comment]
@dotnetshadow that's a behavior for the C# compiler and works the same in regular C# code. You could follow up at https://github.com/dotnet/roslyn if you'd like further clarification.
