### ISSUE TITLE
Blazor Server - Windows Authentication Type is not built/initialized during project creation

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#38360]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-Server---Windows-Authentication-T/1571711)._

---
Hello,

I am using Microsoft Visual Studio Community 2022 RC (64-bit) Version 17.0.0 RC3.
I made the following selection during the project creation steps.

! [image.png] (https://aka.ms/dc/image?name=Bf11437368db74bdf969ddc8f791182ae637716098300019895_20211104-090347-image.png&tid=f11437368db74bdf969ddc8f791182ae637716098300019895)

When running the project, there is nowhere the possibility to login.
The LoginDisplay.razor component is not used at all.
There is an issue during the creation process to define the right coding/setup information for a windows Authentication type for a Blazor Server project.

! [image.png] (https://aka.ms/dc/image?name=Ba44898c9c270466fbb9b995de57506af637716100866818212_20211104-090805-image.png&tid=a44898c9c270466fbb9b995de57506af637716100866818212)

Please fix that issue during the project generation process.

---
#### Feedback Bot on 11/4/2021, 06:03 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/4/2021, 11:54 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### marc.bogais on 11/11/2021, 09:52 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
@Tratcher was this fixed in 6.0 RTM ?

**Comment by Tratcher** [comment]
@mkArtakMSFT this looks different from the prior issue (no windows auth configured for Kestrel). Their complaint is that there is no login/user button at all. You'll have to repro it and see if it's fixed.

**Comment by boukenka** [comment]
@mkArtakMSFT @Tratcher I have tested it with the most recent version of VS.
It is not fixed. 
When running Version 17.1.0 Preview 1.0 and without IIS Express, here is the result. 
Nothing is displayed.

![image](https://user-images.githubusercontent.com/16502423/141854649-413a294f-e522-4e57-8359-efc8bbf90da9.png)
![image](https://user-images.githubusercontent.com/16502423/141854938-3c1da2d6-77c7-4791-9529-268821e3f375.png)

**Comment by javiercn** [comment]
@boukenka If I understood correctly, are you complaining about the user not being displayed on the template?

**Comment by boukenka** [comment]
I am complaining this is working with IIS and it is not working when not running with IIS. It is normal ?

![image](https://user-images.githubusercontent.com/16502423/142019850-0ba74a19-d890-4274-982a-c2f247e749bf.png)

**Comment by CommonLoon102** [comment]
I was able to make Windows Authentication work under Kestrel by using this workaround:
https://stackoverflow.com/questions/59111331/windows-authentication-works-on-iis-but-not-kestrel-microsoft-aspnetcore-authe/59145415#59145415

Don't forget to put the middleware to the correct place:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-6.0#middleware-order

**Comment by boukenka** [comment]
@CommonLoon102 Thank you for the tips.

@mkArtakMSFT Is there any update?

**Comment by mkArtakMSFT** [comment]
We are unable to repro this. Can someone please share a minimal repro project for us to try out?

**Comment by CommonLoon102** [comment]
> We are unable to repro this. Can someone please share a minimal repro project for us to try out?

It is very simple to repro:
1. Update VS 2022 to the latest version
2. Create a new project
3. Select Blazor Server
4. Select `Windows` for authentication type
5. Click Play
6. All I see is a white page with nothing on it
7. If I select IIS Express next to the Play button and click Play, then the website works

I used Firefox 106.0.2 on Windows 7 to reproduce.

There are screenshots from one year ago in this issue about everything.
If you change the play button to IIS Express, it is going to work. Like as you can see it on the screenshots.

**Comment by CommonLoon102** [comment]
I've tried to reproduce this on a Windows 10 machine with MSEdge on it. I couldn't.

**Comment by danroth27** [comment]
Thanks @CommonLoon102  for providing these additional details. Given that this appears to be an issue with an out of support version of Windows, there doesn't appear to be anything to do in Blazor here.
