### ISSUE TITLE
Error retrieving the current token in a Blazor application after successful authentication in Azure B2C with Msal

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#39311]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Error-retrieving-the-current-token-in-a-/1581366)._

---
I have created a Blazor application and I use Msal to do authentication following the examples from Azure B2C.
With my B2C configuration in the server, I can successfully login, I get the User, the claims and I can call the api.
I would need to have access to the token during development to be able to use that token to call my api services directly using swagger. So during Debugging I wanted to print the token on screen to copy and paste.

However, when I try to get the token in the Client after successful login, I get an Exception:
`An exception occurred executing JS interop: The JSON value could not be converted to System.DateTimeOffset. Path: $.token.expires`

This is a very confusing exception and doesn't seem to explain the type of error that is occurring. It seems that is not doing any validation during the parsing or pre-parsing. So not sure why this is happening.

More details:

**I initialise with this:**
            
```
builder. Services.AddMsalAuthentication(options =>
            {
                builder. Configuration.Bind("AzureAdB2C", options. ProviderOptions.Authentication);

//options. ProviderOptions.DefaultAccessTokenScopes.Add("02200220-20202-2020-2020-202020200202002"); // I tried to put the application Id a per documentation and it doesn't work

options. ProviderOptions.DefaultAccessTokenScopes.Add("openid");
                options. ProviderOptions.DefaultAccessTokenScopes.Add("offline_access");

// request scope to access the API
                options. ProviderOptions.AdditionalScopesToConsent.Add("https://myb2c.onmicrosoft.com/whateverApp/MyAPI");

options. ProviderOptions.LoginMode = "redirect";
            });
```

I also use a custom AuthorizationMessageHandler to be able to call the api, which works well.

However, when in my code I call the code to retrieve the Token, I get the exception + one unhandled exception:
```
[Inject]
public IAccessTokenProvider TokenProvider { get; set; }
...
var accessTokenResult = await TokenProvider.RequestAccessToken(); // <-- This throws exception
```

**And additionally there is an unhandled exception:**

```
Unhandled Exception:
System.Text.Json.JsonException: Invalid JSON
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.EndInvokeJS(JSRuntime jsRuntime, String arguments)
   at Microsoft.AspNetCore.Components.WebAssembly.Services.DefaultWebAssemblyJSRuntime.<>c.<EndInvokeJS> b__7_0(String argsJson)
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyCallQueue.Schedule[String](String state, Action`1 callback)
   at Microsoft.AspNetCore.Components.WebAssembly.Services.DefaultWebAssemblyJSRuntime.EndInvokeJS(String argsJson)
Uncaught Error: System.Text.Json.JsonException: Invalid JSONThe thread 0x1b444 has exited with code 0 (0x0).
```

I have tried in B2C to set the configuration, and I'm able to run the SignIn flow redirecting to jwt.ms passing the token and decoding it.

![image.png](https://aka.ms/dc/image?name=B61fe0ca32d5041f0acecb62eae0a3aa2637722914961548223_20211112-162455-image.png&tid=61fe0ca32d5041f0acecb62eae0a3aa2637722914961548223)

And I get the token decoded when redirecting directly to jwt.ms:

![image.png](https://aka.ms/dc/image?name=B3cf703b86356424eb56cb33bbf305263637722919619353128_20211112-163240-image.png&tid=3cf703b86356424eb56cb33bbf305263637722919619353128)

---
#### Feedback Bot on 11/12/2021, 00:15 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is already fixed as part of #38962

**Comment by TanayParikh** [comment]
Please note, the fix for this issue should be available in the 6.0.2 patch release.

**Comment by rmencia-isv** [comment]
Any estimates on this?
I've got this installed 6.0.200-preview.21617.4 and still not working

**Comment by TanayParikh** [comment]
The fix for the underlying `System.Text.Json.JsonException: Invalid JSON` exception was backported through https://github.com/dotnet/aspnetcore/pull/39075.

@rmencia-isv could you please try this out using the latest installer available at https://github.com/dotnet/installer. Please let us know if you're still having the issue with that, and please provide the exact version of the dotnet sdk being used, along side the exact exception message you're getting.

**Comment by rmencia-isv** [comment]
I have installed the latest versionfrom the url you provided (dotnet-sdk-6.0.200-preview.22068.4-win-x64.exe) and I still get the same error in Blazor wasm client app.

Checking the list I have this one installed (6.0.200-preview.22068.4)
However, by looking at the call stack I see references to Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.1.0*

**The error Message:**
An exception occurred executing JS interop: The JSON value could not be converted to System.DateTimeOffset. Path: $.token.expires | LineNumber: 0 | BytePositionInLine: 73.. See InnerException for more details.

**InnerException:**
at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)   
at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.InternalAccessTokenResult, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)   
at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.InternalAccessTokenResult, **Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.1.0**, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)   
at System.Text.Json.JsonSerializer.ReadCore[Object](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)   
at System.Text.Json.JsonSerializer.Read[Object](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo)   
at System.Text.Json.JsonSerializer.Deserialize(Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)   
at Microsoft.JSInterop.JSRuntime.EndInvokeJS(Int64 taskId, Boolean succeeded, Utf8JsonReader& jsonReader)'

**Comment by TanayParikh** [comment]
> by looking at the call stack I see references to Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.1.0*

Ah that's definitely a bit strange. Could you please double check your csproj files to ensure you don't have any hardcoded versions which may be causing this issue? Also, if you could try adding the following to your nuget config:

```xml
<add key="dotnet6" value="https://dnceng.pkgs.visualstudio.com/public/_packaging/dotnet6/nuget/v3/index.json" />
```

Further details [here](https://github.com/dotnet/runtime/blob/main/docs/project/dogfooding.md#nightly-builds-table).

**Comment by rmencia-isv** [comment]
This is what I have in the project file.
I also added the nuget in VS to get the packages from that place and no new updates available, even pre-release for any of those packages.

![image](https://user-images.githubusercontent.com/82075665/150065821-a675b32d-bc8f-404c-9c08-e3e9ac34a504.png)

![image](https://user-images.githubusercontent.com/82075665/150065567-c0f1dc7c-93b9-4216-9d12-da8d9fc404ae.png)

**Comment by TanayParikh** [comment]
Hey @rmencia-isv, I took a look at the feeds and you're right the 6.0.2 (prerelease) packages aren't up yet. You can either try waiting for the official 6.0.2 release (mid February), or try the 7.0 alpha packages (not sure if they'll be updated yet though).

**Comment by rmencia-isv** [comment]
Thanks Tanay for getting back to me. It's unfortunate that the packages are not uploaded yet, as I've seen a number of issues fixed.
I'll probably wait for the release next month, if the pre release packages are not updated.

**Comment by kbeaugrand** [comment]
Hi, @TanayParikh ,

I'm facing the same issue. Unfortunately I cannot wit until mid February. 
Is there any chance to test the 6.0.2 (prerelease) you mentioned. 

This is definitively not present on the repo you suggested...

**Comment by TanayParikh** [comment]
Hello @kbeaugrand, to test out the pre-release you can try using the nightly SDK & packages as above, or by using the 7.0 alpha/beta packages. 


SDK Download: https://github.com/dotnet/installer (ensure you get the 6.0.2 or 7 alpha/beta SDK)

Add to your Nuget config:

```xml
<add key="dotnet6" value="https://dnceng.pkgs.visualstudio.com/public/_packaging/dotnet6/nuget/v3/index.json" />
```

Further details [here](https://github.com/dotnet/runtime/blob/main/docs/project/dogfooding.md#nightly-builds-table).

**Comment by Pete-Nago** [comment]
I also am having the exact same issue with B2C and Blazor WASM.
Hope they release the fix soon.
I'm hesitant to install preview builds.

**Comment by kbeaugrand** [comment]
Hi @TanayParikh, 

Do you have a more precise date for the release of  Microsoft.AspNetCore.Components.WebAssembly.Authentication v6.0.2 ? 

Thank you.

**Comment by TanayParikh** [comment]
> Hi @TanayParikh,
> 
> Do you have a more precise date for the release of Microsoft.AspNetCore.Components.WebAssembly.Authentication v6.0.2 ?
> 
> Thank you.

It was just released earlier today!

**Comment by kbeaugrand** [comment]
> > Hi @TanayParikh,
> > Do you have a more precise date for the release of Microsoft.AspNetCore.Components.WebAssembly.Authentication v6.0.2 ?
> > Thank you.
> 
> It was just released earlier today!

Thank you for your answer. 
I checked it, but unfortunately I'm still facing the issue... ;(

**Comment by TanayParikh** [comment]
> unfortunately I'm still facing the issue

To confirm you've updated the SDK/.csproj to utilize the new 6.0.2 packages, correct? What exact error message are you seeing?

Can you please provide a minimal, public, github repro which reproduces this issue?

**Comment by kbeaugrand** [comment]
> > unfortunately I'm still facing the issue
> 
> To confirm you've updated the SDK/.csproj to utilize the new 6.0.2 packages, correct? What exact error message are you seeing?
> 
> Can you please provide a minimal, public, github repro which reproduces this issue?

Hi, 

Yes I confirm that I updated my package to 6.0.2 ([https://github.com/CGI-FR/IoT-Hub-Portal/blob/main/src/AzureIoTHub.Portal/Client/AzureIoTHub.Portal.Client.csproj](https://github.com/CGI-FR/IoT-Hub-Portal/blob/main/src/AzureIoTHub.Portal/Client/AzureIoTHub.Portal.Client.csproj)). 
I'm using OpenID connect. 

You can find a public repos (not minimal) with my configuration here: [https://github.com/CGI-FR/IoT-Hub-Portal/](https://github.com/CGI-FR/IoT-Hub-Portal/).

For the code sample, that is relevant, you can find at client Program.cs file the executed configuration: [https://github.com/CGI-FR/IoT-Hub-Portal/blob/main/src/AzureIoTHub.Portal/Client/Program.cs](https://github.com/CGI-FR/IoT-Hub-Portal/blob/main/src/AzureIoTHub.Portal/Client/Program.cs).

The error message obtained is: 
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: An exception occurred executing JS interop: The JSON value could not be converted to System.DateTimeOffset. Path: $.token.expires | LineNumber: 0 | BytePositionInLine: 170.. See InnerException for more details.
Microsoft.JSInterop.JSException: An exception occurred executing JS interop: The JSON value could not be converted to System.DateTimeOffset. Path: $.token.expires | LineNumber: 0 | BytePositionInLine: 170.. See InnerException for more details.
 ---> System.Text.Json.JsonException: The JSON value could not be converted to System.DateTimeOffset. Path: $.token.expires | LineNumber: 0 | BytePositionInLine: 170.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'Null' as a string.
   at System.Text.Json.Utf8JsonReader.TryGetDateTimeOffset(DateTimeOffset& value)
   at System.Text.Json.Utf8JsonReader.GetDateTimeOffset()
   at System.Text.Json.Serialization.Converters.DateTimeOffsetConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1[[System.DateTimeOffset, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.AccessToken, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, AccessToken& value)
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.AccessToken, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, AccessToken& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.AccessToken, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.InternalAccessTokenResult, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, InternalAccessTokenResult& value)
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.InternalAccessTokenResult, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, InternalAccessTokenResult& value)
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.InternalAccessTokenResult, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.InternalAccessTokenResult, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.InternalAccessTokenResult, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[Object](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.Read[Object](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize(Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at Microsoft.JSInterop.JSRuntime.EndInvokeJS(Int64 taskId, Boolean succeeded, Utf8JsonReader& jsonReader)
   --- End of inner exception stack trace ---
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.InternalAccessTokenResult, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService`3.<RequestAccessToken>d__22[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteUserAccount, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.AspNetCore.Components.WebAssembly.Authentication.OidcProviderOptions, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.AuthorizationMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.<GetFromJsonAsyncCore>d__13`1[[AzureIoTHub.Portal.Shared.Models.Device.DeviceListItem[], AzureIoTHub.Portal.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at AzureIoTHub.Portal.Client.Pages.Devices.DeviceListPage.LoadDevices() in C:\Users\beaugrandk\Source\Repos\CGI-FR\IoT-Hub-Portal\src\AzureIoTHub.Portal\Client\Pages\Devices\DeviceListPage.razor:line 179
   at AzureIoTHub.Portal.Client.Pages.Devices.DeviceListPage.OnInitializedAsync() in C:\Users\beaugrandk\Source\Repos\CGI-FR\IoT-Hub-Portal\src\AzureIoTHub.Portal\Client\Pages\Devices\DeviceListPage.razor:line 163
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
window.Module.s.printErr @ blazor.webassembly.js:1```

**Comment by TanayParikh** [comment]
> I may be able to reproduce the issue on a minimal project if needed.

Yes please, that'd be much appreciated!

Thanks for the stack trace. I see the underlying `System.Text.Json.JsonException: Invalid JSON` is resolved (via backported https://github.com/dotnet/aspnetcore/pull/39075), but we still have the 

```
Microsoft.JSInterop.JSException: An exception occurred executing JS interop: The JSON value could not be converted to System.DateTimeOffset. Path: $.token.expires | LineNumber: 0 | BytePositionInLine: 170.. See InnerException for more details.
 ---> System.Text.Json.JsonException: The JSON value could not be converted to System.DateTimeOffset. Path: $.token.expires | LineNumber: 0 | BytePositionInLine: 170.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'Null' as a string.
```

error. Re-opening this issue.

**Comment by kbeaugrand** [comment]
> > I may be able to reproduce the issue on a minimal project if needed.
> 
> Yes please, that'd be much appreciated!
> 
> Thanks for the stack trace. I see the underlying `System.Text.Json.JsonException: Invalid JSON` is resolved (via backported #39075), but we still have the
> 
> ```
> Microsoft.JSInterop.JSException: An exception occurred executing JS interop: The JSON value could not be converted to System.DateTimeOffset. Path: $.token.expires | LineNumber: 0 | BytePositionInLine: 170.. See InnerException for more details.
>  ---> System.Text.Json.JsonException: The JSON value could not be converted to System.DateTimeOffset. Path: $.token.expires | LineNumber: 0 | BytePositionInLine: 170.
>  ---> System.InvalidOperationException: Cannot get the value of a token type 'Null' as a string.
> ```
> 
> error. Re-opening this issue.

I'll send you the sample app ass soon I've pushed on a public repos.

**Comment by syska** [comment]
I was so happy when I saw this should have been fixed.

Guess I will have to wait a little more with the auth implementation.

**Comment by kbeaugrand** [comment]
Hi @mkArtakMSFT @TanayParikh , 

I saw that nothing changed here (and I forget to push the sample repository). 

This is available here[https://github.com/kbeaugrand/SampleOpenIDConnect](https://github.com/kbeaugrand/SampleOpenIDConnect)

I'm using Okta identity provider, the settings are present at Program.cs#L16-21

**Comment by TanayParikh** [comment]
> This is available herehttps://github.com/kbeaugrand/SampleOpenIDConnect

Hi @kbeaugrand, could you please confirm the Repo is still available and is **public**? I'm getting a 404 when I try to access that URL.

**Comment by kbeaugrand** [comment]
My bad, it was private. Now it should be ok

**Comment by TanayParikh** [comment]
Thanks. Looks like it's an issue with the deserialization of the `DateTimeOffset` of the `AccessToken` here:

https://github.com/dotnet/aspnetcore/blob/ce10dcaa31b254bda5dcf854f5578f78418d412c/src/Components/WebAssembly/WebAssembly.Authentication/src/Models/AccessToken.cs#L16-L19

which is a part of 

https://github.com/dotnet/aspnetcore/blob/ce10dcaa31b254bda5dcf854f5578f78418d412c/src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs#L246-L252

which gets called here:

https://github.com/dotnet/aspnetcore/blob/24280d974f0624002f963ef8607afe749f9d1b3e/src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs#L151

**Comment by TanayParikh** [comment]
Related: https://stackoverflow.com/a/68565455/17995448

**Comment by TanayParikh** [comment]
Based on https://docs.microsoft.com/dotnet/standard/datetime/system-text-json-support we may be dealing with non compliant `DateTimeOffset` values.

> Attempting to read non-compliant formats with [Utf8JsonReader](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonreader) will cause it to throw a [FormatException](https://docs.microsoft.com/en-us/dotnet/api/system.formatexception):

> // Unhandled exception. System.FormatException: The JSON value is not in a supported DateTime format.

@kbeaugrand can you please confirm what needs to be done to trigger the exception you're seeing, using the repro you provided? I just end up with an Okta 404 when I try to run your project.

**Comment by kbeaugrand** [comment]
@TanayParikh, 

After configuring the OIDC settings for your tenant, and launching the project with Visual Studio, go to [https://localhost:7002/fetchdata](https://localhost:7002/fetchdata), you will have the issue present on log from the broswser developper console.

**Comment by kbeaugrand** [comment]
> Thanks. Looks like it's an issue with the deserialization of the `DateTimeOffset` of the `AccessToken` here:
> 
> https://github.com/dotnet/aspnetcore/blob/ce10dcaa31b254bda5dcf854f5578f78418d412c/src/Components/WebAssembly/WebAssembly.Authentication/src/Models/AccessToken.cs#L16-L19
> 
> which is a part of
> 
> https://github.com/dotnet/aspnetcore/blob/ce10dcaa31b254bda5dcf854f5578f78418d412c/src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs#L246-L252
> 
> which gets called here:
> 
> https://github.com/dotnet/aspnetcore/blob/24280d974f0624002f963ef8607afe749f9d1b3e/src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs#L151
> 
> on the client side, this translates to:
> 
> https://github.com/dotnet/aspnetcore/blob/24280d974f0624002f963ef8607afe749f9d1b3e/src/Components/WebAssembly/Authentication.Msal/src/Interop/AuthenticationService.ts#L111-L123
> 
> which doesn't define `AccessToken.Expires`, which may be why the deserialization is failing.
> 
> For the non-MSAL case:
> 
> on the client side, this translates to:
> 
> https://github.com/dotnet/aspnetcore/blob/24280d974f0624002f963ef8607afe749f9d1b3e/src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts#L98-L130
> 
> which gets the `Expires` via:
> 
> https://github.com/dotnet/aspnetcore/blob/24280d974f0624002f963ef8607afe749f9d1b3e/src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts#L136-L140
> 
> Based on this, does `Expires` really need to be a `DateTimeOffset` vs. `DateTime`? cc/ @javiercn

I think this doesn't comes from the deserialization of the ``access_token``. 
In my configuration I only get the ID Token from the IDP. The issue occurs while getting the access token. at that time I have no network requests from the browser...

**Comment by syska** [comment]
From the Blazor WASM when calling `var tokenRequest = await TokenProvider.RequestAccessToken();` i get the following error:

```
 blazor.webassembly.js:1 
        
       crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: An exception occurred executing JS interop: The JSON value could not be converted to System.DateTimeOffset. Path: $.token.expires | LineNumber: 0 | BytePositionInLine: 73.. See InnerException for more details.
Microsoft.JSInterop.JSException: An exception occurred executing JS interop: The JSON value could not be converted to System.DateTimeOffset. Path: $.token.expires | LineNumber: 0 | BytePositionInLine: 73.. See InnerException for more details.
 ---> System.Text.Json.JsonException: The JSON value could not be converted to System.DateTimeOffset. Path: $.token.expires | LineNumber: 0 | BytePositionInLine: 73.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'Null' as a string.
   at System.Text.Json.Utf8JsonReader.TryGetDateTimeOffset(DateTimeOffset& value)
   at System.Text.Json.Utf8JsonReader.GetDateTimeOffset()
   at System.Text.Json.Serialization.Converters.DateTimeOffsetConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1[[System.DateTimeOffset, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.AccessToken, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, AccessToken& value)
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.AccessToken, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, AccessToken& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.AccessToken, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.InternalAccessTokenResult, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, InternalAccessTokenResult& value)
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.InternalAccessTokenResult, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, InternalAccessTokenResult& value)
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.InternalAccessTokenResult, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.InternalAccessTokenResult, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.InternalAccessTokenResult, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[Object](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.Read[Object](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize(Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at Microsoft.JSInterop.JSRuntime.EndInvokeJS(Int64 taskId, Boolean succeeded, Utf8JsonReader& jsonReader)
   --- End of inner exception stack trace ---
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.InternalAccessTokenResult, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService`3.<RequestAccessToken>d__22[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteUserAccount, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.Authentication.WebAssembly.Msal.Models.MsalProviderOptions, Microsoft.Authentication.WebAssembly.Msal, Version=6.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at BforBoat.Web.Pages.Profile.OnInitializedAsync() in C:\Projects\vsts\mikaelsyska\bforboat\src\BforBoat.Web\Pages\Profile.razor.cs:line 29
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

![image](https://user-images.githubusercontent.com/317770/162069553-6cc18cf5-562f-4e30-a04c-688a7fbee315.png)

This is the response returned from Azure B2C ...

**Comment by abbasl7** [comment]
Do we have any known workaround to handle this issue till it is officially fixed?

**Comment by kbeaugrand** [comment]
> 

Unfortunatly not at this time... ;(

**Comment by kbeaugrand** [comment]
> Do we have any known workaround to handle this issue till it is officially fixed?

Unfortunatly not at this time... ;(

**Comment by SariDev** [comment]
I'm affected by this issue too.

Would be nice if this could be scheduled into one of the next releases.

**Comment by dougclutter** [comment]
Using 6.0.4 and I'm affected by this issue too.  Any timeline on a fix?

**Comment by andrewwilkin** [comment]
The symptoms I'm getting is after being redirected back from Azure AD B2C, I can see the token being sent, from login-callback the app then moves to login-fail.

Yet the app then seems to then try refreshing a couple of times.

Some of the API calls work then it falls over on the third one with a 401.

Is this a symptom of the same issue?

**Comment by kbeaugrand** [comment]
@mkArtakMSFT @TanayParikh any update ?

**Comment by javiercn** [comment]
@kbeaugrand we are looking into it, but it seems the issue happens when the app is not requesting an access token.

**Comment by kbeaugrand** [comment]
> @kbeaugrand we are looking into it, but it seems the issue happens when the app is not requesting an access token.

Thank you @javiercn, Is there a workaround ?

**Comment by javiercn** [comment]
@kbeaugrand You can likely avoid this issue if you request an access token for the app.

Alternatively you can provide your own JS based on https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebAssembly/Authentication.Msal/src/Interop/AuthenticationService.ts and adapt it to your needs.

**Comment by kbeaugrand** [comment]
@javiercn , 

The first option suggest to use Hybrid flow (using token response type) right ? 
Otherwise, since we have the authorization code on the WebAssembly, you suggest to request ourselves the access token ? 

To clarify that, I guess that this should be the responsibility of the TokenProvider to do correctly the second option, right ?

**Comment by SariDev** [comment]
@javiercn 
regarding your workaround suggestions:

> You can likely avoid this issue if you request an access token for the app.

In a Blazor Web Assembly applicaton based on .NET 6.0.4 I try to request a access token like this and it throws a exception as mentioned by @syska 

```c#
var accessTokenResult = await _tokenProvider.RequestAccessToken(); // <-- This throws exception
```
_tokenProvider is of type Microsoft.AspNetCore.Components.WebAssembly.Authentication.IAccessTokenProvider

```
Unhandled exception rendering component: An exception occurred executing JS interop: The JSON value could not be converted to System.DateTimeOffset. Path: $.token.expires | LineNumber: 0 | BytePositionInLine: 73.. See InnerException for more details.
Microsoft.JSInterop.JSException: An exception occurred executing JS interop: The JSON value could not be converted to System.DateTimeOffset. Path: $.token.expires | LineNumber: 0 | BytePositionInLine: 73.. See InnerException for more details.
 ---> System.Text.Json.JsonException: The JSON value could not be converted to System.DateTimeOffset. Path: $.token.expires | LineNumber: 0 | BytePositionInLine: 73.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'Null' as a string.
   at System.Text.Json.Utf8JsonReader.TryGetDateTimeOffset(DateTimeOffset& value)
   at System.Text.Json.Utf8JsonReader.GetDateTimeOffset()
   at System.Text.Json.Serialization.Converters.DateTimeOffsetConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1[[System.DateTimeOffset, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.AccessToken, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, AccessToken& value)
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.AccessToken, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, AccessToken& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.AccessToken, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.InternalAccessTokenResult, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, InternalAccessTokenResult& value)
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.InternalAccessTokenResult, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, InternalAccessTokenResult& value)
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.InternalAccessTokenResult, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.InternalAccessTokenResult, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.InternalAccessTokenResult, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[Object](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.Read[Object](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize(Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at Microsoft.JSInterop.JSRuntime.EndInvokeJS(Int64 taskId, Boolean succeeded, Utf8JsonReader& jsonReader)
   --- End of inner exception stack trace ---
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.InternalAccessTokenResult, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService`3.<RequestAccessToken>d__22[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteUserAccount, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=6.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.Authentication.WebAssembly.Msal.Models.MsalProviderOptions, Microsoft.Authentication.WebAssembly.Msal, Version=6.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at SariDev.LetsEat.LetsEat.App.Shared.MainLayout.GetAllAsync() in C:\WS_Private\GitHub\SariDev\LetsEat\Code\Applications\LetsEat\LetsEat.App\Shared\MainLayout.razor:line 50
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at MudBlazor.MudBaseButton.OnClickHandler(MouseEventArgs ev)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

Or do you mean to retrieve the access token in another way?
Can you clarify that a bit?


---

Regarding 

> Alternatively you can provide your own JS based on https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebAssembly/Authentication.Msal/src/Interop/AuthenticationService.ts and adapt it to your needs.

Has anyone here tried that and had success with it?

**Comment by kbeaugrand** [comment]
@SariDev unfortunately I didn't understand correctly what is expected to be the correct solution. The suggested workaround doesn't seem clear for me.
Furthermore, I cannot understand why this issue is taking so much time since it's a blocking point for integrating Blazor WebAssembly with OpenID Connect...

**Comment by SariDev** [comment]
@kbeaugrand same for me.

Maybe someone can clarify how those workarounds should be implemented with more details.

> Furthermore, I cannot understand why this issue is taking so much time since it's a blocking point for integrating Blazor WebAssembly with OpenID Connect..

I'm also suprises by this.
One would expect that this is a heavily requested Feature and that it should work without issues

**Comment by javiercn** [comment]
@kbeaugrand here is a sample that shows how you can customize the JS we provide. It uses MSAL, but the steps are equivalent for OpenID Connect.

 https://github.com/javiercn/BlazorWasmMsalSample

**Comment by andrewwilkin** [comment]
Looking at the sample:
`interface AccessToken {
    value: string;
    expires: Date | null;
    grantedScopes: string[];
}`

I presume from the error previously that the AccessToken has null expiry and thus cannot be converted to the DateTimeOffset by the serializer:
```An exception occurred executing JS interop: The JSON value could not be converted to System.DateTimeOffset. Path: $.token.expires | LineNumber: 0 | BytePositionInLine: 73.. See InnerException for more details.
Microsoft.JSInterop.JSException: An exception occurred executing JS interop: The JSON value could not be converted to System.DateTimeOffset. Path: $.token.expires | LineNumber: 0 | BytePositionInLine: 73.. See InnerException for more details.
 ---> System.Text.Json.JsonException: The JSON value could not be converted to System.DateTimeOffset. Path: $.token.expires | LineNumber: 0 | BytePositionInLine: 73.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'Null' as a string.`

Maybe it is line 164/165:
`            const result = await this.signInCore(request);
            if (!result) {
                return this.redirect();
            } else if (this.isMsalError(result)) {
                return this.error(result.errorMessage);
            }`

If the result contains something then it won't make the call on line 166. Not tried debugging it yet, thoughts?

**Comment by Spaceman1861** [comment]
If it helps anyone where is how I implemented a work around for this.

I needed to get the token to pass it to my API.

I added this to the index.html

    <script>
        window.getJWT = () => JSON.parse(sessionStorage[
            Object
                .keys(sessionStorage)
                .find(_ => _.includes("yourdomain.b2clogin.com-idtoken"))
            ])
            .secret;
    </script>

Then commented out the recommended message handler:

    builder.Services.AddHttpClient(
        "WebAPI",
        (services,client) => {
            client.BaseAddress = new Uri("http://localhost:7071");
        }
    );
    // COMMENT THIS OUT
    //.AddHttpMessageHandler<CustomAuthorizationMessageHandler>();

Then when you use the Httpclient manually add it:

    builder
        .Services
        .AddScoped(sp => sp.GetRequiredService<IHttpClientFactory>()
        .CreateClient("WebAPI"));


        [Inject]
        protected HttpClient? Http { get; set; }

        [Inject]
        protected IJSRuntime JS { get; set; }

        protected override async Task OnInitializedAsync()
        {
            if (Http == null)
                throw new ArgumentNullException(nameof(Http));

            if (JS == null)
                throw new ArgumentNullException(nameof(JS));

            var text = await JS.InvokeAsync<string>("getJWT", new object[] { });

            Http.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(
                "Bearer",
                text
            );

            using var stream = await Http.GetAsync("http://localhost:7071/api/Function1");

        }

Its pretty janky but works for me until they roll out a fix :).

**Comment by kbeaugrand** [comment]
> 

@Spaceman1861, this would add the id_token in the Authorization header, right ? 
In that case, I guess the authentication should not pass to the backend since this is not the access_token for your backend audience...

**Comment by Spaceman1861** [comment]
Perhaps I'm looking at it wrong @kbeaugrand  ill walk you through the train of though if you think I have it wrong id love to know: 

- User logins in via blazor front end.
- Token stored in session in browser.
- User needs to access separate function app backend and must be Authenticated.
- Passing the JWT as bearer from the session and then validating it in the function app allows with code like this.



        public static async Task<JwtSecurityToken> ValidateAsync(string token)
        {
            string stsDiscoveryEndpoint = "https://YOURSITEHERE.b2clogin.com/YOURSITEHERE.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1_Auth";
            var configManager = new ConfigurationManager<OpenIdConnectConfiguration>(stsDiscoveryEndpoint, new OpenIdConnectConfigurationRetriever()); 
            
            //1. need the 'new OpenIdConnect...'
            OpenIdConnectConfiguration config = await configManager.GetConfigurationAsync();
            TokenValidationParameters validationParameters = new TokenValidationParameters
            {
                //decode the JWT to see what these values should be
                ValidAudience = "SOMEGUID",  // Replaced values by XXXX
                IssuerSigningKeys = config.SigningKeys, //2. .NET Core equivalent is "IssuerSigningKeys" and "SigningKeys"
                ValidateIssuer = true,
                ValidIssuer = "https://YOURSITEHERE.b2clogin.com/SOMEGUID/v2.0/",
                ValidateAudience = true,
                ValidateIssuerSigningKey = true,
                RequireExpirationTime = true,
                ValidateLifetime = true
            };
            JwtSecurityTokenHandler tokendHandler = new JwtSecurityTokenHandler();
            SecurityToken jwt;
            var result = tokendHandler.ValidateToken(token, validationParameters, out jwt);
            return jwt as JwtSecurityToken;
        }

**Comment by kbeaugrand** [comment]
@Spaceman1861 

Can you print in the discussion, the tokens you have in the session storage (not the values, just the keys) ?
Maybe I miss understand the OAuth 2.0 (and OpenId protocol), but with the AspNetCore Assembly, I can only work with the id_token. 
To my standing point, my WebAssembly App should be considered as a client app, and should act to my API on behalf of the user. 
So my API refuse the id_token as the Bearer token because it has been issued for identification, not for authorization....

![image](https://user-images.githubusercontent.com/9513635/169996766-c51292a0-de0a-4c24-81a7-af156c788b5a.png)
Source: [https://auth0.com/blog/id-token-access-token-what-is-the-difference/](https://auth0.com/blog/id-token-access-token-what-is-the-difference/).

@javiercn, I cannot understand the decision to move the fix to this issue to .NET 7. 
What is the solution to use WebAssembly Authenticated (even in MSAL or OpenIdConnect) and provide the access token to the API part properly ? 

I have two issues : 
- When requesting only the id_token from the authorization endpoint, the process works, but while requesting the access_token, the application fails with the ``$.token.expires`` issue
- When requesting both id_token and token, the authentication fails, the browser tries 2 times to authenticate and redirects me to an error page (however the Identity provider sends correctly the id_token and access_token to the app).
![image](https://user-images.githubusercontent.com/9513635/169998086-02df0e97-b624-4594-b749-ea1484aba636.png)

**These two issues makes the Blazor WebAssembly not usable with an authenticated resource !**

**Comment by Spaceman1861** [comment]
An interesting article. 

I am indeed using the IdToken for Authentication.

From that article
> As said above, an ID token proves that a user has been authenticated. In a first-party scenario, i.e. in a scenario where the client and the API are both controlled by you, you may decide that your ID token is good to make authorization decisions: maybe all you need to know is the user identity.

>However, even in this scenario, the security of your application, consisting of the client and the API, may be at risk. In fact, there is no mechanism that ties the ID token to the client-API channel. If an attacker manages to steal your ID token, they can use it to call your API like a legitimate client.

For reference I have 3 tokens in my session

- Refresh
- Id Token
- some random one that seems to have information around the Id Token.

I assume this is the way i configured the B2C workflow to only return an Id Token.

This is adequate for my scenario for the time being.

**Comment by kbeaugrand** [comment]
I finally found what was going wrong. And if I'm right, this might had absolutely never work...

On the **AuthenticationService**, when requesting the AccessToken, it calls the  OIDC client to silent sign in. This will request the IdP and expects to have the `access_token `in the response. 
However, it takes in arguements the `response_type` provided by the application (by default : `id_token`). 
Since the IdP recieves the id_token `response_type`, it will only return the idToken, never the access token... 

To fix that I added the token in the arguments to pass to the `signinSilent` and MAGIC, it gets the access token, and everything was working (no other changes).

**Comment by kbeaugrand** [comment]
Nevermind, I got why getting the access token as part of the login doesn't work in my case...
In my case, I'm using OpenID connect with Azure AD B2C as the IdP.

AD B2C doesn't provide the user info endpoint and he oidc client used requires it ;(
It fails to perfom the sign in and validates the login but without any error message...

By changing the settings, I got my flow working (after disabling the loadUserInfo (see: https://github.com/IdentityModel/oidc-client-js/wiki#other-optional-settings)

After, that I can have my access token with the id_token.

**Comment by BlueKiwiEntertainment** [comment]
Guys fix this?

**Comment by ekuhlmann23** [comment]
@kbeaugrand Could you provide more details on the workaround, please?

**Comment by kbeaugrand** [comment]
@ekuhlmann23, 

I simply moved the settings to specify the authentication response type to ``code```.

e.g: 
```csharp
   _ = builder.Services.AddOidcAuthentication(options =>
            {
                ....
                options.ProviderOptions.ResponseType = "code";
            });
```

**Comment by Magik3a** [comment]
So, using new Blazor project with default B2C configuration is still erroring on the profile page.
So lets wait as the other guys on this :@ 
![image](https://user-images.githubusercontent.com/10474555/188006980-dddb4922-b584-4e77-9c5e-afb0d9ec7769.png)
![image](https://user-images.githubusercontent.com/10474555/188007050-e2ab3cc6-6d84-4135-8e7f-40053c72285a.png)

**Comment by javiercn** [comment]
We have made improvements to this scenario in .NET 7.0, the changes will be available in RC2.

It should be easier to diagnostic when there is an issue in the configuration of the app.

https://github.com/dotnet/aspnetcore/pull/43954
