### ISSUE TITLE
RazorRuntimeCompilation 6.0.5 incomaptible with Microsoft.CodeAnalysis.Common 4.2.0

### ISSUE THREAD

**Issue by dwgray** [dotnet/aspnetcore#42182]
### Description

I have a pretty vanilla asp.net core 6.0 application.  When attempting to update Microsoft.CodeAnalysis.Common from 4.0.1 to 4.2.0 I started getting a runtime error when calling IApplicationBuilder.UseEndpoints and MapControllerRoute. 

```System.TypeLoadException: 'Method 'CreateDeterministicKeyBuilder' in type 'Microsoft.CodeAnalysis.CSharp.CSharpCompilationOptions' from assembly 'Microsoft.CodeAnalysis.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.'```

Reverting to Microsoft.CodeAnalysis.Common 4.01 or commenting out the call to AddRazorRuntimeCompilation resolves the issue, but I'd like to be able to move to tip of all my nuget packages + still use runtime compilation for my razor pages (for development, I'm not using that in production).

### Configuration

.net 6.0.300
Windows 11 x64
RazorRuntimeCompilation 6.0.5 
Microsoft.CodeAnalysis.Common 4.2.0 (also reproduces in 4.1.0, but _not_ in 4.0.1

### Regression?

Appears to have regressed with Microsoft.CodeAnalysis.Common 4.1.0 (see configuration note above)

### Other information

User code where the 1st chance exception is seen:

```
 	Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.dll!Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.CSharpCompiler.ParseOptions.get()	Unknown
 	Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.dll!Microsoft.Extensions.DependencyInjection.RazorRuntimeCompilationMvcCoreBuilderExtensions.AddServices.AnonymousMethod__3(Microsoft.AspNetCore.Razor.Language.RazorProjectEngineBuilder builder)	Unknown
 	Microsoft.AspNetCore.Razor.Language.dll!Microsoft.AspNetCore.Razor.Language.RazorProjectEngine.Create(Microsoft.AspNetCore.Razor.Language.RazorConfiguration configuration, Microsoft.AspNetCore.Razor.Language.RazorProjectFileSystem fileSystem, System.Action<Microsoft.AspNetCore.Razor.Language.RazorProjectEngineBuilder> configure)	Unknown
 	Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.dll!Microsoft.Extensions.DependencyInjection.RazorRuntimeCompilationMvcCoreBuilderExtensions.AddServices.AnonymousMethod__2_2(System.IServiceProvider s)	Unknown

```

Callstack:

``` 	Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.dll!Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.CSharpCompiler.ParseOptions.get()	Unknown
 	Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.dll!Microsoft.Extensions.DependencyInjection.RazorRuntimeCompilationMvcCoreBuilderExtensions.AddServices.AnonymousMethod__3(Microsoft.AspNetCore.Razor.Language.RazorProjectEngineBuilder builder)	Unknown
 	Microsoft.AspNetCore.Razor.Language.dll!Microsoft.AspNetCore.Razor.Language.RazorProjectEngine.Create(Microsoft.AspNetCore.Razor.Language.RazorConfiguration configuration, Microsoft.AspNetCore.Razor.Language.RazorProjectFileSystem fileSystem, System.Action<Microsoft.AspNetCore.Razor.Language.RazorProjectEngineBuilder> configure)	Unknown
 	Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.dll!Microsoft.Extensions.DependencyInjection.RazorRuntimeCompilationMvcCoreBuilderExtensions.AddServices.AnonymousMethod__2_2(System.IServiceProvider s)	Unknown

```

**Comment by javiercn** [comment]
@dwgray thanks for contacting us.

@jaredpar isn't this something we recently addressed?

**Comment by danroth27** [comment]
@dwgray Specifically, we think this may have been fixed in 6.0.301, which was recently released.

**Comment by dwgray** [comment]
@danroth27 Sorry, still see the same behavior:

.net sdk: 6.0.301
RazorRuntimeCompilation 6.0.6
Microsoft.CodeAnalysis.Common 4.2.0

Same exception, same stack.

David

**Comment by MackinnonBuck** [comment]
I was able to reproduce this, but fixed it by using the following package versions:

Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation: 6.0.8
Microsoft.CodeAnalysis.Common: 4.2.0
Microsoft.CodeAnalysis.CSharp: 4.2.0

@dwgray it seems the issue may have been caused by the package version mismatch between Microsoft.CodeAnalysis.Common and Microsoft.CodeAnalysis.CSharp. Could you try the package versions listed above and verify that it resolves your issue?

**Comment by jaredpar** [comment]
>System.TypeLoadException: 'Method 'CreateDeterministicKeyBuilder' in type 'Microsoft.CodeAnalysis.CSharp.CSharpCompilationOptions' from assembly 'Microsoft.CodeAnalysis.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.'

This error can only realistically happen when `Microsoft.CodeAnalysis` and `Microsoft.CodeAnalysis.CSharp` are loaded with different versions. This is an `internal abstract` contract between the two assemblies and they are required to be loaded with the same version. Most likely cause is someone is pinning a version in the NuGet restore which leads to this assembly mismatch.

**Comment by dwgray** [comment]
Thanks @jaredpar and @MackinnonBuck - This was (partially) a user error on my part.  I was for no apparent reason explicitly including Microsoft.CodeAnalysis.Common: 4.2.0 (which even includes a warning not to ever explicitly include it message, as it was being pulled in via dependencies).  Explicitly including Microsoft.CodeAnalysis.CSharp: 4.2.0 fixed the problem  But more cleanly, just removing the explicit dependency on Microsoft.CodeAnalysis.Common worked.

In my defense, this is a side project that started out as a Windows Phone App (back when MS was encouraging employees to build them on the side) that I have been keeping updated to experiment with the latest versions of frameworks, so I imagine there was a point in the past where that inclusion made sense or was a workaround for something else.  If there were any way to make the error help point to the solution that would be extremely helpful.

In fact, this warning: ```warning NU1608: Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.CSharp 4.0.0 requires Microsoft.CodeAnalysis.Common (= 4.0.0) but version Microsoft.CodeAnalysis.Common 4.2.0 was resolved``` probably would have helped, but I noticed that earlier that the actual bug and gave up on trying to resolve it due to this very unhelpful thread: https://github.com/dotnet/roslyn/issues/57708

**Comment by MackinnonBuck** [comment]
Thanks @dwgray, glad your issue has been resolved. Closing this out.

**Comment by nicholust** [comment]
Thanks @MackinnonBuck the versions listed above worked for me
