### ISSUE TITLE
cannot be packaged  staticwebassets.pack.json not found

### ISSUE THREAD

**Issue by qcjxberin** [dotnet/aspnetcore#42200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

严重性	代码	说明	项目	文件	行	禁止显示状态
错误		Manifest file at 'S:\Code\src\CookieManager\obj\Release\net7.0\staticwebassets.pack.json' not found.	DG.CookieManager	C:\Program Files\dotnet\sdk\7.0.100-preview.5.22307.18\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.Pack.targets	205	

### .NET Version

7.0.100-preview.5.22307.18

**Comment by qcjxberin** [comment]
I used Microsoft.NET.Sdk.Web and I also used <EnableStaticWebAssets>false</EnableStaticWebAssets> but still doesn't solve the problem

**Comment by meziantou** [comment]
I get the same issue when updating to .NET 7 preview 5 (`7.0.100-preview.5.22307.18`):

Repro steps:
- `dotnet new razorclasslib`
- Remove `wwwroot` and `.css` files
- `dotnet pack` => "C:\Program Files\dotnet\sdk\7.0.100-preview.5.22307.18\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.Pack.targets(205,5): error : Manifest file at 'obj\Debug\net7.0\staticwebassets.pack.json' not found."

Workaround:
- Add `<StaticWebAssetsEnabled>false</StaticWebAssetsEnabled>` to the csproj

**Comment by qcjxberin** [comment]
@meziantou Thanks, I solved it too.

**Comment by meziantou** [comment]
I think you should reopen the issue as there is a potential bug that should be investigated by the ASP.NET Core team (or at least triaged). Adding `StaticWebAssetsEnabled` was not needed in previous release, and I don't think the new behavior is intended.

**Comment by qcjxberin** [comment]
@meziantou ok i have reopened

**Comment by javiercn** [comment]
@qcjxberin thanks for reporting the issue.

We think this was addressed [here](6c50892ff1b0cc237f98f946fd26ea7bdd7f012c) it should be available on the next release.

**Comment by jander-msft** [comment]
I'm trying to use the latest SDK list at https://github.com/dotnet/installer#table, which has a version of 7.0.100-preview.7.22329.1, and this is still an issue.

Runtime versions:
```
Microsoft.AspNetCore.App 3.1.26 [D:\src\dotnet\dotnet-monitor\.dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.17 [D:\src\dotnet\dotnet-monitor\.dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.6 [D:\src\dotnet\dotnet-monitor\.dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.0-preview.7.22324.1 [D:\src\dotnet\dotnet-monitor\.dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.0-preview.7.22327.8 [D:\src\dotnet\dotnet-monitor\.dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.26 [D:\src\dotnet\dotnet-monitor\.dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.17 [D:\src\dotnet\dotnet-monitor\.dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.6 [D:\src\dotnet\dotnet-monitor\.dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.0-preview.6.22322.7 [D:\src\dotnet\dotnet-monitor\.dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.0-preview.6.22326.1 [D:\src\dotnet\dotnet-monitor\.dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 7.0.0-preview.7.22322.5 [D:\src\dotnet\dotnet-monitor\.dotnet\shared\Microsoft.WindowsDesktop.App]
```

SDK versions:
```
7.0.100-preview.7.22329.1 [D:\src\dotnet\dotnet-monitor\.dotnet\sdk]
```

Build errors:
```
D:\src\dotnet\dotnet-monitor\.dotnet\sdk\7.0.100-preview.7.22329.1\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.S
dk.Razor.StaticWebAssets.Pack.CrossTargeting.targets(105,5): error : Manifest file at 'D:\src\dotnet\dotnet-monitor\art
ifacts\obj\dotnet-monitor\Debug\net6.0\staticwebassets.pack.json' not found. [D:\src\dotnet\dotnet-monitor\src\Tools\do
tnet-monitor\dotnet-monitor.csproj]
D:\src\dotnet\dotnet-monitor\.dotnet\sdk\7.0.100-preview.7.22329.1\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.S
dk.Razor.StaticWebAssets.Pack.CrossTargeting.targets(105,5): error : Manifest file at 'D:\src\dotnet\dotnet-monitor\art
ifacts\obj\Microsoft.Diagnostics.Monitoring.WebApi\Debug\net6.0\staticwebassets.pack.json' not found. [D:\src\dotnet\do
tnet-monitor\src\Microsoft.Diagnostics.Monitoring.WebApi\Microsoft.Diagnostics.Monitoring.WebApi.csproj]
```

**Comment by javiercn** [comment]
@jander-msft thanks for the additional details. I have addressed the issue and added additional test coverage [here](https://github.com/dotnet/sdk/pull/26476) hopefully we can get this merged today and available in preview7 builds in a few days.

As an aside, I would point out that packing web applications is not something that we support. I am not 100% sure on what context you are doing this, but it is something we explicitly don't support.

**Comment by jander-msft** [comment]
> As an aside, I would point out that packing web applications is not something that we support. I am not 100% sure on what context you are doing this, but it is something we explicitly don't support.

Where is it publicly documented that `dotnet pack` on ASP.NET projects is not supported? The closest I found is https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack, which says:

```
Web projects aren't packable by default. To override the default behavior, add the following property to your .csproj file:
```

which is a very different than stating that it is not supported and lends credence to this action being supported. Additionally, a warning is logged from `dotnet pack` that states how to enable it rather than stating it's not supported, prohibited, or even ill-advised:

```
C:\Program Files\dotnet\sdk\6.0.400-preview.22322.20\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(2
03,6): warning : This project cannot be packaged because packaging has been disabled. Add <IsPackable>true</IsPackable>
 to the project file to enable producing a package from this project.
```

**Comment by javiercn** [comment]
@jander-msft we disable packing of webprojects and it is not something we do any sort of testing for. The team position has always been that we set IsPackable false to indicate that it is not something we support. You might override the setting, but we don't guarantee it works.

I was not aware of that doc, but I'll get it corrected.

**Comment by javiercn** [comment]
@jander-msft thanks for bringing the docs issue to our attention, I filed an issue to get it corrected.

**Comment by javiercn** [comment]
This was now addressed https://github.com/dotnet/sdk/commit/b9a1984e221b0900d6cdb42699dca03444080d22

**Comment by jander-msft** [comment]
If you want to say that `dotnet pack` is not supported for creating NuGet packages from ASP.NET applications, that might be fair. But I think ASP.NET applications as .NET tools (by which the only way to create them is via `dotnet pack`) should be supported.
