### ISSUE TITLE
Logout does not work when using AddOidcAuthentication #31088

### ISSUE THREAD

**Issue by tbone95** [dotnet/aspnetcore#46489]
### Is there an existing issue for this?

- [X] I have searched the existing issues and yes there is, I've linked it below.

### Describe the bug

This issue - https://github.com/dotnet/aspnetcore/issues/31088#issue-836464775 is happening for me as well. The logout works fine when I'm on the root page, however, if I'm on any other page it won't work and I get the same error as this original post. 
Using .NET 7.0 and OIDC.

I'm using the NavigateToLogout method like below.

Within the LoginDisplay.
```
<AuthorizeView>
    <Authorized>
        <span class="currentuser-details-section dark:text-dark-mode-text cursor-pointer" @onclick="SwitchTheme">User: @context.User.Identity?.Name</span>        
        <button class="nav-link btn btn-link" @onclick="BeginSignOut">(Log out)</button>
    </Authorized>
</AuthorizeView>
```

Code Behind

```
private void BeginSignOut(MouseEventArgs args)
    {
        this.NavigationManager.NavigateToLogout("authentication/logout");
    }
```

### Expected Behavior

Should logout from any page.

### .NET Version

7.0

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This should be fixed in the most recent 7.0.2 release. Can you please try it out and confirm if that resolves your issue? Thanks!

**Comment by tbone95** [comment]
I just downloaded and installed the latest SDK from here - https://dotnet.microsoft.com/en-us/download/dotnet/7.0

I'm still getting the same result, is there something else required to fix this?

**Comment by javiercn** [comment]
@tbone95 can you tell us what is not working?

**Comment by tbone95** [comment]
In Blazor WASM and I click logout it calls the "Code Behind" code I mentioned above.
The issue is that when I'm at the root directory ("/") it logs out fine, but if I navigate to another page ("/foo/bar") I get the following error:
`There was an error trying to log you out: 'The logout was not initiated from within the page.'`

**Comment by javiercn** [comment]
@tbone95 does this happen during development or only on the published app.

Does it go away if you prefix the url with `/`?

Can you turn on logging and capture the logs?

* Turn logging level to the max by adding this to your Program.cs
  * builder.Logging.SetMinimumLevel(LogLevel.Trace);
* On the developer tools window, filter the console log messages by:
  * Microsoft.AspNetCore.Components.WebAssembly.Authentication

**Comment by tbone95** [comment]
Ok I've worked out the issue.

I'm using the NavigateToLogout() because if I use the SignOutSessionStateManager and use 
`await SignOutManager.SetSignOutState();` it tells me that it's obsolete and to use the 'NavigateToLogout' instead.

I have added the 'SetSignOutState' as well and it's fixed it.

I have added images to explain for reference.
![2023-02-10_11-29-48](https://user-images.githubusercontent.com/106566977/217977638-fa463115-c0e1-4739-abc2-8774f24b5986.png)
![2023-02-10_11-30-30](https://user-images.githubusercontent.com/106566977/217977813-bfb9a38a-0064-43d5-8f85-1a6cf261e1b1.png)

**Comment by tbone95** [comment]
What is the outcome from this? This will be fixed and for now I just use it as above?

**Comment by mkArtakMSFT** [comment]
@tbone95 we still don't have enough information to move forward with this. It would help if you can share the logs requested earlier. Otherwise, we'll need to investigate this which may take us some time.

**Comment by tbone95** [comment]
The logging steps mentioned earlier weren't working. Can you please provide all steps required to enable logging on Blazor WASM and I'll see if I can get it working to provide the logs you require? If not, I've sent screenshots of the issue I've found, can you not replicate by doing the same process?

**Comment by javiercn** [comment]
Gave this a try with 7.0.4 and this seems to be working as expected. 

We did fix a bug here in 7.0.1 I believe, but that's it.

https://user-images.githubusercontent.com/6995051/225306404-c8811dfe-4d8b-4dfc-9ba4-869fa6fa4500.mp4
