### ISSUE TITLE
ASP0023 Ambiguous route warning when targeting .NET 8 and using token [action] or [controller] in [Http*] or [Route] attributes

### ISSUE THREAD

**Issue by Alien21** [dotnet/aspnetcore#49777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When targeting .NET 8 preview 6 and using token [action] or [controller] in [Http*] or [Route] attributes on a controller method, an ASP0023 warning is emitted which is a new behaviour that wasn't observed in .NET 7.

If you ignore the warnings, the code will run and the endpoints can be called and return the expected responses for their respective verbs.

### Expected Behavior

No warning generated

### Steps To Reproduce

```
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddControllers();

var app = builder.Build();
app.MapControllers();
app.Run();

[Route("api/[controller]")]
[ApiController]
public class MyController : ControllerBase
{
    [HttpGet("[action]")]
    public IActionResult GetTime() => Ok(DateTime.Now.ToString("HH:mm:ss"));
    
    [HttpGet("[action]")]
    public IActionResult GetDate() => Ok(DateTime.Now.ToString("yyyy-MM-dd"));
}
```

### Exceptions (if any)

No response

### .NET Version

8.0.100-preview.6.23330.14

### Anything else?

```
╰─ dotnet --info                                                                                                                                                                           ─╯
.NET SDK:
 Version:   8.0.100-preview.6.23330.14
 Commit:    ba97796b8f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.6.23330.14\

.NET workloads installed:
 [wasm-tools]
   Installation Source: SDK 8.0.100-preview.6
   Manifest Version:    8.0.0-preview.6.23329.7/8.0.100-preview.6
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-preview.6\microsoft.net.workload.mono.toolchain.current\WorkloadManifest.json
   Install Type:              Msi
 [wasm-tools-net6]
   Installation Source: SDK 8.0.100-preview.6
   Manifest Version:    8.0.0-preview.6.23329.7/8.0.100-preview.6
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-preview.6\microsoft.net.workload.mono.toolchain.net6\WorkloadManifest.json
   Install Type:              Msi

Host:
  Version:      8.0.0-preview.6.23329.7
  Architecture: x64
  Commit:       5340be2ccc

.NET SDKs installed:
  7.0.306 [C:\Program Files\dotnet\sdk]
  8.0.100-preview.6.23330.14 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.6.23329.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.6.23329.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.6.23329.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

```

**Comment by WernerMairl** [comment]
Same here with net8.0 RC2.

Assuming that "[action]" is interpreted as literal/constant instead of a expression, and then for sure it isn't unique...

BR 
Werner

**Comment by Glitched94** [comment]
Additional note based on what I've seen, it's not considering the full route at all. It seems to only be checking the [Http*] or [Route] attribute on the method, and not seeing the [Route] attribute on the Controller. Usage below throws the same ASP0023 warning despite the full routes of the methods being distinct.

``` csharp
[Route("api/controller1/[action]")]
[ApiController]
public class Controller1 : ControllerBase
{
    [HttpGet("{id:int}")]
    public IActionResult GetMethod(int id) => Ok();
}

[Route("api/controller2/[action]")]
[ApiController]
public class Controller2 : ControllerBase
{
    [HttpGet("{id:int}")]
    public IActionResult GetMethod(int id) => Ok();
}
```

**Comment by jeffraska** [comment]
Analyzer was introduced in PR https://github.com/dotnet/aspnetcore/pull/45915.
@JamesNK is there chance analyzer behavior will be fixed on .net 8 release?

**Comment by martincostello** [comment]
If there's a bug in the analyzer and it's patched in servicing, it's not going to make it into the 8.0.0 release at this point.

**Comment by JamesNK** [comment]
> Analyzer was introduced in PR #45915. @JamesNK is there chance analyzer behavior will be fixed on .net 8 release?

No, .NET 8 is locked down for only urgent fixes right now. This is a bug but not a critical one. However, it can be fixed in 8.0.x release in later this year or early next year.

I suggest you disable the analyzer in code or in the project file, and reenable when it is fixed.

**Comment by Mike-E-angelo** [comment]
Woohoo.  Thank you for your efforts out there @JamesNK and team. 🙏  Happy Holidays. 🦃

**Comment by suchyspotio** [comment]
check string interpolation: [HttpPost($"[action]")]

**Comment by MonstraG** [comment]
Can anybody confirm, was this released in 8.0.1, or is it not fixed yet?

**Comment by JamesNK** [comment]
It should be. Is the issue fixed with 8.0.1?

**Comment by RudyWangCodes** [comment]
I'm still get the warning after update to 8.0.1 with HttpPut method

**Comment by JamesNK** [comment]
If you provide a minimal reproduction then I'll take a look.

**Comment by willyt150** [comment]
After upgrading VS to 17.8.4 (which is how I'm currently getting my .NET 8 SDK) the .NET SDK updated to 8.0.101 and I no longer receive the warnings.

**Comment by menees** [comment]
We're still getting the warnings in 8.0.1. For a minimal repro, I created a new project using the "ASP.NET Core Web API" template with "Use controllers" checked. It generated a `WeatherForecastController`. and I changed it to look like this:

``` C#
namespace WebApplication2.Controllers;
using Microsoft.AspNetCore.Mvc;

[ApiController]
[Route("[controller]")]
public class WeatherForecastController : ControllerBase
{
    private static readonly string[] Summaries = new[]
    {
        "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
    };

    [HttpGet]
    [Route("{action}")]
    public IEnumerable<WeatherForecast> GetWeatherForecast()
    {
        return Enumerable.Range(1, 5).Select(index => new WeatherForecast
        {
            Date = DateOnly.FromDateTime(DateTime.Now.AddDays(index)),
            TemperatureC = Random.Shared.Next(-20, 55),
            Summary = Summaries[Random.Shared.Next(Summaries.Length)]
        })
        .ToArray();
    }

    [HttpGet]
    [Route("{action}")]
    public IEnumerable<string> GetSummaries() => Summaries;
}
```

The ASP0023 analyzer highlights both `[Route("{action}")]` lines. When I run the project, Swagger throws an exception because it can't handle two HttpGets:

``` stacktrace
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException
  HResult=0x80131500
  Message=Conflicting method/path combination "GET WeatherForecast/{action}" for actions - WebApplication3.Controllers.WeatherForecastController.Get (WebApplication3),WebApplication3.Controllers.WeatherForecastController.GetSummaries (WebApplication3). Actions require a unique method/path combination for Swagger/OpenAPI 3.0. Use ConflictingActionsResolver as a workaround
  Source=Swashbuckle.AspNetCore.SwaggerGen
  StackTrace:
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerDocumentWithoutFilters(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.<GetSwaggerAsync>d__6.MoveNext()
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__4.MoveNext()
```

However, both routes work just fine when invoked directly. Putting `https://localhost:7216/WeatherForecast/GetSummaries` in a browser window returns:
``` json
["Freezing","Bracing","Chilly","Cool","Mild","Warm","Balmy","Hot","Sweltering","Scorching"]
```

Putting `https://localhost:7216/WeatherForecast/GetWeatherForecast` in browser window returns:
``` json
[{"date":"2024-01-12","temperatureC":16,"temperatureF":60,"summary":"Scorching"},{"date":"2024-01-13","temperatureC":12,"temperatureF":53,"summary":"Bracing"},{"date":"2024-01-14","temperatureC":22,"temperatureF":71,"summary":"Mild"},{"date":"2024-01-15","temperatureC":32,"temperatureF":89,"summary":"Balmy"},{"date":"2024-01-16","temperatureC":41,"temperatureF":105,"summary":"Scorching"}]
```

The routes are not ambiguous given how the `{action}` token is interpreted in a [route template](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-8.0#route-templates), so I don't think ASP0023 should complain about them. At a minimum, it seems like a rule with too many false positives and not enough documentation to explain what it's really trying to warn about. Maybe, it's saying "Swagger doesn't support this." But it's not reporting _ambiguous_ routes in these cases. 

The rule's error message's first sentence is incorrect given how route templates are processed.

``` text
Route '{action}' conflicts with another action route. An HTTP request that matches multiple routes results in an ambiguous match error. Fix the conflict by changing the route's pattern, HTTP method, or route constraints.
```

The [rule's documentation](https://learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0023?view=aspnetcore-8.0) doesn't provide any useful information other than a minimal restatement of that error message.

Note that if I remove the `[Route("{action}")]` attributes, then neither API will work because an HTTP GET request is ambiguous. But with the attributes present, the routes are not ambiguous.

This minimal repro case is a simplified, contrived example of my old, real-world project where I'm seeing a bunch of ASP0023 errors. It has a few controllers that have multiple HttpGet and HttpPut methods tagged with `[Route("{action}")]`, and the routes are _not_ ambiguous. They work fine now and have for years. So, maybe the documentation for ASP0023 needs to say it's ok to suppress this rule if your controllers intentionally distinguish HTTP actions by using the `{action}` route template instead of just saying, "Do not suppress a warning from this rule."

**Comment by jeffraska** [comment]
@menees correct route token is `[action]` not `{action}`

**Comment by menees** [comment]
Thanks, @jeffraska! That's good to know, and that's an interesting subtlety. It wasn't clear to me from the [route template](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-8.0#route-templates) documentation, which lists examples using `{action}`. However, when I change my example to use `[Route("[action]")]`, Swagger works, each action still works, and ASP0023 no longer appears.

**Comment by Mike-E-angelo** [comment]
> It wasn't clear to me from the [route template](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-8.0#route-templates) documentation, which lists examples using {action}.

I had the same happen to me.  All my warnings went away except for the ones with `{action}` and it made me wonder how it has been working this entire time if it's wrong. 🤔  Apparently this is the same as `[action]`?  In any case, switching to this solved all my warnings and even Swagger is happy now. 🙏

**Comment by jeffraska** [comment]
Curly-braced tokens are used for passing parameters from url to handler.
There is nice post about it
https://dotnettutorials.net/lesson/model-binding-using-fromroute-in-asp-net-core-mvc/

**Comment by menees** [comment]
I've spent more time researching this today, and Microsoft's routing docs are kind of a mess about it. [This section](https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-8.0#token-replacement-in-route-templates-controller-action-area) says:

> For convenience, attribute routes support token replacement by enclosing a token in square-brackets ([, ]). The tokens [action], [area], and [controller] are replaced with the values of the action name, area name, and controller name from the action where the route is defined:

Then [further down on that same page](https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-8.0#specifying-attribute-route-optional-parameters-default-values-and-constraints), it says:

> Attribute routes support the same inline syntax as conventional routes to specify optional parameters, default values, and constraints.

Then it links to a [Route Template Reference](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-8.0#route-template-reference) page, which uses `{action}` six times and never uses `[action]`.

The fact that attribute route processing supports `{action}` at runtime, but Swagger and the ASP0023 rule don't support it seems very inconsistent. I can't find a Microsoft-documented reason for it. Attribute routing is documented to support two syntaxes for token replacements (`{}` and `[]`), but these external tools don't follow the same convention.

**Comment by menees** [comment]
I increased the severity of the [ASP0018](https://learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0018) "Unused route parameter" rule to Error, so it flagged the `{action}` parameter as unused and gave a compile error. Then I fixed all those places to use `[action]`. Now the rules work together to prevent us from using the non-preferred syntax in the future.

**Comment by JamesNK** [comment]
I think we can make the analyzer special case `{action}`. It's not usual to use a parameter instead of replacement, but it is supported, so the analyzer should handle it.

**Comment by jamespfluger-ava** [comment]
So simply using `{action}` results in the same behavior as `[action]`? If so, I can't for the life of me figure out why there are two syntaxes that produce the same result.

**Comment by jamespfluger-ava** [comment]
Using `{action}` instead of `[action]` still results in the same warning as before.

Does this affect the actual behavior of anything or is it just an analyzer? Still seeing an issue using either as of today (2024-01-15)

**Comment by Fulgan** [comment]
This seems like a poorly written validation: the methodes  with different names but marked with the same {action} (or [action] route template clearly do not represent the same endpoint: there is no ambiguity during routing.

**Comment by pwinstead** [comment]
@JamesNK I was running into this today with latest release and it seems that the fix doesn't work if you are include [action] or {action} as part of your route with a route attribute at the controller level.

This containers no warnings

```
[Route("api/[controller]")]
[ApiController]
public class MyController : ControllerBase
{
    [HttpGet("{action}")]
    public IActionResult GetTime() => Ok(DateTime.Now.ToString("HH:mm:ss"));
    
    [HttpGet("{action}")]
    public IActionResult GetDate() => Ok(DateTime.Now.ToString("yyyy-MM-dd"));
}
```


This contains warnings.
```
[Route("api/[controller]/[action]")]
[ApiController]
public class MyController : ControllerBase
{
    [HttpGet]
    public IActionResult GetTime() => Ok(DateTime.Now.ToString("HH:mm:ss"));
    
    [HttpGet]
    public IActionResult GetDate() => Ok(DateTime.Now.ToString("yyyy-MM-dd"));
}
```

**Comment by JamesNK** [comment]
I get no warnings from this:
```cs
[Route("api/[controller]/[action]")]
[ApiController]
public class MyController : ControllerBase
{
    [HttpGet]
    public IActionResult GetTime() => Ok(DateTime.Now.ToString("HH:mm:ss"));
    
    [HttpGet]
    public IActionResult GetDate() => Ok(DateTime.Now.ToString("yyyy-MM-dd"));
}
```
This has warnings but they are fixed in 8.0.3 (not released yet):
```cs
[Route("api/[controller]")]
[ApiController]
public class MyController : ControllerBase
{
    [HttpGet("{action}")]
    public IActionResult GetTime() => Ok(DateTime.Now.ToString("HH:mm:ss"));
    
    [HttpGet("{action}")]
    public IActionResult GetDate() => Ok(DateTime.Now.ToString("yyyy-MM-dd"));
}
```

**Comment by pwinstead** [comment]
@JamesNK and @MonstraG I corrected my comment above.  I'm sorry for making that mistake. Here was my actual example I was struggling with. Seems like I might need to retest once 8.0.3 is release.

This code has warning.
```
[Route("api/[controller]/[action]")]
[ApiController]
public class MyController : ControllerBase
{
	[HttpGet("{id}")]
	public IActionResult GetTime(int id) => Ok(DateTime.Now.ToString("HH:mm:ss"));
    
	[HttpGet("{id}")]
	public IActionResult GetDate(int id) => Ok(DateTime.Now.ToString("yyyy-MM-dd"));
}
```

This doesn't have warnings.
```
[Route("api/[controller]")]
[ApiController]
public class MyController : ControllerBase
{
	[HttpGet("[action]/{id}")]
	public IActionResult GetTime(int id) => Ok(DateTime.Now.ToString("HH:mm:ss"));
    
	[HttpGet("[action]/{id}")]
	public IActionResult GetDate(int id) => Ok(DateTime.Now.ToString("yyyy-MM-dd"));
}
```
