### ISSUE TITLE
Blazor Web App Template NavMenu Component is Missing Render Attribute - Click Events Do Not Get Fired

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#50028]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-Web-App-Template-NavMenu-Componen/10438817)._

---
I was using the 'Blazor Server App' template before, but now discovered the 'Blazor Web App' template.
When testing my new app, I noticed that the ToggleNavMenu click event was not getting fired in the NavMenu component.

On a whim, I decided to add the @attribute [RenderModeServer] to the NavMenu component. When I did then the click events started to fire.

Is that the render mode I should be using for the NavMenu - if not, what do you recommend?

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by guardrex** [comment]
This should be fixed for RC1 per ...

https://github.com/dotnet/aspnetcore/pull/49801#pullrequestreview-1559427680

**Comment by marqdouj-spartan** [comment]
I want to add click events to some of NavLinks for nesting/dropdowns. I've tried using @onclick and the Bootstrap 'toggle' classes and none work except if I add the RenderModeServer option.

**Comment by marqdouj-spartan** [comment]
That's perfect, thanks! 👍

**Comment by mkArtakMSFT** [comment]
This should be fixed already.

**Comment by marqdouj-spartan** [comment]
Still doesn't work for me. According to VS Installer I have the latest version:

![image](https://github.com/dotnet/aspnetcore/assets/97969185/d0b4eb82-6f0f-4fd8-abd9-0c52356344df)

Note: I have 'use interactive server components' checked - if that makes a difference.

**Comment by guardrex** [comment]
@marqdouj-spartan ... RC1 doesn't come out for a few more weeks. If you want the toggler to work on its own using Steve's new approach in the framework, you'll need to wait until RC1 lands next month. If you want it to work today under Pre7, then follow the remarks in the OP :point_up:.

**Comment by marqdouj-spartan** [comment]
No rush, I can wait.
Thanks!

**Comment by guardrex** [comment]
It will be announced at the blog post when it lands ...

https://devblogs.microsoft.com/dotnet/category/blazor/

... and the download gesture will be from within VS via the VS installer. VS will alert you as soon as it comes out.

**Comment by marqdouj-spartan** [comment]
I've downloaded the latest VS and .NET 8 RC 1. I still can't get click events unless I use @attribute [RenderModeServer].
Are click events only available using this render mode?

**Comment by guardrex** [comment]
Yes, @marqdouj-spartan, if you're referring to ***your*** additions (for server interactivity). What Steve did for this only applies to the nav menu toggler. If you have other server-based interactivity that you need to enable, then you add the attribute for interactive server rendering.

**Comment by marqdouj-spartan** [comment]
I guess what I am trying to understand is the concept of having button click events in blazor (I am learning web/blazor). No matter what 'interactive' mode I choose (webassembly or server) I can only get click events in my razor component (page) when using RenderModeServer. I'm confused on when I can get click events to work in blazor. The Blazor/.NET 8 docs do not mention anything about requiring any render mode - they just show how to use them.

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-8.0

**Comment by guardrex** [comment]
I think the doc not showing up is just because you have the .NET 7 docs loading by default. Change the version selector to .NET 8, and the new *Render modes* article will show up. See if that explains things. The article is here, and this link should open it (and set the version selector to .NET 8) ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0

**Comment by marqdouj-spartan** [comment]
Thanks for the link - I think the 'render-modes' link should be referenced on the 'event-handling' link I posted.
