### ISSUE TITLE
ThrowTargetParameterCountException raised when running my .NET WebAPI

### ISSUE THREAD

**Issue by epoitier** [dotnet/aspnetcore#50940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When running the attached .NET v8 WebAPI server, the exception showed below is raised. It is happening due to the [] operator overridden in the Settings class (if set as private, it won't be raised), but was working fine on .NET v7. It seems a change in .NET v8 ASP is forcing the Item methods to be fetched, pointing to the overridden [] operator.

### Expected Behavior

The expected behaviour would be to work the same than ASP .NET v7 and not raising the exception.

### Steps To Reproduce

[WebAPI_DotNet8_Crashing.zip](https://github.com/dotnet/aspnetcore/files/12726462/WebAPI_DotNet8_Crashing.zip)

### Exceptions (if any)

   à System.Reflection.MethodBaseInvoker.ThrowTargetParameterCountException()
   à System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   à System.Reflection.PropertyInfo.GetValue(Object obj)
   à Microsoft.Extensions.Options.DataAnnotationValidateOptions`1.TryValidateOptions(Object options, String qualifiedName, List`1 results, List`1& errors, HashSet`1& visited)
   à Microsoft.Extensions.Options.DataAnnotationValidateOptions`1.Validate(String name, TOptions options)
   à Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   à System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   à System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   à System.Lazy`1.CreateValue()
   à Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd[TArg](String name, Func`3 createOptions, TArg factoryArgument)
   à Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
   à Microsoft.Extensions.DependencyInjection.OptionsBuilderExtensions.<>c__DisplayClass0_1`1.<ValidateOnStart>b__1()
   à Microsoft.Extensions.Options.StartupValidator.Validate()
   à Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__15.MoveNext()
   à Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__15.MoveNext()
   à Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   à Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   à Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   à enman.resource_manager.webapi.Program.Main(String[] args) dans D:\Depots\projets\resource_manager\branches\ep_developer_authentication\src\server\enman.resource_manager.webapi\Program.cs :ligne 407

### .NET Version

8.0.100-rc.1.23455.8

**Comment by BrennanConroy** [comment]
This looks like https://github.com/dotnet/runtime/issues/92276 which is fixed in RC2.

**Comment by BrennanConroy** [comment]
Closing, feel free to reopen if that's not the issue, and if this is an aspnetcore issue, and not a runtime issue.

**Comment by epoitier** [comment]
Thanks for the support. Quite shared though, as my reproduction sample seems to run correctly after installing dotnet 8 rc2, though in my application, the crash is still hapenning during the launch when verifying the appsettings.json.

**Comment by epoitier** [comment]
Ok, so after updating the Visual Studio 2022 to Preview 3 (was under Preview 2), I can confirm the RC2 is fixing the issue. Thanks for the support
