### ISSUE TITLE
HeadOutlet with head::after renders HeadContent into the middle of head, instead of appending to the end

### ISSUE THREAD

**Issue by Peter-Juhasz** [dotnet/aspnetcore#51391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Even though `HeadOutlet` is set to `head::after`, `HeadContent` renders to the middle of the `head` element, after `title` but before everything else.

It worked in .NET 7, seems like a regression in .NET 8.

(Example use case: change theme using CSS, overwrite CSS variables with another file. It works well if the theme file is appended as the latest one in order, while if it is loaded first, default theme values override it, so the theme doesn't get effectively applied.)

### Expected Behavior

Content is rendered at the end of `head` element.

### Steps To Reproduce

![image](https://github.com/dotnet/aspnetcore/assets/9047283/1c0adc9c-8324-404b-9a44-dcf880df1fb6)

Start from Blazor WebAssembly project template.

Program.cs (already set)
```cs
builder.RootComponents.Add<HeadOutlet>("head::after");
```

Add to any razor file:
```razor
<HeadContent>
    <meta name="test" content="test" />
</HeadContent>
```

### Exceptions (if any)

No exceptions.

### .NET Version

8.0.100-rc.2.23502.2

### Anything else?

```
.NET SDK:
 Version:   8.0.100-rc.2.23502.2
 Commit:    0abacfc2b6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-rc.2.23502.2\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-rc.2.23479.6
  Architecture: x64
  Commit:       0b25e38ad3

.NET SDKs installed:
  8.0.100-rc.2.23502.2 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-rc.2.23480.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.2.23479.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-rc.2.23479.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by danroth27** [comment]
I verified that if I take a .NET 7 Blazor WebAssembly app the head content renders at the bottom of the head, but when I update the app to .NET 8 RC2 the head content moves to the top.

**Comment by GZidar** [comment]
Hi @mkArtakMSFT the reason this is a problem is because moving to the start (or the middle) it impacts the order of CSS rule evaluation. We are using the HeadOutlet :: after to load in the custom CSS and when it was being added to the end then the rules of the custom CSS were applied last (which is what we were expecting) but now that it has moved to the top it means the custom CSS rules are evaluated first and default rules are then overriding them.

**Comment by mkArtakMSFT** [comment]
A fix has been merged for this and it will ship in the upcoming .NET 8 patch release.

**Comment by zachgreen** [comment]
I have v8.0.1, but I am still seeing this issue. Has the fix actually been released?

**Comment by danroth27** [comment]
@zachgreen The first patch release of .NET 8 hasn't been released yet. It should be available in Jan.

**Comment by zachgreen** [comment]
@danroth27 Is there any official workaround for this issue?

I put a nasty hack in that appears to work, but I am not in love with it. It appears that Chrome, Firefox, and Edge load style and script tags that are inside a <template /> element in the <head /> element.

index.html:
<img width="1188" alt="image" src="https://github.com/dotnet/aspnetcore/assets/1130739/881bc92e-cd0f-44fc-82c3-ab6dad6ba2bf">

Program.cs:
<img width="1288" alt="image" src="https://github.com/dotnet/aspnetcore/assets/1130739/2b3cba52-8760-48eb-8738-d07a9fd90255">

**Comment by WoodyJ007** [comment]
We just added another head in the body...which is awful but works in Maui on windows and android. Doesn't work when released on a iPhone or Mac though. This patch can't come soon enough.

**Comment by WoodyJ007** [comment]
The patch was released on 9th right?  The issue still persists with Maui Blazor.  HeadOutlet is still put at the start!

**Comment by zachgreen** [comment]
I can confirm with 8.0.1 installed, in Blazor WASM, the `HeadOutlet` is correctly rendering at the end of the `<head />` element.
