### ISSUE TITLE
The SPA default page middleware could not return the default page '/index.html' in production application

### ISSUE THREAD

**Issue by danobri** [dotnet/aspnetcore#5223]
I have an ASP.Net Core / Angular 5 application that is logging errors to the Windows Event Log in our production environment.  The following error is getting logged frequently but intermittently in production, and I have no idea why.  The application is definitely in production mode, has been published, and is functioning.

`System.InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.
Your application is running in Production mode, so make sure it has been published, or that you have built your SPA manually. Alternatively you may wish to switch to the Development environment.`

AFAIK no users are experiencing a problem with the site when these errors occur.  Any idea why these errors are being thrown, and whether there is in fact a problem that needs to be addressed?

**Comment by ColinM9991** [comment]
Hi folks,

I too have this issue with ASP.NET Core, running on .NET Core targeting platform with Angular 7. The application works fine but my log files are plagued with this exception.

![image](https://user-images.githubusercontent.com/2162419/50301867-58951100-0480-11e9-852e-995e584fc1ae.png)

Hosted server is
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

This is a picture of the directory structure, ClientApp/dist/index.html exists
![image](https://user-images.githubusercontent.com/2162419/50301799-313e4400-0480-11e9-82cf-24069e52c6d3.png)

Middleware is configured, out of the box with ASP.NET Core + Angular template, like so
`app.UseSpa(spa =>
{
    spa.Options.SourcePath = "ClientApp";
});`

angular.json has the output path correctly set to `dist`
`
"options": {
  "outputPath": "dist",
  "index": "src/index.html",
  "main": "src/main.ts",
  "tsConfig": "src/tsconfig.app.json",
  "progress": true,
  "polyfills": "src/polyfills.ts",
  "assets": [
    "src/assets"
  ],
  "styles": [
    "node_modules/bootstrap/dist/css/bootstrap.min.css",
    "node_modules/ngx-toastr/toastr.css",
    "src/styles.css"
  ],
  "scripts": []
},
`

**Comment by tatvapci27** [comment]
> So the reason we're getting this is someone is trying to POST AND OPTIONS to /index.html not GET. Which causes this error message and causes a 500 error.
> 
> Of course of Azure/IIS sees too many errors in too short a time it tries and recycles the app. the problem is that it's doing it over and over again which causes everything in that App Service Plan to crash. :<
> 
> How do we properly handle this without the site throwing a 500 error?
> 
> Note that this only happens in production, not development and as far as I can tell there is no way to handle this error with your own route. This is a major DOS attack vector in spa services that needs to be fixed ASAP.

@JohnGalt1717 Have you found any workaround for this?

**Comment by JohnGalt1717** [comment]
@tatvapci27 I wrote middleware and caught to error explicitly and return 400.

It has to be registered in the right order. I can't remember which at the moment so you'll need to experiment before and after the spa registration.

**Comment by ColinM9991** [comment]
@JohnGait1717

Middleware is first in first out so you could have it right before the Spa middleware.

Could you possibly share the code of this middleware component you have added? Sounds very straight forward, but would be good to put it straight into my app when I'm finished work - otherwise I could create a production ready piece of middleware and share for a temporary workaround.

**Comment by JohnGalt1717** [comment]
I stand corrected.

The middleware didn't work.

I added an exception handler that looks like this:

```
public class ExceptionHandlerMiddleware
    {
		private readonly ILogger Logger;
        public ExceptionHandlerMiddleware(ILogger logger) {
			Logger = logger ?? throw new ArgumentNullException(nameof(logger));
		}

		public async Task Invoke(HttpContext context) {
			context.Response.StatusCode = (int)HttpStatusCode.InternalServerError;

			var ex = context.Features.Get<IExceptionHandlerFeature>()?.Error;
			if (ex == null)
				return;

			Logger.LogError(new EventId(500, "InternalServerError"), ex, ex.Message);

			context.Response.ContentType = "text/html";
			context.Response.StatusCode = (int) HttpStatusCode.BadRequest;
			using (var writter = new StreamWriter(context.Response.Body)) {
				await writter.WriteLineAsync("<html>");
				await writter.WriteLineAsync("<body>");
				await writter.WriteLineAsync("<p>Invalid request.</p>");
				#if(DEBUG)
				await writter.WriteLineAsync($"<p>{ex.InnerException?.Message ?? ex.Message}</p>");
				#endif
				await writter.WriteLineAsync("</body>");
				await writter.WriteLineAsync("</html>");
				await writter.FlushAsync();
			}
		}
    }
```

and added it to the Configure function in the Startup.cs but only if not in development mode like this:

```
				app.UseExceptionHandler (new ExceptionHandlerOptions {
					ExceptionHandler = new ExceptionHandlerMiddleware (loggerFactory.CreateLogger ("SystemErrors")).Invoke
				});

```

This effectively catches them and returns an HTML page with a 400 error in those cases. Hope that helps someone!

**Comment by ColinM9991** [comment]
Thanks for that, I'll have a look at middleware later today which just redirects to index.html with GET

**Comment by dalibor-sanzeru** [comment]
Guys,
I found this discussion because my asp.net core app + ng7 (with /api hosted) returned always index.html on /api calls. 

Solution was to call UseMvc and UseSpa (inside Configure method) in correct order.
Correct order:
1) UseMvc 
2) UseSpa
Please check your order call. I hope, this help somebody...

**Comment by ColinM9991** [comment]
Having checked my code for the above order, I can confirm my app is using the order of
1. UseMvc
2. UseSpa

This remains to be an issue and plagues my log files rendering them almost useless when it comes to parsing for actual errors.

**Comment by Aj1402** [comment]
I have the same issue, but what I can see is that the index.html that the server returns is from wwwroot/ not from ClientApp/build (my distribution directory) therefore problem lies with wrong index.html being served. Can anybody tell me how can this be fixed?

**Comment by pwen090** [comment]
@Aj1402 I actually just fixed my issue. My issue was that the default .net core project sets up the paths with ClientApp but my pipeline was publishing using the string /site/wwwroot/clientapp. In my case I was using a linux app service so the difference of ClientApp vs. clientapp was failing given the case sensitivity. The error message did not really help me find that error and so your error might be different but i thought I would share this for any future person.

**Comment by cole21771** [comment]
So I just ran into this issue. Turns out that the problem is that asp.net core is weird in how it builds its stuff.

There are a bunch of DLLs that look like your production build in `ProjectName/bin/Release/netcoreappX.X/`, however, there are also a bunch of the same DLLs plus more stuff like your build client and drivers in the folder below is called `publish`. So if you run the one above, it can't find your ClientApp folder. If you run the one in the publish folder, it finds it since the publish command moves it there. 

TLDR: Run `dotnet ProjectName/bin/Release/netcoreappX.X/publish/ProjectName.dll` since it has the built ClientApp files right next to it.

Hope this helps somebody.

**Comment by jamend** [comment]
@cole21771 This helped me figure it out. I was the calling executable on the command line using its absolute path in the publish directory (let's say `/home/me/project/bin/publish/myapp`). This would give me the `The SPA default page middleware could not return the default page '/index.html'` exception. I got it to work by first changing the working directory to the publish folder and running it from there, so `cd /home/me/project/bin/publish` and `./myapp`.

**Comment by Ruud-cb** [comment]
Hi,

All of the solutions and problems I have seen so far are due application setup changes, Unfortunately my problem is occurring in production, where 1000 users each day visit and use the webshop, only a few requests yesterday ended up with this error. I am really curious why this problem occurs.

I am running Angular in the front-end and ASP.NET Core v2 in the back-end.

1. One issue occurred after doing a GET request: `/api/account/session`  This is a very commonly used request to check if the user is logged in or not. Usually it just returns 200 or 401 but now it returned 400. Which, for that api request, was redirected to /Error. 

![image](https://user-images.githubusercontent.com/10037514/54671307-f4710000-4af5-11e9-8fb5-149458ddddfc.png)

I think the user did not see this because it was just due an API request. However it did also occur during a user coming back after payment (see issue 2 below)

2. Second one is a bit more serious, because from the logs I can see that the user tried to come back from a payment operation (externally). Usually the url for that would be `/payment/complete?payload=...` but in this situation it seem to have redirected to `/index.html?payload=...` something I am 100% sure about that I never redirect users to `index.html` at all.

![image](https://user-images.githubusercontent.com/10037514/54670785-b9220180-4af4-11e9-9f6c-0dcd0a2b607d.png)

Other associated logs:

![image](https://user-images.githubusercontent.com/10037514/54670981-2fbeff00-4af5-11e9-948b-ee1d668b0ebf.png)

The trace mentioning `method: proceedWithPayment() - request is redirect` means that the user is redirected to an external site, completes the payment, and after a minute comes back.

Fortunately I can see that later logs point out that the user has probably not seen any issue and has visited the payment completion page (with the same payload query parameter). I am just very very curious why this issue occurs and how to avoid or prevent them.

It is clear to me that when someone would browse `/Error`, this error occurs, I can not reproduce the issue (exception and logs) when I redirect to `/Error`, it only shows me the content in HTML that an error occurred and I should switch to development mode to see the error.


Here is the stacktrace if that is of any use for the second issue.
```
System.InvalidOperationException:
   at Microsoft.AspNetCore.SpaServices.SpaDefaultPageMiddleware+<>c__DisplayClass0_0.<Attach>b__1 (Microsoft.AspNetCore.SpaServices.Extensions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.AspNetCore.Builder.UseExtensions+<>c__DisplayClass0_1.<Use>b__1 (Microsoft.AspNetCore.Http.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware+<Invoke>d__7.MoveNext (Microsoft.AspNetCore.StaticFiles, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext (Microsoft.AspNetCore.Routing, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware+<Invoke>d__8.MoveNext (Microsoft.AspNetCore.Cors, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware+<Invoke>d__8.MoveNext (Microsoft.AspNetCore.Cors, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware+<Invoke>d__8.MoveNext (Microsoft.AspNetCore.Cors, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware+<Invoke>d__8.MoveNext (Microsoft.AspNetCore.Cors, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware+<Invoke>d__8.MoveNext (Microsoft.AspNetCore.Cors, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware+<Invoke>d__8.MoveNext (Microsoft.AspNetCore.Cors, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext (Microsoft.AspNetCore.Authentication, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware+<Invoke>d__7.MoveNext (Microsoft.AspNetCore.StaticFiles, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware+<Invoke>d__7.MoveNext (Microsoft.AspNetCore.StaticFiles, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware+<Invoke>d__6.MoveNext (Microsoft.AspNetCore.Diagnostics, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)

```

**Comment by CTSteven** [comment]
I ran into the sam issue when user copy content from IE browser and paste to Excel. IIS logs  many OPTIONS request 500 error for /assets/... under ClientApp/dist/ folder .   
After trying many suggestions about this issue.
It works for me,  to config IIS's URL Rewrite rule to response 200 OK when  OPTIONS or POST request for /myapp/ or /myapp/assets/...

The URL Rewrite rule is :
```
<system.webServer>
    <rewrite>
      <rules>
        <rule name="avoid OPTIONS request error when paste from IE to excel" stopProcessing="true">
          <match url=".*" />
          <conditions logicalGrouping="MatchAll">
            <add input="{REQUEST_METHOD}" pattern="OPTIONS|POST" />
            <add input="{PATH_INFO}" pattern="^(/myapp)?/assets/|^/myapp/$" />
          </conditions>
          <action type="CustomResponse" statusCode="200" statusReason="OK" statusDescription="OK" />
        </rule>
      </rules>
    </rewrite>
  </system.webServer>

```

**Comment by naveedahmed1** [comment]
Any update on this? None of the above mentioned solutions fixes the problem:


> ```cs
> spa.Options.SourcePath
> ```

Since `spa.Options.SourcePath` is used in Development, as per my understanding its completely ignored in Production.



> So the reason we're getting this is someone is trying to POST AND OPTIONS to /index.html not GET. Which causes this error message and causes a 500 error.
> 
> Of course of Azure/IIS sees too many errors in too short a time it tries and recycles the app. the problem is that it's doing it over and over again which causes everything in that App Service Plan to crash. :<
> 
> How do we properly handle this without the site throwing a 500 error?
> 
> Note that this only happens in production, not development and as far as I can tell there is no way to handle this error with your own route. This is a major DOS attack vector in spa services that needs to be fixed ASAP.

I can confirm that its not any bot or someone sending requests to Index.html. I have CloudFlare on my website, I setup a Page Rule to redirect all requests to Index.html to https://www.mywebsite.com/. But still seeing the 404 errors for Index.html in my log.



> Would be nice if an error wasn't the default behavior. I was able to prevent the exceptions using a rewrite rule in my web.config.
> 
> ```
> <rewrite>
>   <rules>
>     <rule name="Prevent requests to index">
>       <match url="^index\.html$" />
>       <action type="Redirect" url="/" redirectType="Permanent" appendQueryString="true" />
>     </rule>
>   </rules>
> </rewrite>
> ```

Even setting Redirect Rule in web.config doesn't work.

> Solution was to call UseMvc and UseSpa (inside Configure method) in correct order.

Using wrong order can produce similar error but the issue discussed here is different, and it occurs even with correct order. In case of wrong order,it will always return Index.html. But the issue being discussed here is about the random 404 errors for index.html in log, despite the website seems to be working fine.

**Comment by Rookian** [comment]
I have the same problem. I don't understand, why the SPA site works eventhough I also get this error.

**Comment by cthames** [comment]
I'm also having this same exact issue. Best fix is to manually copy the `ClientApp/dist` to the `wwwroot` directory.

Note: This is a hack until we finally get some answers (been over a year!!!!!!!!!)

Does anyone have a msbuild copy task that would do this during the build? For whatever reason, I'm unable to get the msbuild copy task to work. Tried both `$(TargetDir)` and `$(OutputPath)`. Is there something special with the `wwwroot` directory that we can't recursively copy all directories and files in the `ClientApp/dist` to the `wwwroot`?

**Comment by rezabayesteh** [comment]
I think the issue is related to the wrong value for ContentRootPath. 
```
 var env = serviceProvider.GetRequiredService<IHostingEnvironment>();
            var absoluteRootPath = Path.Combine(
                env.ContentRootPath,
                options.RootPath);

            // PhysicalFileProvider will throw if you pass a non-existent path,
            // but we don't want that scenario to be an error because for SPA
            // scenarios, it's better if non-existing directory just means we
            // don't serve any static files.
            if (Directory.Exists(absoluteRootPath))
            {
                _fileProvider = new PhysicalFileProvider(absoluteRootPath);
            }
```

**Comment by ryanbrandenburg** [comment]
Does anyone have a concrete list of repro steps for this? Earlier in the thread it seemed that people were running into this when they just did `dotnet new react; dotnet publish -c Release; .\bin\Release\netcoreapp3.0\publish\*.exe`, but when I tried that locally it worked fine. There seems to be a common theme with some people solving it by setting the correct ContentRootPath, but it's hard for me to tell if that's the root problem here since I'm not able to reproduce.

So if I can get either 1. A GitHub repo that I can clone then run 1 or 2 dotnet commands to replicate the behavior or 2. A short list of steps to take an app from `dotnet new` to demonstrating this behavior that would be greatly helpful in diagnosing this. If possible I would prefer number 1.

**Comment by maxisam** [comment]
@ryanbrandenburg The problem is it doesn't show up every time, which is why we don't know what sets it off.

**Comment by naveedahmed1** [comment]
@ryanbrandenburg in my case the issue occurs with Angular app with SSR enabled and deployed on live server. In my case the website is accessible and there aren't any 404/500 errors even when search engine crawls, at least Google Search console isn't reporting any 404 (we have several hundred thousand pages in Google index).

But when I enable ApplicationInsights, I see many 404 error for index.html, I believe these are for SSR.

**Comment by meriturva** [comment]
I can confirm that errors is related to POST and OPTIONS call to index.html.
I really don't know if with new 3.1 version issue still present.

Sentry is really happy about it :)
![image](https://user-images.githubusercontent.com/5664195/70457917-5a9d1900-1ab1-11ea-8f0f-2f478f7228cf.png)

**Comment by rezabayesteh** [comment]
I can confirm that the issue still presents in 3.1 and as @meriturva mentioned it's very easy to reproduce:
Send OPTIONS or POST request to index.html using postman

**Comment by futureinfo** [comment]
Yes,same issue for my spa project with vuejs in 3.1.
When post a request with invalid URL  to server, then you will get that issue. 
_"System.InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request."_
but when get  with invalid URL, it works normally.

**Comment by clement-fifty** [comment]
I second futureinfo that it happens on vuejs too, but for GET requests to index.html
This is really intermittent and can't be reproduced locally (or at least I couldn't).
Again, this is happening only in production, with users having no problem whatsoever.

**Comment by vincentcastagna** [comment]
Hello. 

Still not real identified solution for this issue ?

**Comment by FunkMonkey33** [comment]
I can confirm that this still happens in 3.1 with the default settings.  

To fix this, I simply build my Angular project (I'm on Angular) in aot mode, then copy the **contents** of ClientApp\dist\ClientApp to the target's ClientApp\dist folder.  

Lame, but that' where we are.

**Comment by dreymers-goformz** [comment]
It looks like anything that is not a GET will cause that error, regardless of whether the default spa page exists or not. In my case, a misspelled POST to a controller didn't match the controller route and fell through to this middleware. The error message may be misleading, and can hide the root cause.

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to be worked on for the coming release. We will reassess the backlog following the current release and consider this item at that time. To learn more about our issue management process and to have better expectation regarding different types of issues you can read our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md).

**Comment by philip-reed** [comment]
I have just encountered the same issue and appear to have had some success by adding `MapFallbackToFile("/index.html")` to my endpoint config:

```
app.UseEndpoints(endpoints =>
{
    endpoints.MapHealthChecks("/health");   
    endpoints.MapFallbackToFile("/index.html");
    endpoints.MapControllerRoute(
        name: "default",
        pattern: "{controller}/{action=Index}/{id?}");
});
```

**Comment by miguellira** [comment]
It's a shame this issue hasn't been addressed after more than 2 years. My guess is that most .NET developers building SPA applications are either deploying their client assets separately and bypassing the use of [SpaDefaultPageMiddleware ](https://github.com/dotnet/aspnetcore/blob/master/src/Middleware/SpaServices.Extensions/src/SpaDefaultPageMiddleware.cs) altogether or living with these exceptions in their production environment.

In my case, our PaSS solution (Cloud Foundry) hits our containers with a specific `OPTIONS` request so this shows up in our logs even though the app is working fine.

My current workaround (see below) is to write a simple middleware before the call to `UseSpa` to look for that specific request and return a 404. As others have pointed out, however, you can easily DoS a server simply by making erroneous HTTP requests.

@SteveSandersonMS and @javiercn you were both helpful in previous SPA related issues I've logged. Any chance you can take a quick look at this one and provide better guidance?

```c#
...
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller}/{action=Index}/{id?}");
            });

            // HACK: Cloud Foundry's Spring Boot actuators makes an OPTIONS call to /cloudfoundryapplication
            //       https://docs.run.pivotal.io/console/using-actuators.html#troubleshoot
            //       which raises an error in .NET Core's SpaDefaultPageMiddleware. This middleware
            //       ensures a 404 is returned to minimize the noise in the logs.
            //       See https://github.com/dotnet/aspnetcore/issues/5223 for more details.
            app.Use(next => async context =>
            {
                if (context.Request.Method == HttpMethods.Options &&
                    context.Request.Path == "/cloudfoundryapplication")
                {
                    context.Response.StatusCode = StatusCodes.Status404NotFound;
                    return;
                }

                await next(context);
            });

            app.UseSpa(spa =>
            {
                spa.Options.SourcePath = "ClientApp";

                if (env.IsDevelopment())
                {
                    spa.UseAngularCliServer(npmScript: "start");
                }
            });
...
```

**Comment by caseysick** [comment]
@rezabayesteh Nice solution. Where are you defining and implementing your UseRootRewrite method? Thank you.

**Comment by Solale90** [comment]
@caseysick Add it before app.UseSpa:
```
app.UseCustomStaticFiles();
app.UseCustomSpaStaticFiles();
app.UseRouting();
app.UseCors(ServerConstants.AnyOriginCorsPolicy);
app.UseCookiePolicy();
app.UseAuthentication();
app.UseAuthorization();
app.UseSession();
app.UseCustomEndpoints();
**app.UseRootRewrite();**
app.UseCustomSpa(HostEnvironment);

```

**Comment by caseysick** [comment]
@Solale90 Thanks. Where is the UseRootRewrite method being created though? What class?

**Comment by rezabayesteh** [comment]
@caseysick Here is the complete solution:
```
public static class ApplicationBuilderExtensions
{
    public static IApplicationBuilder UseCustomEndpoints(this IApplicationBuilder app)
    {
        app.UseEndpoints(endpoints =>
        {
            endpoints.MapHub<ProgressReportHub>("/reporthub");
            endpoints.MapHub<OrdersHub>("/orderhub");
            
            endpoints.MapDefaultControllerRoute();

            endpoints.MapRazorPages()
                     .RequireHost("titifood.com", "finddishes.com");
        });

        return app;
    }
}

public class Startup
{
    public IWebHostEnvironment HostEnvironment { get; }
    public IConfiguration Configuration { get; }

    public Startup(IConfiguration configuration, IWebHostEnvironment env)
    {
        HostEnvironment = env;
        Configuration = configuration;
    }

    public void ConfigureServices(IServiceCollection services)
    {
        ...
    }

    public void Configure(IApplicationBuilder app)
    {
        ...
        app.UseCustomStaticFiles();
        app.UseCustomSpaStaticFiles();
        app.UseRouting();
        app.UseCors(ServerConstants.AnyOriginCorsPolicy);
        app.UseCookiePolicy();
        app.UseAuthentication();
        app.UseAuthorization();
        app.UseSession();
        app.UseCustomEndpoints();
        app.UseRootRewrite();
        app.UseCustomSpa(HostEnvironment);
    }
}

```

**Comment by caseysick** [comment]
**The original issue here was most likely due to incorrectly packaging the published files, in the case of an Amazon Elastic production environment anyways**

ASP.NET Core with Angular template, created with visual studio (no modifications)

Make sure your aws manifest links to the published folder, e.g. "publish/" and not a publish.zip file. Even though the aws documentation [here](https://docs.amazonaws.cn/en_us/elasticbeanstalk/latest/dg/dotnet-core-tutorial.html#dotnet-core-tutorial-launch) explains how it is permitted to add zip files to the appBundle in aws manifest, it wasn't cooperating with my zip. All the files were within the publish.zip, but it's possible aws is having trouble unzipping. 

Regardless, zipping isn't even necessary. Go to the project root file:

1. dotnet publish --configuration Release
2. Navigate to publish folder.. bin/Release/netcoreapp3.1/
3. zip -r publish.zip publish

**Don't forget to change appBundle to "publish/" in your aws-windows-deployment-manifest.json**
{
    "manifestVersion": 1,
    "deployments": {
        "aspNetCoreWeb": [
        {
            "name": "asptest",
            "parameters": {
                "appBundle": "**publish/**",
                "iisPath": "/",
                "iisWebSite": "Default Web Site"
            }
        }
        ]
    }
}

4. zip -r package.zip publish/ aws-windows-deployment-manifest.json
(upload this package to amazon elastic when you create the environment)

package.zip should contain....
aws-windows-deployment-manifest.json
publish/

**Comment by praEngineer** [comment]
On my development machine, my REACT as part of a bigger VS 2019 solution (REACT and a C# API)
![NEtutors](https://user-images.githubusercontent.com/3459509/97790021-8e869e80-1b9b-11eb-98b4-090c7058886b.png)
 runs fine in IISExpress.  Publishing "to PROD" causes host to look in ClientApp/build for index.html.  IISExpress is looking in ClientApp/public and finding Index.html there.  I have to change the Startup.cs (**ConfigureServices** and **app.UseSpa**)file depending upon where the solution is being published.

---

`
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.HttpsPolicy;
using Microsoft.AspNetCore.SpaServices.ReactDevelopmentServer;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace [redacted]
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {

            services.AddControllersWithViews();

            // In production, the React files will be served from this directory
            services.AddSpaStaticFiles(configuration =>
            {
                // for IIS Express
                // configuration.RootPath = "ClientApp";

                // for DiscountASP
                configuration.RootPath = "ClientApp/build";
            });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseSpaStaticFiles();

            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller}/{action=Index}/{id?}");
            });

            app.UseSpa(spa =>
            {
                // for IISExpress
                // spa.Options.SourcePath = System.IO.Path.Join(**env.ContentRootPath, "ClientApp"**); // "ClientApp/build"; //
                
                // for DiscountASP
                spa.Options.SourcePath = System.IO.Path.Join(env.ContentRootPath, "ClientApp/build"); //"ClientApp"); 

                //https://github.com/dotnet/aspnetcore/issues/6342#issue-395713046
                spa.Options.StartupTimeout = System.TimeSpan.FromSeconds(300);
                if (env.IsDevelopment())
                {
                    spa.UseReactDevelopmentServer(npmScript: "start");
                }
            });
        }
    }
}
`

**Comment by jtillman** [comment]
I just hit this issue today and hopefully I can add another piece of investigation detail.

After publishing my application to a release folder, my folder structure looks something like this:
│.  <-- Working directory
│└ release
│  └───ClientApp
│             └───dist

My .Net Application is within the `release` folder and the angular app is in `release/ClientApp/dist`.

If I run `dotnet .\release\MyApp.dll` I reproduce the error message given in this thread:
System.InvalidOperationException: The SPA default page middleware could not return the default page '/index.html'

But if I change directories inside of the `release` folder then run `dotnet .\MyApp.dll`, The angular application runs fine. 

This gives me the assumption that the Spa library is somehow depending on the process path and not the path of the application binary.

**Comment by maxima120** [comment]
I've just had the same. it appeared ClientApp directory had not enough permissions (Linux). fixed by simple `chmod`

**Comment by snebjorn** [comment]
I can confirm that this is still an issue in .NET 5
I see many comments that are related to misconfiguration. Perhaps and admin can mark those as "not relevant".

This issue is about POST,OPTIONS calls throwing in production when the configuration is correct and working. This https://github.com/dotnet/aspnetcore/issues/5223#issuecomment-433394061 explains it perfectly. Thank you for that explanation.

The workaround proposed here https://github.com/dotnet/aspnetcore/issues/5223#issuecomment-678530768 does work.
However I discovered that it's not only calls to the base path "/" that throws. Any path that isn't mapped to a controller will throw. So these will also throw:
- OPTIONS /wubba
- POST /luppa
- PUT /dub
- PATCH /dub/dub

**Comment by Donistivanov** [comment]
I applied the `FromBody` attribute to the complex type parameters of my actions and things seem to have quieted down.

**Comment by maxima120** [comment]
"Any path that isn't mapped to a controller will throw. "

Why shouldn't it? Could you please explain why post/put should work on a pure get resource?

**Comment by snebjorn** [comment]
> Why shouldn't it? Could you please explain why post/put should work on a pure get resource?

This issue is about the backend throwing is error
> System.InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request. Your application is running in Production mode, so make sure it has been published, or that you have built your SPA manually. Alternatively you may wish to switch to the Development environment.

When calling a bogus resource then I'd expect the backend to return 404 without incident. In other words. Not throw an exception about the SPA default page middleware.

**Comment by espenrl** [comment]
A resource which does NOT exist should end in a 404 response.

**Comment by maxima120** [comment]
a) if we talk http codes - then i think 405 more appropriate (the index.html is there). b) yeah well a lot of things are not exactly to my liking so what. you send a bogus request and get slightly wrong response wow, 15 pages discussion.

**Comment by snebjorn** [comment]
> a) if we talk http codes - then i think 405 more appropriate (the index.html is there). b) yeah well a lot of things are not exactly to my liking so what. you send a bogus request and get slightly wrong response wow, 15 pages discussion.

We're not talking about http codes. You should read the OP. And perhaps also https://github.com/dotnet/aspnetcore/issues/5223#issuecomment-433394061

As stated

> > This issue is about the backend throwing this error
> 
> System.InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request. Your application is running in Production mode, so make sure it has been published, or that you have built your SPA manually. Alternatively you may wish to switch to the Development environment.

When it shouldn't. Nothing more.

**Comment by emilssonn** [comment]
Another possible workaround is:
```
app.UseWhen(context => HttpMethods.IsGet(context.Request.Method), builder =>
{
    builder.UseSpa(spa =>
    {
    });
});
```
This will only run the SpaMiddleware for Get requests, letting all other request pass to the next middleware.

**Comment by nsunmaz** [comment]
> SSR isn't the problem. You should set path in `ConfigureServices()` method via `services.AddSpaStaticFiles(configuration => configuration.RootPath = $"ClientApp/dist");`. Then in `Configure` you shouldn't specify source path:
> 
> ```cs
> app.UseSpaStaticFiles();
> app.UseSpa(configuration => { /*spa.Options.SourcePath = "ClientApp";*/ });
> ```
> 
> `spa.Options.SourcePath` is only used in development build judging from its' description.

Thanks, this solution works perfecly.

**Comment by HEBOS** [comment]
The thing is that the problem happens when there is a pending attack.
Someone is trying to POST request to a path which isn't handled by any middleware, so SPA middleware terminates it with that message.
Clearly, SPA middleware needs to be amended to address that issue.

To address attack in the first place (as that is the priority), we need to terminate the further processing and return 404, but that needs to happen before UseSpa().

First, we need to create a constant in Startup class, so we don't duplicate "ClientApp/dist".

```
public class Startup() {
    private const string SpaPath = "ClientApp/dist";
}
```

Next, we need to create an builder extension.

```
public static class ApplicationBuilderExtensions
    {
        public static IApplicationBuilder UseRootRewrite(this IApplicationBuilder builder, string spaPath)
        {
            var socks = "/sockjs-node";

            builder.Use((context, next) =>
            {
                if (!HttpMethods.IsGet(context.Request.Method) && !context.Request.Path.StartsWithSegments(socks))
                {
                    //context.Request.Method = "GET";
                }

                if (!context.Request.Path.StartsWithSegments(new PathString(socks)) &&
                    !context.Request.Path.StartsWithSegments(new PathString($"/{spaPath}")))
                {
                    if (!context.Response.HasStarted)
                    {
                        context.Response.StatusCode = 404;
                        context.Response.CompleteAsync().GetAwaiter().GetResult();
                    }
                }

                return null;
            });

            return builder;
        }
    }
```

And finally hook it before UseSpa().

```
public class Startup() {
    ...
    
    public void Configure(IApplicationBuilder app) {
        app.UseRootRewrite(SpaPath);
        app.UseSpa(config => {});
    }
}
```

**Comment by KalpeshPopat** [comment]
I am trying to get my production server running on https and getting the same error.

"The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request."

However i am getting the error only when apache is configured to receive requests on https and proxy / reverse proxy is on http
When both apache and proxy are configured on http then the system works correctly.

**Comment by KalpeshPopat** [comment]
I have solved my problem. all that was needed in the apache configuration was this 

ProxyPreserveHost On

this ensures the headers of the original requests are preserved even when using proxypass

**Comment by rlm42** [comment]
I am getting this error.. tried everything to fix it, mine works fine in Development mode just not when Publishing/running in Production mode. 

I've uploaded my whole project to https://github.com/rlm42/angular12

If someone could please have a look I would be grateful! Also you have to copy the Photos folder to the root directory when published

**Comment by KalpeshPopat** [comment]
in the startup.cs you need to add
```
            app.UseForwardedHeaders(new ForwardedHeadersOptions
            {
                ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
            });

```
what is your production environment ?

**Comment by rlm42** [comment]
> in the startup.cs you need to add
> 
> ```
>             app.UseForwardedHeaders(new ForwardedHeadersOptions
>             {
>                 ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
>             });
> ```
> 
> what is your production environment ?

  I set "ASPNETCORE_ENVIRONMENT": "Development" in appsettings.json

**Comment by KalpeshPopat** [comment]
what i want to know is where are you running the system after publishing it.....
os: linux or windows?
web server: apache, iis or something else?
and you need to check everything given in the docs of ms under Host and Deploy section, here is the link: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/?view=aspnetcore-5.0

**Comment by rlm42** [comment]
IIS, I just need someone to download and have a look, I'm not pointing the to the ClientApp properly or specifing a way to handle Production server

**Comment by KalpeshPopat** [comment]
You seem to have the solution, nice way to ask for help ? what you need to understand is that your production environment issues cannot be solved by looking at the source code.

you should be mapping the content of your publish folder which is at following path "angular12/WebAPI with Angular/WebAPI with Angular/bin/Release/net5.0/publish/" correctly under iis.

If not then you need to read the link i have shared earlier and click on iis.

**Comment by rlm42** [comment]
Mate I did ask for help nicely, read my first post again. What's your problem? If you don't want to help that's fine. Been stuck on this for a while. I just hosted the server and client seperately and it works fine. I think that's the way to go. Thanks for responding anyway!

**Comment by KalpeshPopat** [comment]
my bad, you were prompting suggestion to the person who was trying to help you, it was sort of distracting. anyways good to know your problem is solved. i would still try and host server and client together, let's try again ?

the only files that really has any say on the hosted environment is startup.cs and appsetting file and i notice one piece of code that is not consistent in the startup.cs file

the code on line no. 52 should point to your published folder of angular - this is correct
the code on line no. 96 should point to your source code folder of angular - this is wrong, correct value as per your folder structure is "ClientApp"

once this is corrected, try publishing again from step 1 to z

It will be easy to diagnose the issue if you can share your hosted environment configuration. cheers.

**Comment by rlm42** [comment]
> my bad, you were prompting suggestion to the person who was trying to help you, it was sort of distracting. anyways good to know your problem is solved. i would still try and host server and client together, let's try again ?
> 
> the only files that really has any say on the hosted environment is startup.cs and appsetting file and i notice one piece of code that is not consistent in the startup.cs file
> 
> the code on line no. 52 should point to your published folder of angular - this is correct
> the code on line no. 96 should point to your source code folder of angular - this is wrong, correct value as per your folder structure is "ClientApp"
> 
> once this is corrected, try publishing again from step 1 to z
> 
> It will be easy to diagnose the issue if you can share your hosted environment configuration. cheers.

Sorry bro all good. I did that this, though the output path when published is ClientApp/dist. Where is the hosted environment configuration? I appreciate your help

![image](https://user-images.githubusercontent.com/56745971/128455560-71557bd1-67c4-422b-aeab-ef174a178a74.png)

**Comment by KalpeshPopat** [comment]
i need to see your published structure and its environment and configuration. I thought you were using iis please confirm, since the error file appears to be of kestrel.

do you want to take this offline ? once sorted we can publish the solution here on git.

**Comment by rlm42** [comment]
> i need to see your published structure and its environment and configuration. I thought you were using iis please confirm, since the error file appears to be of kestrel.
> 
> do you want to take this offline ? once sorted we can publish the solution here on git.

Ok add me on Skype, rlm042.

**Comment by buchatsky** [comment]
In VS 2022 with .Net Core 6 the standard ASP.Net Angular project template does not return index.html at all in Production mode.
And I fixed that with the following code:

```
//app.UseStaticFiles();
if (!app.Environment.IsDevelopment())
{
    app.UseFileServer(new FileServerOptions
    {
        FileProvider = new PhysicalFileProvider(Path.Combine(app.Environment.ContentRootPath, "ClientApp/dist"))
    });
}

```

**Comment by HappyNomad** [comment]
Finally, I figured out this framework bug's root cause and how to work around it.  You work around it by fixing another bug that you may not even realize is in your code.  The other bug, and how to fix it (and thus work around the framework bug), are [described here](https://stackoverflow.com/questions/52358498).

**Comment by akonyer** [comment]
Thank you @Redart98

This is a huge gaping DOS hole in the .net core SPA framework. Yes, it makes sense to redirect routes to the SPA so it can handle routing on the front end, but I'm getting POST requests to index.html that are being redirected to the SPA middleware. It makes no sense.

**Comment by cssriraman** [comment]
> 

Hi,
I am getting error as below:
`'IApplicationBuilder' does not contain a definition for 'Environment' and no accessible extension method 'Environment' accepting a first argument of type 'IApplicationBuilder' could be found`

Do you have any solution for that?

**Comment by cssriraman** [comment]
> In VS 2022 with .Net Core 6 the standard ASP.Net Angular project template does not return index.html at all in Production mode. And I fixed that with the following code:
> 
> ```
> // Serve files from wwwroot
> app.UseStaticFiles();
> // In production, serve Angular files and default page from ClientApp/dist
> if (!app.Environment.IsDevelopment())
> {
>     app.UseFileServer(new FileServerOptions
>     {
>         FileProvider = new PhysicalFileProvider(Path.Combine(app.Environment.ContentRootPath, "ClientApp/dist"))
>     });
> }
> ```
> 
> PS. But it also requires changing the SPA deployment folder from wwwroot to ClientApp/dist (as it was in ASP.Net Core 3.1 template): `<!--<RelativePath>wwwroot\%(RecursiveDir)%(FileName)%(Extension)</RelativePath>--> <RelativePath>%(DistFiles.Identity)</RelativePath>`
Thank you @buchatsky

I am getting error as below:
'IApplicationBuilder' does not contain a definition for 'Environment' and no accessible extension method 'Environment' accepting a first argument of type 'IApplicationBuilder' could be found

Do you have any solution for that?

**Comment by wtdrog** [comment]
I have this issue too with ASP.NET Core 6 and Microsoft.AspNetCore.SpaServices.Extensions with version 6.0.22 referenced in .csproj.
As I see it, [SpaDefaultPageMiddleware](https://github.com/dotnet/aspnetcore/blob/28b2bfd3ac67f07a5985550f1bec2e659af02aea/src/Middleware/Spa/SpaServices.Extensions/src/SpaDefaultPageMiddleware.cs#L37) uses StaticFileMiddleware to serve a default page, assuming that it would run the next middleware part only when there is no such file in the filesystem, but actually [StaticFileMiddleware](https://github.com/dotnet/aspnetcore/blob/28b2bfd3ac67f07a5985550f1bec2e659af02aea/src/Middleware/StaticFiles/src/StaticFileMiddleware.cs#L64) does not serve the file not because there is none, but because the request method is wrong.
As SpaDefaultPageMiddleware is a catch-all middleware that should just serve a single file, I think it should handle the case when a request was sent with an inappropriate header and return a 405 status code instead of trying to serve the file with StaticFileMiddleware.

**Comment by mkArtakMSFT** [comment]
Thanks everyone for your comments.
This is not area we plan to make investments in the long term, so we're closing this issue.
