### ISSUE TITLE
Hot Reload not working: Cannot update because an inferred delegate type has changed.

### ISSUE THREAD

**Issue by westonwalker** [dotnet/aspnetcore#52270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hot reload is not working for 1 of my projects. I have 2 separate issues depending on how I run the app.

**Using dotnet watch:**
Hot reload is alerted a change was made but outputs no hot reload changes to apply.
![image](https://github.com/dotnet/aspnetcore/assets/66449990/e30d98a5-6ea0-408c-89f3-ff0a9dcad0a6)

**Using Start without debugging:**
When a change is made, the app fails to update with the following error messages.
```
16:09 51.48 DotnetJobs (Web server): [Error] Errors found in application:

C:\code\DotnetJobs\DotnetJobs\DotnetJobs.csproj(0,0,0,0): Cannot update because an inferred delegate type has changed.

16:09 51.48 [Error] C:\code\DotnetJobs\DotnetJobs\DotnetJobs.csproj (line 1): error CS8984: Cannot update because an inferred delegate type has changed.
16:09 51.48 Invalid changes were found. Please refer to the Error List window to fix those issues.
```

### Expected Behavior

The app to reload and show changes.

### Steps To Reproduce

This app is a minimal api app that returns Razor components via the RazorComponentResult class.

1. Run dotnet watch or start in visual studio.
2. Make changes to app.

### Exceptions (if any)

none

### .NET Version

8.0.100

**Comment by Stefanu83** [comment]
I have the same issue in Visual Studio 17.8.1 / Blazor project when even changing an element (i.e. changing the style).

**Comment by davidlopez9210** [comment]
I have the same isssue using Microsoft Visual Studio Enterprise 2022 (64-bit) - Version 17.8.2 for a Console Application with .NET 8

**Comment by dennis-jones** [comment]
I also have this issue. VS Pro 17.7 and Rider 2023.2.3.

**Comment by tmat** [comment]
I believe this is fixed by https://github.com/dotnet/roslyn/pull/70501 in 17.9.

**Comment by Stefanu83** [comment]
I just installed the preview version of Visual Studio 17.9.0 Preview 1.1 (as far as I know the most current version). 

Still get this error: 

`11:55 00.14 [Error] C:\Users\**\source\repos\**\**\**.csproj (line 1): error CS8984: Cannot update because an inferred delegate type has changed.
`

And this was with a very mundane change in a Razor page (adding a span with the text test).

**Comment by jonblankenship** [comment]
I was getting the error as well, and discovered that it was due to an optional parameter on a minimal API definition.

Hot reload fails when this is present in my Program.cs:
```
app.MapGet("Hello",  (HttpContext httpContext, string greeting = "") => 
    Results.Ok(string.IsNullOrWhiteSpace(x) ? "Hi!" : greeting));
```

Hot reload starts working again when I make the `greeting` parameter not optional:
```
app.MapGet("Hello",  (HttpContext httpContext, string greeting) => 
    Results.Ok(string.IsNullOrWhiteSpace(x) ? "Hi!" : greeting));
```
