### ISSUE TITLE
Issue with OutputCache in Blazor SSR

### ISSUE THREAD

**Issue by zubairkhakwani** [dotnet/aspnetcore#55534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

 Initially, everything functions as expected. However, upon adding the OutputCache attribute, two significant issues arise

1. **Script Functionality Breakdown:** Upon revisiting the cached Home page, script functionality becomes non-responsive. Despite logging within the OnUpdate method, the console remains empty, indicating a failure in executing JavaScript functionality. This impedes the user experience and disrupts the intended behavior of the page.
2. **Excessive Reloading with Hash Navigation** Furthermore, when navigating to a link within the same page containing a hash (#element), Blazor's JavaScript file (blazor.web.js) inexplicably reloads the page multiple times. 

I am using BlazorPageScript nuget package provided by @MackinnonBuck  to work with PageScript

If I remove `@attribute [OutputCache(Duration = 2000)]` it works fine.

Additionally, I've created a Video demonstrating the precise steps to replicate the issues.

https://github.com/dotnet/aspnetcore/assets/38009549/f78fba32-ca14-4874-90dc-5cd0105652c5

### Expected Behavior

<PageScript> should works and navigating to #elements in same page should not reload pages multiple times.

### Steps To Reproduce

 Repo link to reproduce this issue.

[minimalistic project which reproduces this issue](https://github.com/zubairkhakwani/BlazorCacheIssue)

### .NET Version

8.0.204

**Comment by zubairkhakwani** [comment]
@danroth27 @SteveSandersonMS @mkArtakMSFT I believe that addressing the issue related to Output Cache is crucial for enhancing the performance and scalability of SSR websites. Since this appears to be a solvable bug (Hopefully :D), I propose considering its resolution for inclusion in the .NET 9 release. Thank you for addressing this matter & Thank you for Blazor, Have a good day.

**Comment by LeszekKalibrate** [comment]
still not fixed?

**Comment by javiercn** [comment]
> 2\. **Excessive Reloading with Hash Navigation** Furthermore, when navigating to a link within the same page containing a hash (#element), Blazor's JavaScript file (blazor.web.js) inexplicably reloads the page multiple times.

This might have been fixed https://github.com/dotnet/aspnetcore/pull/63449

**Comment by ilonatommy** [comment]
@javiercn, I tried with rc2, it's not fixed. The symptoms are changed:

```
Enhanced navigation failed for destination http://localhost:5133/#contact-us. Falling back to full page load.
```

<img width="2545" height="1306" alt="Image" src="https://github.com/user-attachments/assets/f841b7aa-3653-4795-be66-00ec530526c8" />

**Comment by ilonatommy** [comment]
I confirmed that my reproduction was done with rc1, not rc2. It did not contain the fix: https://github.com/dotnet/aspnetcore/pull/63449. I will start the backport.

**Comment by ilonatommy** [comment]
Fixed by https://github.com/dotnet/aspnetcore/issues/55534.
