### ISSUE TITLE
HotReload In BlazorWebAssembly Dont Work Correctly

### ISSUE THREAD

**Issue by shabanelmogy-os** [dotnet/aspnetcore#59813]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

i use blazor webassembly standalone in .net 9 hotreload not work and this make development very difficult and waste time 
please solve this problem because most of blazor prgrammer might migrate to another framework 
if anyone has production app it will be big problem

### .NET Version

.net 9

**Comment by javiercn** [comment]
@shabanelmogy-os thanks for contacting us.

Can you provide a concrete description of what exactly is not working? otherwise is impossible for us to take any action.

**Comment by danroth27** [comment]
@shabanelmogy-os It would help if you could include the following specific details:

- What operating system you are using?
- What tool are you using to perform the hot reload? VS, VSCode, or `dotnet watch`
- What sort of change are you trying to hot reload? What is the original code and what change did you make?
- Are there any errors in the hot reload output window?

@phil-allen-msft FYI

**Comment by ghostinside** [comment]
+1, just updated to VS.NET  17.12.4, it seems the .net 9 was added with an update, but the web assembly project hot reload stopped working.  rebuild (ctrl+R tries to open the browser all the time), the console shows that the hot reload was applied, and the application crashed in the browser.

web assemble, not hosted project

**Comment by rabberbock** [comment]
I just upgraded one of our projects to .NET 9 and the blazor wasm hot reload just does not work well anymore. I use dotnet watch from cli on a Mac.

Here are some error logs from my latest run. I was not doing anything fancy, just changing css classes.

<img width="1487" alt="Image" src="https://github.com/user-attachments/assets/249a2dd8-99be-45e9-9b5e-c627c1002ca4" />

<img width="573" alt="Image" src="https://github.com/user-attachments/assets/f3224436-dd1a-47f6-941c-1a0647a964e7" />

[Reddit thread ](https://www.reddit.com/r/Blazor/comments/1h2rnko/ive_defended_hot_reload_since_the_start_but_has/)as well.

For now I am going to stick with the `dotnet watch --no-hot-reload` option. 

Let me know if you want anything specific and I can try to pull it together. Thanks!

**Comment by danroth27** [comment]
@rabberbock Thanks for sharing this additional information.

@lewing Can you take a look and see if this is something we need to investigate on the runtime side?

**Comment by ghostinside** [comment]
my case the project is still .net 8, dot net watch, when you rebuild the first time, it works till the first hot reload, during the hot reload I see that the changed file was removed and added (cli messages in the console), and the second time it starts warning that we have unknown component on the page & need to add a namespace, the hot reload in console still a success, browser app crashed

**Comment by lewing** [comment]
cc @tmat

**Comment by tmat** [comment]
@rabberbock
>  ctrl+R tries to open the browser all the time

This is tracked by https://github.com/dotnet/sdk/issues/46175

**Comment by tmat** [comment]
@rabberbock
Would you mind setting env variable `Microsoft_CodeAnalysis_EditAndContinue_LogDir=%temp%\HotReloadLog` before starting `dotnet watch --verbose` and sharing the verbose output and content of the log directory? 

Note, the logs will contain pieces of your source code. You can use [VS Feedback](https://developercommunity.visualstudio.com/home) if you prefer not sharing the code publicly.

**Comment by ghostinside** [comment]
this is also because "as usual"

console:

`
dotnet watch ⌚ File changed: .\Features\Shipments\ShipmentDetails.razor.
dotnet watch 🔥 Hot reload of changes succeeded.
dotnet watch ⌚ File changed: .\Features\Shipments\ShipmentDetails.razor.
dotnet watch 🔥 Hot reload of changes succeeded.
dotnet watch ⌚ File changed: .\Features\Shipments\ShipmentDetails.razor.
dotnet watch ⌚ No hot reload changes to apply.
`

browser:

`
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not load file or assembly 'essContactListAsync>b__8_0, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies.
System.IO.FileNotFoundException: Could not load file or assembly 'essContactListAsync>b__8_0, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies.
File name: 'essContactListAsync>b__8_0, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
`

this does not exist in real live - essContactListAsync

refresh does not help, just rebuild & refresh

.NET SDK:
 Version:           8.0.405
 Commit:            fb1830d421
 Workload version:  8.0.400-manifests.87fdb0b5
 MSBuild version:   17.11.9+a69bbaaf5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.405\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [aspire]
   Installation Source: VS 17.11.35327.3
   Manifest Version:    8.1.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.1.0\WorkloadManifest.json
   Install Type:              Msi

 [maui-windows]
   Installation Source: VS 17.11.35327.3
   Manifest Version:    8.0.82/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.82\WorkloadManifest.json
   Install Type:              Msi

 [maccatalyst]
   Installation Source: VS 17.11.35327.3
   Manifest Version:    18.0.8303/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\18.0.8303\WorkloadManifest.json
   Install Type:              Msi

 [ios]
   Installation Source: VS 17.11.35327.3
   Manifest Version:    18.0.8303/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\18.0.8303\WorkloadManifest.json
   Install Type:              Msi

 [wasm-tools-net6]
   Installation Source: VS 17.11.35327.3
   Manifest Version:    8.0.12/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.workload.mono.toolchain.net6\8.0.12\WorkloadManifest.json
   Install Type:              Msi

 [android]
   Installation Source: VS 17.11.35327.3
   Manifest Version:    34.0.113/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.113\WorkloadManifest.json
   Install Type:              Msi


Host:
  Version:      8.0.12
  Architecture: x64
  Commit:       89ef51c5d8

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.203 [C:\Program Files\dotnet\sdk]
  5.0.214 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.321 [C:\Program Files\dotnet\sdk]
  8.0.112 [C:\Program Files\dotnet\sdk]
  8.0.206 [C:\Program Files\dotnet\sdk]
  8.0.403 [C:\Program Files\dotnet\sdk]
  8.0.405 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  arm64 [C:\Program Files\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\arm64\InstallLocation]
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by tmat** [comment]
@ghostinside
Please file a separate issue. Include repro steps or logs as described in https://github.com/dotnet/aspnetcore/issues/59813#issuecomment-2620300257.

**Comment by ghostinside** [comment]
@tmat i think this the same hot reload issue, that is why I posted it here

**Comment by rabberbock** [comment]
@tmat Will try to get to this over the weekend.

**Comment by rabberbock** [comment]
@tmat Can you please point me to where I can upload the output to the VS Feedback site? Also, I noticed that the the browser that gets launched when Blazor starts up has pretty good hot reloading, but once I open a new browser or reload the page it starts breaking.

**Comment by danroth27** [comment]
> [@tmat](https://github.com/tmat) Can you please point me to where I should upload the output to the VS Feedback site. Also, I noticed that the the browser that gets launched when Blazor starts up has pretty good hot reloading, but once I open a new browser or reload the page it starts breaking.

@rabberbock Reproduce the issue in Visual Studio using the requested settings and then go to Help > Send Feedback > Report a Problem to create a feedback ticket. You can then attach additional information to the feedback ticket as needed.

**Comment by tmat** [comment]
@rabberbock Thanks for the logs, will take a look. Would you mind also uploading the verbose output of dotnet-watch?

**Comment by kevin-mueller** [comment]
Since .NET 9.0.200 hot reload fails for me with this message:

```
warning CS8785: Generator 'RazorSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentException' with message 'The hintName 'Pages_Settings_razor.g.cs' of the added source file must be unique within a generator. (Parameter 'hintName')'.
System.ArgumentException: The hintName 'Pages_Settings_razor.g.cs' of the added source file must be unique within a generator. (Parameter 'hintName')
   at Microsoft.CodeAnalysis.AdditionalSourcesCollection.Add(String hintName, SourceText source)
   at Microsoft.CodeAnalysis.SourceOutputNode`1.AppendOutputs(IncrementalExecutionContext context, CancellationToken cancellationToken)
-----
```

It might be important to note that the file I've edited is in a razor class library.

**Comment by jaredpar** [comment]
@333fred PTAL

**Comment by brettzook** [comment]
Yesterday, I updated to Visual Studio 17.13 / SDK **9.0.200**, eager to see how Hot Reload behaved since #45810 had been closed and was included in this update.

My first few tests with `dotnet watch` were great. I was able to make 7-8 changes in a row and they all reloaded successfully, which is something that hasn't happened ever since move from .net 8 to .net 9. I thought it was time to celebrate.

Today, in a different spot within my app, I'm not able to make even a single change to an attribute of a Blazor component. The powershell console shows 
![Image](https://github.com/user-attachments/assets/a7276123-201c-46c8-ab9c-ea9366ee7b4a)

But the browser console shows
![Image](https://github.com/user-attachments/assets/6874f9d6-7e2c-4c02-8fac-80de20818657)

Note the mangled assembly name `0, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60`. Obviously it's not going to find that, there is no "0" assembly. This appears to be the same issue @ghostinside [reported above](https://github.com/dotnet/aspnetcore/issues/59813#issuecomment-2622845850).

What is the most helpful next step? I'm happy to provide logging details if desired.

Will #45810 be reopened? Should the mangled assembly name problem be a separate issue?

**Comment by ghostinside** [comment]
i also have updated vs to 17.13 SDK 8, but still second hot reload crash with an invalid frame (in the browser), console says all successful

**Comment by brettzook** [comment]
I carved out a subset of the real project that will run standalone and can be shared, but unfortunately it doesn't exhibit the problem.

I'll take some more time to see if I can add enough back into it so that the problem is replicated.

**Comment by brettzook** [comment]
@tmat I have a stripped-down project where the issue happens reliably. It happens to make use of DevExpress Blazor nuget packages which are licensed, though those packages aren't directly related to the issue as far as I can tell. Do you have a means to restore the packages on your side (maybe trial license?) or do I need to remove them before sharing?

![Image](https://github.com/user-attachments/assets/c0cc20b1-fda5-4a51-a578-e2e8aae98e84)

**Comment by ghostinside** [comment]
@brettzook interesting, we use Telerik

**Comment by tmat** [comment]
@brettzook Removing the packages would help, if you don't mind. Thanks!

**Comment by 333fred** [comment]
@kevin-mueller does your issue reproduce consistently? If so, would you be able to either share a repro solution, or share more info about how your solution is setup? I'm unable to reproduce that with a few simple Blazor+Razor Class Library tests, but very possible there's some complication that I'm missing in your setup.

**Comment by kevin-mueller** [comment]
@333fred While trying to reproduce the issue in a new project, I've figured out what was wrong.
In the .csproj of my razor class library, I've had a couple of `<AdditionalFiles Include="Components\Component.razor" />` tags, which lead to the hot reload breaking.
I removed them and it works fine now. Sorry for the confusion!

**Comment by brettzook** [comment]
@tmat I'm working on hacking out all the references to DevExpress so I can remove the nuget package references. My app has about 20 Pages and about as many subcomponents, that nearly all rely on a DevExpress component, so after removing those there's next to nothing left.

What I'm finding is that the success rate of Hot Reload seems to be tied to the number of Pages/components in the app. For example, if I delete all my pages except one (and leaving all DevExpress stuff in place), Hot Reload worked on the first try and continued to work for multiple changes after that.

But as soon as I add the rest of the 20 pages back, Hot Reload fails on the very first try.

When I removed 10 of my pages, Hot Reload worked for 2-3 changes then started failing.

It's not clear from that if the issue is due to the use of DevExpress components, or just having a lot of any type of component, so I'm creating a bunch of dummy Pages using only out-of-box Blazor controls to take the place of my custom code.

My end goal is still to provide you with a non-DevExpress dependent project you can run and reproduce the error.

**Comment by 333fred** [comment]
> [@333fred](https://github.com/333fred) While trying to reproduce the issue in a new project, I've figured out what was wrong. In the .csproj of my razor class library, I've had a couple of `<AdditionalFiles Include="Components\Component.razor" />` tags, which lead to the hot reload breaking. I removed them and it works fine now. Sorry for the confusion!

Thanks for confirming. I'll hide our messages to avoid getting in the way of the main bug.

**Comment by tmat** [comment]
@333fred Shouldn't a build error be reported? It's not ideal that we only fail in Hot Reload.

**Comment by tmat** [comment]
> My end goal is still to provide you with a non-DevExpress dependent project you can run and reproduce the error.

Much appreciated!

**Comment by 333fred** [comment]
> Shouldn't a build error be reported? It's not ideal that we only fail in Hot Reload.

https://github.com/dotnet/razor/pull/11498

**Comment by ghostinside** [comment]
`crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not load file or assembly 'uctDetails>b__0, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies.
System.IO.FileNotFoundException: Could not load file or assembly 'uctDetails>b__0, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies.
File name: 'uctDetails>b__0, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Shipping.Features.Shipments.ShipmentDetails.BuildRenderTree(RenderTreeBuilder pmentExternalEntityAsync>b__0) in d:\work\Shipping-Core\Shipping\Features\Shipments\ShipmentDetails.razor:line 14
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
Dt @ blazor.webassembly.js:1
(anonymous) @ invoke-js.ts:176
Ll @ invoke-js.ts:276
$func349 @ dotnet.native.wasm:0x1f99d
$func245 @ dotnet.native.wasm:0x1be44
$func238 @ dotnet.native.wasm:0xf011
$func272 @ dotnet.native.wasm:0x1d062
$func3187 @ dotnet.native.wasm:0xe8853
$func2507 @ dotnet.native.wasm:0xbe535
$func2506 @ dotnet.native.wasm:0xbe4c5
$func1876 @ dotnet.native.wasm:0x9a58b
$func349 @ dotnet.native.wasm:0x1fa21
$func245 @ dotnet.native.wasm:0x1be44
$func238 @ dotnet.native.wasm:0xf011
$func272 @ dotnet.native.wasm:0x1d062
$func3187 @ dotnet.native.wasm:0xe8853
$func2507 @ dotnet.native.wasm:0xbe535
$func2513 @ dotnet.native.wasm:0xbed59
$func2537 @ dotnet.native.wasm:0xc13b0
$mono_wasm_invoke_method_bound @ dotnet.native.wasm:0xa4fe
Module._mono_wasm_invoke_method_bound @ dotnet.native.js:8
kr @ invoke-cs.ts:273
(anonymous) @ invoke-cs.ts:247
invokeDotNetFromJS @ blazor.webassembly.js:1
invokeDotNetMethod @ blazor.webassembly.js:1
invokeDotNetStaticMethod @ blazor.webassembly.js:1
nt._internal.applyHotReload @ blazor.webassembly.js:1
(anonymous) @ aspnetcore-browser-refresh.js:188
applyDeltas_legacy @ aspnetcore-browser-refresh.js:182
applyBlazorDeltas @ aspnetcore-browser-refresh.js:237
BlazorHotReloadDeltav3 @ aspnetcore-browser-refresh.js:49
connection.onmessage @ aspnetcore-browser-refresh.js:57Understand this errorAI
2blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not load file or assembly 'dGrid>d__63, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies.
System.IO.FileNotFoundException: Could not load file or assembly 'dGrid>d__63, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies.
File name: 'dGrid>d__63, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Shipping.Features.Shipments.ShipmentDetails.BuildRenderTree(RenderTreeBuilder pmentExternalEntityAsync>b__0) in d:\work\Shipping-Core\Shipping\Features\Shipments\ShipmentDetails.razor:line 14
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
Dt @ blazor.webassembly.js:1
(anonymous) @ invoke-js.ts:176
Ll @ invoke-js.ts:276
$func349 @ dotnet.native.wasm:0x1f99d
$func245 @ dotnet.native.wasm:0x1be44
$func238 @ dotnet.native.wasm:0xf011
$func272 @ dotnet.native.wasm:0x1d062
$func3187 @ dotnet.native.wasm:0xe8853
$func2507 @ dotnet.native.wasm:0xbe535
$func2506 @ dotnet.native.wasm:0xbe4c5
$func1876 @ dotnet.native.wasm:0x9a58b
$func349 @ dotnet.native.wasm:0x1fa21
$func245 @ dotnet.native.wasm:0x1be44
$func238 @ dotnet.native.wasm:0xf011
$func272 @ dotnet.native.wasm:0x1d062
$func3187 @ dotnet.native.wasm:0xe8853
$func2507 @ dotnet.native.wasm:0xbe535
$func2513 @ dotnet.native.wasm:0xbed59
$func2537 @ dotnet.native.wasm:0xc13b0
$mono_wasm_invoke_method_bound @ dotnet.native.wasm:0xa4fe
Module._mono_wasm_invoke_method_bound @ dotnet.native.js:8
kr @ invoke-cs.ts:273
(anonymous) @ invoke-cs.ts:247
invokeDotNetFromJS @ blazor.webassembly.js:1
invokeDotNetMethod @ blazor.webassembly.js:1
invokeDotNetStaticMethod @ blazor.webassembly.js:1
nt._internal.applyHotReload @ blazor.webassembly.js:1
(anonymous) @ aspnetcore-browser-refresh.js:188
applyDeltas_legacy @ aspnetcore-browser-refresh.js:182
applyBlazorDeltas @ aspnetcore-browser-refresh.js:237
BlazorHotReloadDeltav3 @ aspnetcore-browser-refresh.js:49
connection.onmessage @ aspnetcore-browser-refresh.js:57Understand this errorAI
2blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not load file or assembly 'ionAsync>d__8, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies.
System.IO.FileNotFoundException: Could not load file or assembly 'ionAsync>d__8, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies.
File name: 'ionAsync>d__8, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Shipping.Features.Shipments.ShipmentDetails.BuildRenderTree(RenderTreeBuilder pmentExternalEntityAsync>b__0) in d:\work\Shipping-Core\Shipping\Features\Shipments\ShipmentDetails.razor:line 14
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
Dt @ blazor.webassembly.js:1
(anonymous) @ invoke-js.ts:176
Ll @ invoke-js.ts:276
$func349 @ dotnet.native.wasm:0x1f99d
$func245 @ dotnet.native.wasm:0x1be44
$func238 @ dotnet.native.wasm:0xf011
$func272 @ dotnet.native.wasm:0x1d062
$func3187 @ dotnet.native.wasm:0xe8853
$func2507 @ dotnet.native.wasm:0xbe535
$func2506 @ dotnet.native.wasm:0xbe4c5
$func1876 @ dotnet.native.wasm:0x9a58b
$func349 @ dotnet.native.wasm:0x1fa21
$func245 @ dotnet.native.wasm:0x1be44
$func238 @ dotnet.native.wasm:0xf011
$func272 @ dotnet.native.wasm:0x1d062
$func3187 @ dotnet.native.wasm:0xe8853
$func2507 @ dotnet.native.wasm:0xbe535
$func2513 @ dotnet.native.wasm:0xbed59
$func2537 @ dotnet.native.wasm:0xc13b0
$mono_wasm_invoke_method_bound @ dotnet.native.wasm:0xa4fe
Module._mono_wasm_invoke_method_bound @ dotnet.native.js:8
kr @ invoke-cs.ts:273
(anonymous) @ invoke-cs.ts:247
invokeDotNetFromJS @ blazor.webassembly.js:1
invokeDotNetMethod @ blazor.webassembly.js:1
invokeDotNetStaticMethod @ blazor.webassembly.js:1
nt._internal.applyHotReload @ blazor.webassembly.js:1
(anonymous) @ aspnetcore-browser-refresh.js:188
applyDeltas_legacy @ aspnetcore-browser-refresh.js:182
applyBlazorDeltas @ aspnetcore-browser-refresh.js:237
BlazorHotReloadDeltav3 @ aspnetcore-browser-refresh.js:49
connection.onmessage @ aspnetcore-browser-refresh.js:57Understand this errorAI
2blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not load file or assembly '_7_0>d, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies.
System.IO.FileNotFoundException: Could not load file or assembly '_7_0>d, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies.
File name: '_7_0>d, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Shipping.Features.Shipments.ShipmentDetails.BuildRenderTree(RenderTreeBuilder pmentExternalEntityAsync>b__0) in d:\work\Shipping-Core\Shipping\Features\Shipments\ShipmentDetails.razor:line 14
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)`


`File updated: .\Features\Shipments\ShipmentDetails.razor
dotnet watch 🔥 [Shipping (net8.0)] Hot reload succeeded.
dotnet watch ⌚ File updated: .\Features\Shipments\ShipmentDetails.razor
dotnet watch 🔥 [Shipping (net8.0)] Hot reload succeeded.
dotnet watch ⌚ File updated: .\Features\Shipments\ShipmentDetails.razor
dotnet watch 🔥 [Shipping (net8.0)] Hot reload succeeded.
dotnet watch ⌚ File updated: .\Features\Shipments\ShipmentDetails.razor
dotnet watch 🔥 [Shipping (net8.0)] Hot reload succeeded.
dotnet watch ⌚ File updated: .\Features\Shipments\ShipmentDetails.razor
dotnet watch 🔥 [Shipping (net8.0)] Hot reload succeeded.
dotnet watch ⌚ File updated: .\Features\Shipments\ShipmentDetails.razor
dotnet watch 🔥 [Shipping (net8.0)] Hot reload succeeded.
dotnet watch ⌚ File updated: .\Features\Shipments\ShipmentDetails.razor
dotnet watch 🔥 [Shipping (net8.0)] Hot reload succeeded.
dotnet watch ⌚ File updated: .\Features\Shipments\ShipmentDetails.razor
dotnet watch 🔥 [Shipping (net8.0)] Hot reload succeeded.
dotnet watch ⌚ File updated: .\Features\Shipments\ShipmentDetails.razor
dotnet watch 🔥 [Shipping (net8.0)] Hot reload succeeded.
dotnet watch ⌚ File updated: .\Features\Shipments\ShipmentDetails.razor
dotnet watch 🔥 [Shipping (net8.0)] Hot reload succeeded.
dotnet watch ⌚ File updated: .\Features\Shipments\ShipmentDetails.razor
dotnet watch 🔥 [Shipping (net8.0)] Hot reload succeeded.
dotnet watch ⌚ File updated: .\Features\Shipments\ShipmentDetails.razor
dotnet watch 🔥 [Shipping (net8.0)] Hot reload succeeded.`

**Comment by brettzook** [comment]
@tmat I still haven't been able to replicate the issue in my test project, and there's no clear path on how to get any closer.

However, this morning on a whim I decided to try hot reload again in my real project (I had abandoned it by running `dotnet watch` with the `--no-hot-reload` option), and...it worked.

I did update these packages from 9.0.1 to 9.0.2 prior to that:
```
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="9.0.2" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="9.0.2" />
```

However, I reverted them to 9.0.1 and it still worked.

So, I have no idea what made the difference. My confidence level is very low that it will continue to work, but I currently don't have an issue to diagnose or pursue.

**Comment by tmat** [comment]
@brettzook If it still reproes in the project with DevExpress dependencies and are ok sharing it, I can try to look into it.

**Comment by brettzook** [comment]
@tmat Hot Reload worked smoothly for the last two days, but this morning it started acting up again. So, I went back to my Solution where I can replicate the problem consistently, and spent more time stripping irrelevant things out.

I'll shared that in as a zip file via https://developercommunity.visualstudio.com/dotnet. Inside the zip is a Word document with step-by-step instructions, including how to reference the DevExpress packages. I've tried to make it as painless as possible so you can get right at the issue.

See https://developercommunity.visualstudio.com/t/Hot-Reload-error-for-Blazor-app-WASM/10855677

**Comment by tmat** [comment]
@brettzook Thanks!

**Comment by kjeske** [comment]
It seems the fix hasn't been released yet. It is in 9.0.3:
https://github.com/dotnet/aspnetcore/pull/59908

**Comment by tmat** [comment]
@brettzook  I can repro now. Thanks for great repro instructions.

**Comment by brettzook** [comment]
Can the `Needs: Repro` label also be removed?

**Comment by javiercn** [comment]
@tmat is there anything else to do here?

Should we move this to the SDK repo?

**Comment by tmat** [comment]
The linked VS feedback issue has been fixed.

**Comment by danroth27** [comment]
@brettzook @shabanelmogy-os @ghostinside If you're still having issues with Blazor WebAssembly hot reload, please let us know!

**Comment by alex-kovalov-vectorsolutions** [comment]
> [@brettzook](https://github.com/brettzook) [@shabanelmogy-os](https://github.com/shabanelmogy-os) [@ghostinside](https://github.com/ghostinside) If you're still having issues with Blazor WebAssembly hot reload, please let us know!

I do still have an issue, but I use .NET 8. Do I need to update sdk to try it again?

**Comment by danroth27** [comment]
> I do still have an issue, but I use .NET 8. Do I need to update sdk to try it again?

@alex-kovalov-vectorsolutions This issue was specifically about a .NET 9 regression, so if you're hitting problems with hot reload in .NET 8 please open a separate issue with detailed steps to reproduce the problem and we'll investigate. If you're hitting problems in Visual Studio, I recommend opening a Visual Studio feedback ticket. For dotnet watch, open the issue in the dotnet/sdk repo.
