### ISSUE TITLE
Blazor Web App WASM download performance issues

### ISSUE THREAD

**Issue by wendellestradairely** [dotnet/aspnetcore#64009]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

There are too many wasm files being downloaded during startup and every time I reload the browser. It took almost 10 seconds to load all these files in local environment and several minutes to load these files into the browser when deployed to a remote/cloud server.

<img width="1039" height="984" alt="Image" src="https://github.com/user-attachments/assets/0f0aa54a-b9f0-4b71-a870-fa91ab88d72c" />

This happens only in .NET 10 rc1 but not in previous versions (e.g. 9.0/8.0).

### Expected Behavior

Must load faster like in .net 8/9

### Steps To Reproduce

Compare two simple projects in both .NET 10 and .NET 9/8

1. Create a new Blazor Web App.
2. Use InteractiveAuto
3. Global Interactivity location

Refresh/reload the browser. As you can see in .NET 10 it's download several wasm files and are very slow. This behavior doesn't happen in .NET 9 and .NET 8

**Comment by javiercn** [comment]
@wendellestradairely thanks for contacting us.

During development asset caching is disabled to avoid serving stale assets. In production you should see the files served from cache. In .NET 8.0 and 9.0 we used a custom `browser` cache object to avoid the asset download altogether, but that came at a cost of size and complexity.

In .NET 10.0 an onwards we simply rely on the browser HTTP cache, which shouldn't show any difference in performance or behavior provided you are publishing in Release mode and running the published app.

During development we take some shortcuts to avoid potentially serving stale assets.

Please publish the app in Release mode, run the published output and let us know if you still have issues in that configuration.

**Comment by wendellestradairely** [comment]
@javiercn It's already published in Release mode. I wish I could share the app link, but I could only show a video recording.

Here's the comparison between the same apps published in both .NET 10 and .NET 9. In .NET 10, it took over a minute for the page to become interactive whereas in .NET 9, it only took about 5 seconds for the page to become interactive. The issue happens on every normal page refresh.

_(P.S. Don't mind the timer in the recording it's not accurate. Please see the browser's Network tab on the right.)_

.NET 10 recording (trimmed)

https://github.com/user-attachments/assets/a3636745-df2c-40fb-a362-702db24723c9

.NET 9 recording

https://github.com/user-attachments/assets/805f2601-e69a-4a22-ac75-cb8aac6138ce

Same thing happens in Starter template (dotnet new blazor -int Auto -ai).
How I published the app (tried 3 methods):
`dotnet publish`
`dotnet publish -c Release`
Publish via Visual Studio Insiders (both in Azure App Service and On-prem IIS)

**Comment by javiercn** [comment]
@wendellestradairely what does the `from` column after time say?

**Comment by wendellestradairely** [comment]
@javiercn You mean the "Fulfilled by" column?
It says nothing. It's blank. 

<img width="1213" height="386" alt="Image" src="https://github.com/user-attachments/assets/4f0a25f3-bda2-48d1-bac1-eba38352b572" />

Only the css and javascript are either memory or disk cached

<img width="1115" height="297" alt="Image" src="https://github.com/user-attachments/assets/c0aef9fb-202d-4c07-b900-1aca03884216" />

**Comment by wendellestradairely** [comment]
Clear site data + Hard refresh = wasms are being downloaded with status 200
Normal refresh = wasms are always being downloaded with status 304

<img width="726" height="382" alt="Image" src="https://github.com/user-attachments/assets/727a0a04-52d7-42a7-95ab-ee5071c34048" />

**Comment by wendellestradairely** [comment]
Here's an example using the starter template. Same issue.

<img width="1889" height="937" alt="Image" src="https://github.com/user-attachments/assets/274bbb16-a184-4809-bd61-a8c257fa1542" />

**Comment by wendellestradairely** [comment]
**UPDATE**:
I have upgraded to the latest .NET 10 RC.2 (10.0.0-rc.2.25502.107). I can no longer see a bunch of wasm files being downloaded on every browser refresh. It loads faster now. However, you can see a bunch of console errors.

<img width="1896" height="892" alt="Image" src="https://github.com/user-attachments/assets/7f9ca5a7-22f5-4b19-8ea0-53c60f918404" />

Another issue is that it doesn't transition to WebAssembly render mode even after several reloads:

<img width="1561" height="910" alt="Image" src="https://github.com/user-attachments/assets/acfe3b89-3590-43cc-9c97-7820f982204a" />

**Comment by oroztocil** [comment]
@wendellestradairely 

The errors you see in the console are caused by an unrelated problem with Wasm publish that was introduced in RC2 and reported elsewhere (#63970, #64041). This problem is fixed in the latest build.

Could you please try to reproduce your original download issue with the latest RC2 build (currently the same as the latest main)? You can get it from here: https://github.com/dotnet/dotnet/blob/main/docs/builds-table.md

**Comment by oroztocil** [comment]
@wendellestradairely I apologize but a colleague just informed me that a final bit of the Wasm publish fix has not been released yet (pending this PR https://github.com/dotnet/dotnet/pull/2927). If you are willing to re-test the download issue later, I can ping you when a proper public build of the SDK is available.

**Comment by wendellestradairely** [comment]
Not a problem @oroztocil. I can wait for the fixes. Thanks!

**Comment by oroztocil** [comment]
@wendellestradairely Sorry for the delay. If you are still interested, can you reproduce your initial performance issue using the final GA release? https://dotnet.microsoft.com/en-us/download/dotnet/10.0

**Comment by wendellestradairely** [comment]
@oroztocil I am currently in the final GA release and in publish -c Release mode. The error is now gone but the `wasm` files were not being cached. Is that an expected behavior?

<img width="1159" height="579" alt="Image" src="https://github.com/user-attachments/assets/f0e14824-3393-45de-a046-e4d8123b78bb" />

**Comment by ManbirRakhra** [comment]
Wasm files are downloaded repeatedly instead of being cached properly. Can this issue be fixed? This problem is preventing the upgrade of my Blazor Web App to upgrade to .Net 10.0

**Comment by balukin** [comment]
I see the same issue in my release build using GA .NET 10. The files are not re-downloaded fully on return visits, but the interactive transition is still delayed until all assemblies are re-validated individually with 1 HTTP request for every assembly, even if it didn't change. It wouldn't be bad if this happened in parallel, but currently, I can see over 50 assemblies, each with a 50-millisecond round trip, firing one by one. That wastes a couple of seconds just to see a waterfall of sequential If-None-Match requests -> 304 Not Modified responses.

It may be caused by my failure to read all the breaking changes in ASP.NET 10, too. I just updated net9.0 to net10.0 in the csproj files, updated nugets, and changed dockerfile to reference `dotnet/aspnet:10.0` and `dotnet/sdk:10.0 `. It's also possible that it was this bad in the previous version when the loader stashed the assemblies manually in the browser cache storage, and I didn't notice the wasted time. So, I'm not 100% positive that it's a regression. Maybe it's just an illusion that interactivity kicks in later now, but I'm pretty sure it used to work like in the .NET 9 video provided by wendellestradairely. I am using InteractiveAuto render mode for most of my project - the issue is not relevant to server-interactive render modes.

Still, it sounds like a lot of unnecessary HTTP trips just to say, "Yeah, the entire thing is unchanged." Assembly fingerprints should be immutable from the build time until the load time, so the loader should not even attempt to re-fetch assemblies if cached artifacts are still valid. Maybe some hot-reload thing is now flipped which delegates staleness check to server instead of doing it in the browser - not sure, just thinking out loud.

Next week, I may have time to debug it further and provide an isolated reproduction case using `dotnet new blazor --interactivity Auto`, in case it's not reproducible on your end.

**Comment by suriya-kongsuk** [comment]
I'm using a blazor webassembly project written with .net 6 which worked fine, but when I just switched to .net 10 it gave me all the same problems, without any code changes.

**Comment by jacekmichalski** [comment]
Same here, is there any fix for this? @oroztocil please help

**Comment by javiercn** [comment]
Hi folks.

We ran some tests on our end and we don't see a meaningful difference in results. To explain what is happening here, the browser chooses to send some HTTP requests to revalidate the `.wasm` files does so in the background. We believe the dev tools here are misleading because the content is served right away from the cache but it shows as 304 in the dev tools because the browser actually revalidates it. Now with that in mind, we want to ask you to run a somewhat simple test in your setups to see if you observe any difference. Note that you shouldn't be looking at the dev tools for this, but at some other metric like TTI or similar. You could use a performance counter in JS to measure the difference in startup time.

The following snippet will force the cache and it shows as such on the devtools. Please let us know if this makes any actual observable wall clock time difference in your setups.

```js
    <script>
        (function() {
            const originalFetch = window.fetch;
            window.fetch = function(resource, options = {}) {
                // Check if the resource is a .wasm file
                const url = typeof resource === 'string' ? resource : resource.url;
                if (url && url.toLowerCase().endsWith('.wasm')) {
                    // Force cache mode for .wasm files
                    options = {
                        ...options,
                        cache: 'force-cache'
                    };
                }
                return originalFetch.call(this, resource, options);
            };
        })();
    </script>
```

**Comment by balukin** [comment]
Hi, thank you for the response.

I can't check your suggested fetch patch to isolate it further now, but I just checked with Firefox and found the correct behavior there.  All .wasm are resolved in ~0ms immediately from cache. In Edge and Chrome, the behavior is different - it triggers sequential revalidation of all WASM resources, blocking transition to interactive until all HTTP 304s finish sequentially. It is noticeably slower to transition into interactive, it's not a measurement error.

Tried with F12 tools closed/opened but this happens with both scenarios. In all of them I ensured to NOT have "Disable cache" checked but I will need to dig further to find out why and how because there are some tools installed on my OS (windows) in the proxy/http inspection area, so it's possible that something affects cache/no-cache decisions - not sure how, but there must be something browser-specific. This happens both for localhost and for external domains, though, so it's not localhost-specific. Browsers checked:

Chrome Version 142.0.7444.162 - issue exists
Edge Version 142.0.3595.53 - issue exists
Firefox 144.0.2 and 145.0 - no issue

If you have some public blazor test site that uses InteractiveAuto and .NET 10, I'll happily check if it's specific to my site, or my browser. If not, I'll try to set up public deployment+project that I can share next week, so we can isolate the underlying cause that affects this caching decisions.

Edit: Noticed one more thing - hitting F5 (not Ctrl+F5, without browser tools opened) always attaches Cache-Control: max-age=0 header in chromium, entering the site from a bookmark does not. This seems to work the same way for all sites - it just seems chrome/edge aggressively throws in this header on F5. I thought that it could be the explanation, but even when I enter from bookmark, it still reaches interactivity in ~2s on Firefox, compared to ~7s on Chrome (wall-clock time). There's something more that affects cache/revalidate decision.

**Comment by bxjg1987** [comment]
I encountered a similar problem. I suspect it is related to the network proxy set on my computer. I will continue to test.

**Comment by schmidtgit** [comment]
+1 same issue here.

Brave and Chrome both attempts to revalidate all the .wasm files even though the files are served with cache control immutable.

I've upgraded from .NET 8 to .NET 10

I also ran a comparison of the .NET 8 Blazer Web App and .NET 10 Blazor Web App templates.

The .NET 10 template has the same issue.

**Comment by thnak** [comment]
Hi.
I have tried to create a new solution with net 9 and it work fine. but with net 10 (aslo new solution with the same config) browser did not cache anything and disk usage from Application storage empty too.

`
Visual studio 2026:
 Blazor web app:
  Framwork 9/10
  Authenticate type None
  Interactive render mode Auto
  Interactive location Per page/component
`

I just realized this issue today when I demoed my app after upgrading to Net 10.

**Comment by oroztocil** [comment]
@balukin Thanks for testing the issue.

Note that the difference in behavior between Firefox and Chrome (and other browsers) is due to the fact that Firefox actually supports the `immutable` cache-control flag, while Chrome does not. There is a long-standing [open issue](https://issues.chromium.org/issues/41253661) for adding support for the flag in Chromium.

**Comment by jacekmichalski** [comment]
@oroztocil I've sent you an email to the live website which has the same problem.

**Comment by oroztocil** [comment]
@jacekmichalski Thank you for the reproduction. I have seen your app and observe the sequential loading and the long time-to-interactivity as well. (Although your app seems to intermittently crash with error 500 which I assume might be due to free deployment configuration?)

I want to note that we are aware of the issue. I have previously reproduced it myself on a simple app with server-side HTTP logging deployed on Azure. There is an ongoing internal investigation in multiple directions, including assesing the extent of the problem, as well as providing short-term workarounds (see @javiercn's [comment](https://github.com/dotnet/aspnetcore/issues/64009#issuecomment-3534259401)) and implementing a long-term fix.

**Comment by ManbirRakhra** [comment]
> Hi folks.
> 
> We ran some tests on our end and we don't see a meaningful difference in results. To explain what is happening here, the browser chooses to send some HTTP requests to revalidate the `.wasm` files does so in the background. We believe the dev tools here are misleading because the content is served right away from the cache but it shows as 304 in the dev tools because the browser actually revalidates it. Now with that in mind, we want to ask you to run a somewhat simple test in your setups to see if you observe any difference. Note that you shouldn't be looking at the dev tools for this, but at some other metric like TTI or similar. You could use a performance counter in JS to measure the difference in startup time.
> 
> The following snippet will force the cache and it shows as such on the devtools. Please let us know if this makes any actual observable wall clock time difference in your setups.
> 
>     <script>
>         (function() {
>             const originalFetch = window.fetch;
>             window.fetch = function(resource, options = {}) {
>                 // Check if the resource is a .wasm file
>                 const url = typeof resource === 'string' ? resource : resource.url;
>                 if (url && url.toLowerCase().endsWith('.wasm')) {
>                     // Force cache mode for .wasm files
>                     options = {
>                         ...options,
>                         cache: 'force-cache'
>                     };
>                 }
>                 return originalFetch.call(this, resource, options);
>             };
>         })();
>     </script>

Implementing this workaround provides a noticeable performance improvement, particularly by decreasing load times during subsequent reloads. The snippet in App.razor enabled disk-cache retrieval once again. Nonetheless, resolving the root issue within the .NET repository remains essential.

**Comment by bxjg1987** [comment]
My project used to be. net9 blazer web app auto mode, and the auto mode worked well before.

After the official release of. net10, I upgraded. After I published the project to the server, through strict testing, I found that sometimes the wasm file returned 304, and after a period of time, it was accessed again. The response status was 200, and I had to wait more than 1 minute. Obviously, the auto mode failed.

 I use the edge browser: version 142.0.3595.90 (official version) (64 bit), and the server release is released, windows server 2019， Run using kestrel.

**Comment by bxjg1987** [comment]
> Hi folks.
> 
> We ran some tests on our end and we don't see a meaningful difference in results. To explain what is happening here, the browser chooses to send some HTTP requests to revalidate the `.wasm` files does so in the background. We believe the dev tools here are misleading because the content is served right away from the cache but it shows as 304 in the dev tools because the browser actually revalidates it. Now with that in mind, we want to ask you to run a somewhat simple test in your setups to see if you observe any difference. Note that you shouldn't be looking at the dev tools for this, but at some other metric like TTI or similar. You could use a performance counter in JS to measure the difference in startup time.
> 
> The following snippet will force the cache and it shows as such on the devtools. Please let us know if this makes any actual observable wall clock time difference in your setups.
> 
>     <script>
>         (function() {
>             const originalFetch = window.fetch;
>             window.fetch = function(resource, options = {}) {
>                 // Check if the resource is a .wasm file
>                 const url = typeof resource === 'string' ? resource : resource.url;
>                 if (url && url.toLowerCase().endsWith('.wasm')) {
>                     // Force cache mode for .wasm files
>                     options = {
>                         ...options,
>                         cache: 'force-cache'
>                     };
>                 }
>                 return originalFetch.call(this, resource, options);
>             };
>         })();
>     </script>

I tried this method and it didn't always work.

**Comment by jacekmichalski** [comment]
> Hi folks.
> 
> We ran some tests on our end and we don't see a meaningful difference in results. To explain what is happening here, the browser chooses to send some HTTP requests to revalidate the `.wasm` files does so in the background. We believe the dev tools here are misleading because the content is served right away from the cache but it shows as 304 in the dev tools because the browser actually revalidates it. Now with that in mind, we want to ask you to run a somewhat simple test in your setups to see if you observe any difference. Note that you shouldn't be looking at the dev tools for this, but at some other metric like TTI or similar. You could use a performance counter in JS to measure the difference in startup time.
> 
> The following snippet will force the cache and it shows as such on the devtools. Please let us know if this makes any actual observable wall clock time difference in your setups.
> 
>     <script>
>         (function() {
>             const originalFetch = window.fetch;
>             window.fetch = function(resource, options = {}) {
>                 // Check if the resource is a .wasm file
>                 const url = typeof resource === 'string' ? resource : resource.url;
>                 if (url && url.toLowerCase().endsWith('.wasm')) {
>                     // Force cache mode for .wasm files
>                     options = {
>                         ...options,
>                         cache: 'force-cache'
>                     };
>                 }
>                 return originalFetch.call(this, resource, options);
>             };
>         })();
>     </script>

I've noticed an issue with this script. After deployment of a new version of my blazor app I need to ask users to manually refresh browser cache to get latest improvements. It's painful to do this in a saas application with many users  @maraf @oroztocil do you have any permanent fix?

**Comment by wendellestradairely** [comment]
I have abandoned my Blazor project and switched to Angular due to the performance issues in Blazor .Net 10 including this issue in wasm caching.

**Comment by bitbound** [comment]
@javiercn   I've been trying to find answers to this issue that appeared in .NET 10, and I saw a couple GitHub issues that were closed without resolution.  With all due respect, if you're not seeing a difference in your tests, I think it's possible that you're either not replicating the issue, or the network conditions in the tests are "too optimal" to notice the symptoms.

I would love this to be something I'm doing wrong or overlooking, since that would be easy to fix.  But it's looking like that's not the case.

Please see the below video.  The left one is .NET 9.  The right is .NET 10.  Both deployed in Release configuration to Docker Hub.  Both hosted on the same platform (Railway).  Notice the difference in network calls.  (Edit: Also, the .NET 10 one has the benefit of Cloudflare cache here.  The .NET 9 app is being served straight from Railway.  If I turn Cloudflare cache off for the .NET 10 one, I get 20-second load times like the one shown below.)

https://github.com/user-attachments/assets/ad0ac60f-e337-4df4-9667-468a69b70b7e


In both browsers, the WASM files have already been downloaded and cached.

The difference is that, in .NET 9, Blazor served them directly from cache storage without making any http requests.  You don't see any calls in the network tab.

With .NET 10, an http request is sent for every wasm file to revalidate it.  It returns 304 Not Modified and serves from cache after that, but all of the sequential http calls to check all the files is what's taking so long.

I'm seeing up to 20-second load times when Cloudflare's not in front of it.  I know this phrase is over-used, but like, this is totally unusable.  I can't ship this.

<img width="1497" height="911" alt="Image" src="https://github.com/user-attachments/assets/e559003e-f699-47de-878d-a9ae2fce9739" />

Also, I have gigabit fiber, so I know it's not on my end.

<img width="691" height="261" alt="Image" src="https://github.com/user-attachments/assets/bfd08be9-92de-4095-9ed3-93fa6fa43248" />

So, my questions regarding your testing are:

1. Are you seeing the 304's for every WASM file, on every page refresh, even after everything's cached?
2. How many WASM files are there with each page refresh?
3. What's your average time for http requests that return the 304?

Because if you have, say, 100 WASM files and your latency is in the double or triple digits, you're going to notice the difference.

I can reduce the load time a bit with some extra Cloudflare cache rules.  But it's still not practically usable.  And there's no guarantee that the user will have a nearby CF edge node, or that they'll have low latency to it.  Let's be honest, even people who love Blazor will admit that it's right on the edge of what's considered acceptable load times.

Like I said, I'd love to be wrong about this, and hopefully I'll soon feel very stupid about some dumb mistake I'm making.  But I'm looking at my roadmap with dread, wondering if I need to throw everything out and rewrite my app.

**Comment by stavroskasidis** [comment]
I am also seeing behavior like this in our project (which is quite large - over 50 wasm files) after upgrading to .net 10, so I cannot ship the upgrade until this is fixed.

The previous solution prior to .net 10 may have been complicated but it was working very well. Saving the files in the cache storage with a hash, no network requests invoked ever, no firewalls or proxies interfering and removing cache headers after the first load, etc.

Based on the last 2-3 releases of .net, I am very sad to have come to the conclusion that the team that writes Blazor does not actually use it in real life scenarios or large enough apps (eg the [horrible new templates](https://github.com/dotnet/aspnetcore/issues/55307) that have yet to be fixed since net 8.0). Maybe this is not the case but that is definitely the feeling I am getting and it’s very problematic if it’s true.

**Comment by daesk** [comment]
Any comment from any MS people in this issue?

We are having the same issue

**Comment by bitbound** [comment]
I found this comment from @javiercn from back in September, with a screenshot of exactly what we're talking about: https://github.com/dotnet/aspnetcore/issues/63682#issuecomment-3291517890

But notice it's localhost, with a roundtrip time of 2-4ms.  Of course you're not going to see the issue in that scenario.  Try 140ms per file.

If I'm understanding correctly, this appears to be the PR that caused this (in the `runtime` repo):  https://github.com/dotnet/runtime/pull/114901

From what I can gather of the conversations I've read, it seems everyone assumed that relying solely on the browser's cache implementation was fine and would have no impact.

I don't see anyone mention if it was actually tested, though.  Was it?  Or was it only tested on localhost?  Or when the origin server is in the same datacenter?  Those scenarios aren't going to yield representative numbers.

Also, were different browsers tested to ensure they handled caching the way it was being assumed?  Chromium obviously doesn't.

But I've found that Firefox handles the `immutable` cache header differently and serves it directly from cache.  You can still see the http request, but it never leaves the browser, and returns 200 directly from cache.  Still, it's not as performant as the built-in caching was.

https://github.com/user-attachments/assets/0fbc4fd0-c454-437f-9894-ab0e686cd5cf

**Comment by javiercn** [comment]
Hi folks,

Thank you for your patience. We understand how frustrating these performance problems are, and we recognize this is blocking many of you from upgrading to .NET 10.

We've identified the root cause of problem and we are working on a fix. During the .NET 10 changes, we missed updating code in the WebAssembly loader that was forcing fetch requests to bypass the cache. This caused the browser to make revalidation requests for every WASM file on each page load, even though the server was returning the correct cache headers. This issue is especially severe with InteractiveAuto render mode, where these requests happen one after another rather than in parallel, leading to the significant delays you've observed.

This slipped through because our automated and manual testing wasn't properly covering the auto render mode scenario and it was using webassembly instead, where the requests happen in parallel and it wasn't obvious.

We sincerely apologize for the inconvinience this has caused many of you. As an immediate fix, you can disable the `no-cache` behavior as follows.

Add a file named `{AssemblyName}.lib.module.js` to your Blazor Client project's `wwwroot` folder:

```js
export function onRuntimeConfigLoaded(config) {
    config.disableNoCacheFetch = true;
}
```

**For example:**
```
- BlazorApp
  - BlazorApp.Client
    - wwwroot
      - BlazorApp.Client.lib.module.js
```

This will address the issue and let the files be properly cached as can be seen here.

<img width="1307" height="376" alt="Image" src="https://github.com/user-attachments/assets/b771abb7-6d2d-45ea-9558-b96cb1cb323e" />

**Auto mode**
<img width="2317" height="870" alt="Image" src="https://github.com/user-attachments/assets/eedeacb1-695b-4fc2-a2e4-a469ec606837" />

**Webassembly mode**
<img width="1985" height="1014" alt="Image" src="https://github.com/user-attachments/assets/113f5911-7d31-4ec3-94ca-b77503b9a015" />

We are working on a permanent fix for the next servicing release to fully resolve the issue. Please try the temporary fix and let us know if you are still running into issues afterwards.

**Comment by bitbound** [comment]
@javiercn   Thank you for the quick reply.  This is working for me.  Cheers!

**Comment by Bellarmine-Head** [comment]
> Based on the last 2-3 releases of .net, I am very sad to have come to the conclusion that the team that writes Blazor does not actually use it in real life scenarios or large enough apps (eg the [horrible new templates](https://github.com/dotnet/aspnetcore/issues/55307) that have yet to be fixed since net 8.0). Maybe this is not the case but that is definitely the feeling I am getting and it’s very problematic if it’s true.

@stavroskasidis - This ^^

The horrible new templates do a great job of _not showing how to do what a classic Blazor WebAssembly needs to do_ and mistakes like the one described in this ticket have reduced my faith in the team to near zero.  Of course many things have improved since launch, but in some respects I had a better, happier, more stable time when I started in May 2020.  And at least I knew how to standup a new, working project that had proper API calls from client to server via shared models.

While happy to continue using C# and ASP.NET Core on the server, I'm seriously considering putting aside Blazor WebAssembly in the client project (for new websites) and moving back to JS/TS and some JS framework.  It'll be less pain and more stable.

That reminds me: our CTO (and other CTOs I have talked to) said from the start: Blazor WebAssembly is ok for our internal tools, but we will never use it for public-facing websites.  Very wise.  With every year that has passed, that dictate seems more and more sensible and prescient.

**Comment by stavroskasidis** [comment]
Is the problem the `cache: 'no-cache' ` passed onto fetch under the hood ?

If so, then everyone of us who uses the `loadBootResource` method for custom blazor startup, according to the docs, they were instructed to use `cache: 'no-cache' `. 

Isn't this a breaking change for us? Shouldn't [the docs](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-10.0#load-client-side-boot-resources) also be updated to not use 'no-cache' ?

**Comment by codemahek** [comment]
> Hi folks,
> 
> Thank you for your patience. We understand how frustrating these performance problems are, and we recognize this is blocking many of you from upgrading to .NET 10.
> 
> We've identified the root cause of problem and we are working on a fix. During the .NET 10 changes, we missed updating code in the WebAssembly loader that was forcing fetch requests to bypass the cache. This caused the browser to make revalidation requests for every WASM file on each page load, even though the server was returning the correct cache headers. This issue is especially severe with InteractiveAuto render mode, where these requests happen one after another rather than in parallel, leading to the significant delays you've observed.
> 
> This slipped through because our automated and manual testing wasn't properly covering the auto render mode scenario and it was using webassembly instead, where the requests happen in parallel and it wasn't obvious.
> 
> We sincerely apologize for the inconvinience this has caused many of you. As an immediate fix, you can disable the `no-cache` behavior as follows.
> 
> Add a file named `{AssemblyName}.lib.module.js` to your Blazor Client project's `wwwroot` folder:
> 
> export function onRuntimeConfigLoaded(config) {
>     config.disableNoCacheFetch = true;
> }
> **For example:**
> 
> ```
> - BlazorApp
>   - BlazorApp.Client
>     - wwwroot
>       - BlazorApp.Client.lib.module.js
> ```
> 
> This will address the issue and let the files be properly cached as can be seen here.
> 
> <img alt="Image" width="1307" height="376" src="https://private-user-images.githubusercontent.com/6995051/520177750-b771abb7-6d2d-45ea-9558-b96cb1cb323e.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ2NjIxNzUsIm5iZiI6MTc2NDY2MTg3NSwicGF0aCI6Ii82OTk1MDUxLzUyMDE3Nzc1MC1iNzcxYWJiNy02ZDJkLTQ1ZWEtOTU1OC1iOTZjYjFjYjMyM2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTEyMDJUMDc1MTE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjA4MzFhYzdiNzgxZTg0OTkxZmViZTNmYjU4YzY4YzQ1YTJkN2Y3MjQ0Zjc2YTVmMDFlN2YwN2QxMzE5YTU3NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.PnfL48lEAbbVBC29YdqLhAS4nZULE0ga8CaXtkzYyYY">
> **Auto mode** <img alt="Image" width="2000" height="870" src="https://private-user-images.githubusercontent.com/6995051/520177961-eedeacb1-695b-4fc2-a2e4-a469ec606837.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ2NjIxNzUsIm5iZiI6MTc2NDY2MTg3NSwicGF0aCI6Ii82OTk1MDUxLzUyMDE3Nzk2MS1lZWRlYWNiMS02OTViLTRmYzItYTJlNC1hNDY5ZWM2MDY4MzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTEyMDJUMDc1MTE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTk2NWIyODIwOWM5ZjlkNDIwZWJjYmY3NmRiMjY5YThjN2IyYzk5MGQ5ODY0YTFhMWU4MzJjOTM0NWJlZGIzZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.rP7EuTBexSs2yPL5-_USXRv5Vsx7XFYZxIyw9bahZHw">
> 
> **Webassembly mode** <img alt="Image" width="1985" height="1014" src="https://private-user-images.githubusercontent.com/6995051/520179341-113f5911-7d31-4ec3-94ca-b77503b9a015.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ2NjIxNzUsIm5iZiI6MTc2NDY2MTg3NSwicGF0aCI6Ii82OTk1MDUxLzUyMDE3OTM0MS0xMTNmNTkxMS03ZDMxLTRlYzMtOTRjYS1iNzc1MDNiOWEwMTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTEyMDJUMDc1MTE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGNhYjk5MGRlMGQ0MjYzYzQyY2UxZjY4YThiMjJlNDhlMzg2ODM0NTA1M2QyZGFjYjBmN2MyNTY5M2RjNWViMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.AhFSOIJzZd--6qmKAlU-mJYwMuS3clIOdcgYgn5FYNE">
> 
> We are working on a permanent fix for the next servicing release to fully resolve the issue. Please try the temporary fix and let us know if you are still running into issues afterwards.

This doesn't work for me and I ceaated the js file as you mentioned. When I add the breakpoint it does get called but I don't see any impact. Its still always 200

**Comment by daesk** [comment]
> Hi folks,
> 
> Thank you for your patience. We understand how frustrating these performance problems are, and we recognize this is blocking many of you from upgrading to .NET 10.
> 
> We've identified the root cause of problem and we are working on a fix. During the .NET 10 changes, we missed updating code in the WebAssembly loader that was forcing fetch requests to bypass the cache. This caused the browser to make revalidation requests for every WASM file on each page load, even though the server was returning the correct cache headers. This issue is especially severe with InteractiveAuto render mode, where these requests happen one after another rather than in parallel, leading to the significant delays you've observed.
> 
> This slipped through because our automated and manual testing wasn't properly covering the auto render mode scenario and it was using webassembly instead, where the requests happen in parallel and it wasn't obvious.
> 
> We sincerely apologize for the inconvinience this has caused many of you. As an immediate fix, you can disable the `no-cache` behavior as follows.
> 
> Add a file named `{AssemblyName}.lib.module.js` to your Blazor Client project's `wwwroot` folder:
> 
> export function onRuntimeConfigLoaded(config) {
>     config.disableNoCacheFetch = true;
> }
> **For example:**
> 
> ```
> - BlazorApp
>   - BlazorApp.Client
>     - wwwroot
>       - BlazorApp.Client.lib.module.js
> ```
> 
> This will address the issue and let the files be properly cached as can be seen here.
> 
> <img alt="Image" width="1307" height="376" src="https://private-user-images.githubusercontent.com/6995051/520177750-b771abb7-6d2d-45ea-9558-b96cb1cb323e.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ2NjIxNTUsIm5iZiI6MTc2NDY2MTg1NSwicGF0aCI6Ii82OTk1MDUxLzUyMDE3Nzc1MC1iNzcxYWJiNy02ZDJkLTQ1ZWEtOTU1OC1iOTZjYjFjYjMyM2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTEyMDJUMDc1MDU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWU5MjI4ZWJmNWE1YWE5YTdmMTk3NjcyY2ZjMzExM2Y3N2Q1ZWZjZGM5MDA5YTRkMmQxZTg5OWExNWVhNDkwZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.SuCXWJ_5I-YIN-PBhYwUwFfuEzwa7Ac7B1LD-uyb7hQ">
> **Auto mode** <img alt="Image" width="2000" height="870" src="https://private-user-images.githubusercontent.com/6995051/520177961-eedeacb1-695b-4fc2-a2e4-a469ec606837.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ2NjIxNTUsIm5iZiI6MTc2NDY2MTg1NSwicGF0aCI6Ii82OTk1MDUxLzUyMDE3Nzk2MS1lZWRlYWNiMS02OTViLTRmYzItYTJlNC1hNDY5ZWM2MDY4MzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTEyMDJUMDc1MDU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTA1OTA3MDM0YjA2MjlmZWE4MjBlODNmZTJhZjU0ODkzNTcyM2ZmNWE2ODUwYjg1ZTFiOTVjZjkzODc4NmJkMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.orGM114frkTrH8MgOP_3H4HefBahUi-2UlJn1_hpNao">
> 
> **Webassembly mode** <img alt="Image" width="1985" height="1014" src="https://private-user-images.githubusercontent.com/6995051/520179341-113f5911-7d31-4ec3-94ca-b77503b9a015.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ2NjIxNTUsIm5iZiI6MTc2NDY2MTg1NSwicGF0aCI6Ii82OTk1MDUxLzUyMDE3OTM0MS0xMTNmNTkxMS03ZDMxLTRlYzMtOTRjYS1iNzc1MDNiOWEwMTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTEyMDJUMDc1MDU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjQ0NmM1OGZmN2I4NzdiNjY2OTVmYWMyNGYxYmM5MGNlNjQ5YTRkOWFjZWVjNGFmMmQyZTZhZjg5ZjRlOTA3ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.iJuiqplCMMPu9nk0jsV-QzoJIRyqj3zRR56mkp-aFBU">
> 
> We are working on a permanent fix for the next servicing release to fully resolve the issue. Please try the temporary fix and let us know if you are still running into issues afterwards.

@javiercn 

It works for us, except for the biggest file _framework/dotnet.native.q9p6bb09u1.wasm

<img width="2517" height="883" alt="Image" src="https://github.com/user-attachments/assets/b9bab363-c4d4-4e61-a62d-cd3ab0aae866" />

Our application is a JS app were we are using Blazor components in. 
So i have overridden this as well

<img width="981" height="340" alt="Image" src="https://github.com/user-attachments/assets/1c1c2954-2292-430c-ac57-570797810735" />

Also done this 

<img width="837" height="241" alt="Image" src="https://github.com/user-attachments/assets/0ac3ab62-1b99-499c-bbb3-763a04e70891" />

That is never cached. It works in firefox, but not in chrome and edge. 
Any ideas why?

**Comment by codemahek** [comment]
> > Hi folks,
> > Thank you for your patience. We understand how frustrating these performance problems are, and we recognize this is blocking many of you from upgrading to .NET 10.
> > We've identified the root cause of problem and we are working on a fix. During the .NET 10 changes, we missed updating code in the WebAssembly loader that was forcing fetch requests to bypass the cache. This caused the browser to make revalidation requests for every WASM file on each page load, even though the server was returning the correct cache headers. This issue is especially severe with InteractiveAuto render mode, where these requests happen one after another rather than in parallel, leading to the significant delays you've observed.
> > This slipped through because our automated and manual testing wasn't properly covering the auto render mode scenario and it was using webassembly instead, where the requests happen in parallel and it wasn't obvious.
> > We sincerely apologize for the inconvinience this has caused many of you. As an immediate fix, you can disable the `no-cache` behavior as follows.
> > Add a file named `{AssemblyName}.lib.module.js` to your Blazor Client project's `wwwroot` folder:
> > export function onRuntimeConfigLoaded(config) {
> > config.disableNoCacheFetch = true;
> > }
> > **For example:**
> > ```
> > - BlazorApp
> >   - BlazorApp.Client
> >     - wwwroot
> >       - BlazorApp.Client.lib.module.js
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This will address the issue and let the files be properly cached as can be seen here.
> > <img alt="Image" width="1307" height="376" src="https://private-user-images.githubusercontent.com/6995051/520177750-b771abb7-6d2d-45ea-9558-b96cb1cb323e.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ2NjIxNTUsIm5iZiI6MTc2NDY2MTg1NSwicGF0aCI6Ii82OTk1MDUxLzUyMDE3Nzc1MC1iNzcxYWJiNy02ZDJkLTQ1ZWEtOTU1OC1iOTZjYjFjYjMyM2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTEyMDJUMDc1MDU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWU5MjI4ZWJmNWE1YWE5YTdmMTk3NjcyY2ZjMzExM2Y3N2Q1ZWZjZGM5MDA5YTRkMmQxZTg5OWExNWVhNDkwZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.SuCXWJ_5I-YIN-PBhYwUwFfuEzwa7Ac7B1LD-uyb7hQ">
> > **Auto mode** <img alt="Image" width="2000" height="870" src="https://private-user-images.githubusercontent.com/6995051/520177961-eedeacb1-695b-4fc2-a2e4-a469ec606837.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ2NjIxNTUsIm5iZiI6MTc2NDY2MTg1NSwicGF0aCI6Ii82OTk1MDUxLzUyMDE3Nzk2MS1lZWRlYWNiMS02OTViLTRmYzItYTJlNC1hNDY5ZWM2MDY4MzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTEyMDJUMDc1MDU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTA1OTA3MDM0YjA2MjlmZWE4MjBlODNmZTJhZjU0ODkzNTcyM2ZmNWE2ODUwYjg1ZTFiOTVjZjkzODc4NmJkMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.orGM114frkTrH8MgOP_3H4HefBahUi-2UlJn1_hpNao">
> > **Webassembly mode** <img alt="Image" width="1985" height="1014" src="https://private-user-images.githubusercontent.com/6995051/520179341-113f5911-7d31-4ec3-94ca-b77503b9a015.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ2NjIxNTUsIm5iZiI6MTc2NDY2MTg1NSwicGF0aCI6Ii82OTk1MDUxLzUyMDE3OTM0MS0xMTNmNTkxMS03ZDMxLTRlYzMtOTRjYS1iNzc1MDNiOWEwMTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTEyMDJUMDc1MDU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjQ0NmM1OGZmN2I4NzdiNjY2OTVmYWMyNGYxYmM5MGNlNjQ5YTRkOWFjZWVjNGFmMmQyZTZhZjg5ZjRlOTA3ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.iJuiqplCMMPu9nk0jsV-QzoJIRyqj3zRR56mkp-aFBU">
> > We are working on a permanent fix for the next servicing release to fully resolve the issue. Please try the temporary fix and let us know if you are still running into issues afterwards.
> 
> [@javiercn](https://github.com/javiercn)
> 
> It works for us, except for the biggest file _framework/dotnet.native.q9p6bb09u1.wasm
> 
> <img alt="Image" width="2000" height="883" src="https://private-user-images.githubusercontent.com/21100041/521202920-b9bab363-c4d4-4e61-a62d-cd3ab0aae866.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ2NjM5OTIsIm5iZiI6MTc2NDY2MzY5MiwicGF0aCI6Ii8yMTEwMDA0MS81MjEyMDI5MjAtYjliYWIzNjMtYzRkNC00ZTYxLWE2MmQtY2QzYWIwYWFlODY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjAyVDA4MjEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjZGZkMTY2Mjc0MTUxN2Q0MDIzZjc0YTMxYjY1OTQwYmM1M2I5YWJlOTc4MTMwMTM4NjM5YmM5YmQ5N2Q1YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BIMV4HGzoqCHZT9J290yNOpXnpe_dwBGYZBUG5_mhKo">
> Our application is a JS app were we are using Blazor components in. So i have overridden this as well
> 
> <img alt="Image" width="981" height="340" src="https://private-user-images.githubusercontent.com/21100041/521202170-1c1c2954-2292-430c-ac57-570797810735.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ2NjM5OTIsIm5iZiI6MTc2NDY2MzY5MiwicGF0aCI6Ii8yMTEwMDA0MS81MjEyMDIxNzAtMWMxYzI5NTQtMjI5Mi00MzBjLWFjNTctNTcwNzk3ODEwNzM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjAyVDA4MjEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4ZDkxMmEyYTQ2YjMzMWQ5OWYzNTE4M2Y5ZGNiZjkwM2YxZTYxNjU3YzYyZTY1OTFmNTlmODAzOTJkM2Y5MTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.z4bbs2M59wBOnquTA5WzdQEZ1xhv-HChVYZ9nhyS4VU">
> Also done this
> 
> <img alt="Image" width="837" height="241" src="https://private-user-images.githubusercontent.com/21100041/521202431-0ac3ab62-1b99-499c-bbb3-763a04e70891.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ2NjM5OTIsIm5iZiI6MTc2NDY2MzY5MiwicGF0aCI6Ii8yMTEwMDA0MS81MjEyMDI0MzEtMGFjM2FiNjItMWI5OS00OTljLWJiYjMtNzYzYTA0ZTcwODkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjAyVDA4MjEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkMjhmNmUxMmZjMDVlZGY5MmM2ZGJlZjMxMzMyNTk1MWU1ODcyOGU0NmM1MDY4ZDY1M2Q3M2FlNTkwMTUzNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.keuRptViKuZVYjqaMDghFyt0dyr7oAGvGQSXTjZZg5U">
> That is never cached. It works in firefox, but not in chrome and edge. Any ideas why?

Thanks for your code. I am kind of doing the similar thing. So in our case its working because of doing 
cache: 'force-cache'

if you remove that code, than the suggestion which @javiercn gave will not work.

Other thing which I have noticed if you use

app.UseStaticFiles();

instead of 

app.MapStaticAssets

it will even fetch the dotnet one from the disk cache

**Comment by javiercn** [comment]
@codemahek are you running the published app?

When you run with `dotnet run` or VS there we explicitly set the caching headers to `no-cache` to all assets to avoid stale resources across runs. On the publish output you should see the right behavior (and the right cache-control headers).

**Comment by javiercn** [comment]
@daesk can you check the cache-control header on that response?

**Comment by codemahek** [comment]
> [@codemahek](https://github.com/codemahek) are you running the published app?
> 
> When you run with `dotnet run` or VS there we explicitly set the caching headers to `no-cache` to all assets to avoid stale resources across runs. On the publish output you should see the right behavior (and the right cache-control headers).

Thanks, I was running it using dotnet run

**Comment by codemahek** [comment]
@javiercn after publishing it works fine. So if I refresh multiple times it will take it from disk cache. 
But after sometime it will do 304 and again after that it will be disk cache for sometime, and it goes on.
So seems like there is some timeout for cache invalidate

**Comment by phongphambkdn** [comment]
@javiercn Just double confirm, with the new fix, you will improve the loading of wasm files on the startup as well? 

With .NET 9 I don't see wasm files loading in the network tab.
But .NET 10 I saw it and it block all other HTTP requests and make the loading slow.

You are fixing the wasm files loading like .NET 9 right?

**Comment by daesk** [comment]
> [@daesk](https://github.com/daesk) can you check the cache-control header on that response?

@javiercn, We had missed the app.MapStaticAssets(..) call 
Thanks to @codemahek for mention that, Now its works for us

**Comment by javiercn** [comment]
> [@javiercn](https://github.com/javiercn) Just double confirm, with the new fix, you will improve the loading of wasm files on the startup as well?
> 
> With .NET 9 I don't see wasm files loading in the network tab. But .NET 10 I saw it and it block all other HTTP requests and make the loading slow.
> 
> You are fixing the wasm files loading like .NET 9 right?

You'll see the file loads in the network tab, but they will return from disk cache, and the speed should be the same as in 9.0.

**Comment by Dasuke** [comment]
The - BlazorApp.Client.lib.module.js works for now, thank you! Do we have an ETA for this issue? I'd appreciate if we can fix that ASAP

**Comment by javiercn** [comment]
We have already merged a fix https://github.com/dotnet/runtime/pull/122442 and will be available in the next servicing release.

**Comment by zubairkhakwani** [comment]
@javiercn Can we skip 304 check and directly load wasm files from disk-cache? because in initial response of these assets files the response cache header is returning.

`cache-control: max-age=31536000, immutable`

immutable should not check again with server as this round trip could increase startup time.

**Comment by zubairkhakwani** [comment]
In a Blazor web app, routes like /view-users or /view-subscriptions ultimately return the same app shell (App.razor), and the actual component is rendered client-side by the router.

However, when navigating directly to these routes (refresh or direct URL), the server always returns a full 200 OK response with the entire app shell, even when nothing has changed. This happens on every request.

In other SPA frameworks (e.g. Angular), I’ve seen the app shell cached using ETag/304 Not Modified, which reduces reload time and unnecessary data transfer.

My questions:

- Is app-shell or route-level caching already supported in Blazor?
- If not, is there a recommended way to enable 304 Not Modified (ETag / conditional requests) for these routes?
- Since all routes serve the same shell, shouldn’t this content be cacheable to improve startup performance?

I couldn’t get 304 responses to work and would like to know if this is a framework limitation or a configuration issue.

**Comment by javiercn** [comment]
@zubairkhakwani what you are talking is different. Please file a separate issue to discuss your scenario.

There are already other issues tracking SSR caching, but this issue is not for that. In addition to that, the browser caches things by URL, so what you are describing with different routes won't work.

If you want that, you need to use a service worker to control the network.

**Comment by zubairkhakwani** [comment]
> @zubairkhakwani what you are talking is different. Please file a separate issue to discuss your scenario.
> 
> There are already other issues tracking SSR caching, but this issue is not for that. In addition to that, the browser caches things by URL, so what you are describing with different routes won't work.
> 
> If you want that, you need to use a service worker to control the network.

Okay but what about no (304) network round trip for cached wasm assets, like for css and js. As mentioned in my first comment.

And for URL based caching we can do something like baseurl/#/remaining-route. For even separate coaching for each url is still better than no catching at all. But for that i will open new issue to discuss this. Thanks.

**Comment by lfoust** [comment]
@javiercn -  Is there an estimated date when this fix will ship?

**Comment by codemahek** [comment]
@lfoust it has been fixed in the latest version i.e. 10.0.2.
I deployed and it works fine now.
thanks @javiercn

**Comment by czlatea** [comment]
With 10.0.2, it is working fine. The only concern I have is with _framework/dotnet.js

Additionally, a request is made for AuthenticationService.js, even though I have included the script properly. 
```
<script src="@Assets["_content/Microsoft.Authentication.WebAssembly.Msal/AuthenticationService.js"]"></script>
<script src="@Assets["_framework/blazor.web.js"]"></script>
```

<img width="1911" height="167" alt="Image" src="https://github.com/user-attachments/assets/cf8b667c-a94e-436e-860d-bc1ff2620e63" />

**Comment by Smayke95** [comment]
I just update everything on 10.0.2 and still is not working.

Server project:
<img width="736" height="91" alt="Image" src="https://github.com/user-attachments/assets/d9d24a9e-8e5c-4088-a758-0c0beaeb75dd" />

Client project:
<img width="827" height="112" alt="Image" src="https://github.com/user-attachments/assets/f3adf0cd-fc70-4914-a347-98f30ea1a1c8" />

IIS (dotnet --list-runtimes):
<img width="752" height="22" alt="Image" src="https://github.com/user-attachments/assets/44635089-04ff-49ce-83dd-bb8fcb14d0cf" />

First load:
<img width="846" height="417" alt="Image" src="https://github.com/user-attachments/assets/c3b04412-fc09-4064-accb-3c08237473f9" />

Second load (304 issue, browser Chrome):
<img width="852" height="367" alt="Image" src="https://github.com/user-attachments/assets/ff36b9a3-c6c4-4ca4-9182-06395108b6f7" />

**Comment by Smayke95** [comment]
After I updated Visual Studio and publish with it, it's working. Still not working when app is deployed via Azure DevOps.

<img width="848" height="466" alt="Image" src="https://github.com/user-attachments/assets/016e1588-9716-44b3-bd0d-512aaf1dbece" />

**Comment by frindler** [comment]
After upgrading to 10.0.2 it works locally, but when publishing to Azure App Service it's still super slow with sequential 304s for every wasm asset on every reload. This creates 10+ seconds to WASM interactivity. Anything else that needs to be done to get this working?

**Comment by ManbirRakhra** [comment]
Hello, I’ve noticed another issue. The website initially loads and works in Blazor Server mode while the WASM is downloading. However, even after the WASM finishes loading, it stays in Blazor Server mode until I do a hard refresh (F5). This used to switch automatically without needing a refresh in .NET 8/9.

**Comment by lfoust** [comment]
> After upgrading to 10.0.2 it works locally, but when publishing to Azure App Service it's still super slow with sequential 304s for every wasm asset on every reload. This creates 10+ seconds to WASM interactivity. Anything else that needs to be done to get this working?

I am seeing the same behavior. I have updated to the latest nugets, removed the workaround, and it seems to be loading from cache when run locally. When I deploy my app to Azure, it is loading each wasm every time causing extremely slow load times (this is what I understand to be the original issue that was being addressed here). Also, the workaround does not seem to mitigate this.

<img width="2457" height="1220" alt="Image" src="https://github.com/user-attachments/assets/c1dcd8a1-8e78-4f01-91f5-eed875335058" />

**Comment by dave-gcv** [comment]
I am also experiencing this problem with a solution that was updated from .NET 9 to .NET 10

Updated to SDK 10.0.102 and updated all nuget packages and the problem persists.

I have to add that I only experience the issue when debugging in VS2026 (F5).

I haven't deployed a .NET 10 version of my app anywhere (other than local IIS) - I don't have the confidence to do that yet until this issue is resolved.

As it stands I have zero trust in Blazor with .NET 10

**Comment by frindler** [comment]
@javiercn Please reopen this issue as not fixed (for deployments)

**Comment by czlatea** [comment]
@frindler  @dave-gcv I have deployed the application in Azure, as a Container App, and it is working as expected.  I have a wasm application. 

<img width="1199" height="226" alt="Image" src="https://github.com/user-attachments/assets/491916eb-8617-453e-a868-460869676804" />

**Comment by frindler** [comment]
@czlatea That's great - any ideas what to do? I can get it to use the disk cache with the workaround here: https://github.com/dotnet/aspnetcore/issues/64009#issuecomment-3589477955 -- without I'm seeing the old 304s. I checked that the GH runner is compiling with 10.0.2. It's an auto-rendermode app, maybe there is some interaction that's preventing the disk cache from being used.

**Comment by patgoull** [comment]
> After upgrading to 10.0.2 it works locally, but when publishing to Azure App Service it's still super slow with sequential 304s for every wasm asset on every reload. This creates 10+ seconds to WASM interactivity. Anything else that needs to be done to get this working?

For me, the issue still occurred after deployment because the Azure DevOps pipeline was not yet using the 10.0.2 SDK. We use a local agent running on a VM, so I updated the SDK directly on the VM, and the next build completed successfully.

I tested this extensively by flushing blazor-resource-hash:[YourWebsite] from the browser Local Storage and then clearing the browser cache. On the first visit, the app correctly uses SignalR while the WASM files download. Any subsequent refresh or visit then correctly uses the cached WASM version.

I honestly wish I had known about blazor-resource-hash in Local Storage earlier. It effectively acts as a flag that tells auto mode whether to use Interactive Server (SignalR) or WASM and is set after the full WASM is downloaded. 

This has been extremely helpful for testing both modes locally and in a staging environment.

**Comment by lfoust** [comment]
So is this just a matter of waiting for App Service to deploy the 10.0.2 runtime? As far as I can tell, App Service doesn't allow you to control what minor version of the runtime you want to run on

**Comment by frindler** [comment]
I see, looks like App Service hasn't been updated yet... That's what I'm getting on the console:


```
C:\home\site\wwwroot>dotnet --version
10.0.100

C:\home\site\wwwroot>dotnet --list-sdks
1.1.14 [C:\Program Files (x86)\dotnet\sdk]
2.1.526 [C:\Program Files (x86)\dotnet\sdk]
2.2.109 [C:\Program Files (x86)\dotnet\sdk]
3.1.426 [C:\Program Files (x86)\dotnet\sdk]
5.0.408 [C:\Program Files (x86)\dotnet\sdk]
6.0.428 [C:\Program Files (x86)\dotnet\sdk]
7.0.410 [C:\Program Files (x86)\dotnet\sdk]
8.0.416 [C:\Program Files (x86)\dotnet\sdk]
9.0.307 [C:\Program Files (x86)\dotnet\sdk]
10.0.100 [C:\Program Files (x86)\dotnet\sdk]

C:\home\site\wwwroot>dotnet --list-runtimes
Microsoft.AspNetCore.All 2.1.30 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.2.14 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.30 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.2.14 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.0.3 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.32 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.17 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.36 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.20 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 8.0.16 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 8.0.22 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 9.0.11 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 10.0.0 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 1.0.16 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 1.1.13 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.0.9 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.30 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.2.14 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.0.3 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.32 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.17 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.36 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.20 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.16 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.22 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 9.0.11 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 10.0.0 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by ManbirRakhra** [comment]
Thanks a lot. My project started working nicely.
